import { Service } from '../service';
import { RevenexxException, Client, type Payload, UploadProgress } from '../client';
import type { Models } from '../models';

import { Action } from '../enums/action';
import { Surface } from '../enums/surface';

export class ConsentManagerRecords {
    client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * Every record, filterable by column. There is no route that edits one — an update answers 405.
     *
     * @param {string} params.id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one; it reads one back and puts it in the path of later calls.
     * @param {string} params.consentId - Filter to rows whose `consent_id` is exactly this value. The random uuid v4 in the visitor's own `rvx_consent` cookie. It chains one browser's decisions and nothing else — it is never handed to a tag, and a full withdrawal mints a new one.
     * @param {Action} params.action - Filter to rows whose `action` is exactly this value. What the visitor did: accept_all, reject_all, custom, vendor_grant, withdraw or renew.
     * @param {Surface} params.surface - Filter to rows whose `surface` is exactly this value. Where they did it: first_layer, preferences, privacy_link or content_gate.
     * @param {string} params.policyVersionId - Filter to rows whose `policy_version_id` is exactly this value. The published version the visitor was shown.
     * @param {number} params.policyNumber - Filter to rows whose `policy_number` is exactly this value. That version's number.
     * @param {string} params.policySha256 - Filter to rows whose `policy_sha256` is exactly this value. That version's hash, copied in, so the record alone proves which text it points at.
     * @param {string} params.locale - Filter to rows whose `locale` is exactly this value. The language the visitor was shown.
     * @param {string} params.market - Filter to rows whose `market` is exactly this value. The market this row belongs to, by code — '' (empty) is the shop as a whole. Taken from the `x-revenexx-market` header of the call that wrote it, never from a body.
     * @param {string} params.recordedAt - Filter to rows whose `recorded_at` is exactly this value. When the server received the decision. This is the authoritative time.
     * @param {string} params.clientTs - Filter to rows whose `client_ts` is exactly this value. The visitor's clock when they decided, kept as a hint — a record retried on a later page view carries it.
     * @param {string} params.expiresAt - Filter to rows whose `expires_at` is exactly this value. When the decision lapses: the received time plus the version's consent lifetime. Retention of the newest record counts from here.
     * @param {string} params.userAgentClass - Filter to rows whose `user_agent_class` is exactly this value. The browser family and major version only — never the full user agent.
     * @param {string} params.pagePath - Filter to rows whose `page_path` is exactly this value. The path the decision was made on, without query or fragment, so no campaign id is ever stored.
     * @param {string} params.contactId - Filter to rows whose `contact_id` is exactly this value. The signed-in B2B contact, taken from the identity the gateway injected — never from the body. Set to null on an erasure request; the rest of the record stays.
     * @param {string} params.createdAt - Filter to rows whose `created_at` is exactly this value. When the row was created. Server-set.
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped.
     * @param {number} params.offset - Row offset (default 0).
     * @param {string} params.order - Sort by one column: 'column', 'column.asc' or 'column.desc'.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    consentManagerRecordsList(params?: { id?: string, consentId?: string, action?: Action, surface?: Surface, policyVersionId?: string, policyNumber?: number, policySha256?: string, locale?: string, market?: string, recordedAt?: string, clientTs?: string, expiresAt?: string, userAgentClass?: string, pagePath?: string, contactId?: string, createdAt?: string, limit?: number, offset?: number, order?: string }): Promise<{}>;
    /**
     * Every record, filterable by column. There is no route that edits one — an update answers 405.
     *
     * @param {string} id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one; it reads one back and puts it in the path of later calls.
     * @param {string} consentId - Filter to rows whose `consent_id` is exactly this value. The random uuid v4 in the visitor's own `rvx_consent` cookie. It chains one browser's decisions and nothing else — it is never handed to a tag, and a full withdrawal mints a new one.
     * @param {Action} action - Filter to rows whose `action` is exactly this value. What the visitor did: accept_all, reject_all, custom, vendor_grant, withdraw or renew.
     * @param {Surface} surface - Filter to rows whose `surface` is exactly this value. Where they did it: first_layer, preferences, privacy_link or content_gate.
     * @param {string} policyVersionId - Filter to rows whose `policy_version_id` is exactly this value. The published version the visitor was shown.
     * @param {number} policyNumber - Filter to rows whose `policy_number` is exactly this value. That version's number.
     * @param {string} policySha256 - Filter to rows whose `policy_sha256` is exactly this value. That version's hash, copied in, so the record alone proves which text it points at.
     * @param {string} locale - Filter to rows whose `locale` is exactly this value. The language the visitor was shown.
     * @param {string} market - Filter to rows whose `market` is exactly this value. The market this row belongs to, by code — '' (empty) is the shop as a whole. Taken from the `x-revenexx-market` header of the call that wrote it, never from a body.
     * @param {string} recordedAt - Filter to rows whose `recorded_at` is exactly this value. When the server received the decision. This is the authoritative time.
     * @param {string} clientTs - Filter to rows whose `client_ts` is exactly this value. The visitor's clock when they decided, kept as a hint — a record retried on a later page view carries it.
     * @param {string} expiresAt - Filter to rows whose `expires_at` is exactly this value. When the decision lapses: the received time plus the version's consent lifetime. Retention of the newest record counts from here.
     * @param {string} userAgentClass - Filter to rows whose `user_agent_class` is exactly this value. The browser family and major version only — never the full user agent.
     * @param {string} pagePath - Filter to rows whose `page_path` is exactly this value. The path the decision was made on, without query or fragment, so no campaign id is ever stored.
     * @param {string} contactId - Filter to rows whose `contact_id` is exactly this value. The signed-in B2B contact, taken from the identity the gateway injected — never from the body. Set to null on an erasure request; the rest of the record stays.
     * @param {string} createdAt - Filter to rows whose `created_at` is exactly this value. When the row was created. Server-set.
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped.
     * @param {number} offset - Row offset (default 0).
     * @param {string} order - Sort by one column: 'column', 'column.asc' or 'column.desc'.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    consentManagerRecordsList(id?: string, consentId?: string, action?: Action, surface?: Surface, policyVersionId?: string, policyNumber?: number, policySha256?: string, locale?: string, market?: string, recordedAt?: string, clientTs?: string, expiresAt?: string, userAgentClass?: string, pagePath?: string, contactId?: string, createdAt?: string, limit?: number, offset?: number, order?: string): Promise<{}>;
    consentManagerRecordsList(
        paramsOrFirst?: { id?: string, consentId?: string, action?: Action, surface?: Surface, policyVersionId?: string, policyNumber?: number, policySha256?: string, locale?: string, market?: string, recordedAt?: string, clientTs?: string, expiresAt?: string, userAgentClass?: string, pagePath?: string, contactId?: string, createdAt?: string, limit?: number, offset?: number, order?: string } | string,
        ...rest: [(string)?, (Action)?, (Surface)?, (string)?, (number)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (number)?, (number)?, (string)?]    
    ): Promise<{}> {
        let params: { id?: string, consentId?: string, action?: Action, surface?: Surface, policyVersionId?: string, policyNumber?: number, policySha256?: string, locale?: string, market?: string, recordedAt?: string, clientTs?: string, expiresAt?: string, userAgentClass?: string, pagePath?: string, contactId?: string, createdAt?: string, limit?: number, offset?: number, order?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id?: string, consentId?: string, action?: Action, surface?: Surface, policyVersionId?: string, policyNumber?: number, policySha256?: string, locale?: string, market?: string, recordedAt?: string, clientTs?: string, expiresAt?: string, userAgentClass?: string, pagePath?: string, contactId?: string, createdAt?: string, limit?: number, offset?: number, order?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                consentId: rest[0] as string,
                action: rest[1] as Action,
                surface: rest[2] as Surface,
                policyVersionId: rest[3] as string,
                policyNumber: rest[4] as number,
                policySha256: rest[5] as string,
                locale: rest[6] as string,
                market: rest[7] as string,
                recordedAt: rest[8] as string,
                clientTs: rest[9] as string,
                expiresAt: rest[10] as string,
                userAgentClass: rest[11] as string,
                pagePath: rest[12] as string,
                contactId: rest[13] as string,
                createdAt: rest[14] as string,
                limit: rest[15] as number,
                offset: rest[16] as number,
                order: rest[17] as string            
            };
        }
        
        const id = params.id;
        const consentId = params.consentId;
        const action = params.action;
        const surface = params.surface;
        const policyVersionId = params.policyVersionId;
        const policyNumber = params.policyNumber;
        const policySha256 = params.policySha256;
        const locale = params.locale;
        const market = params.market;
        const recordedAt = params.recordedAt;
        const clientTs = params.clientTs;
        const expiresAt = params.expiresAt;
        const userAgentClass = params.userAgentClass;
        const pagePath = params.pagePath;
        const contactId = params.contactId;
        const createdAt = params.createdAt;
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;


        const apiPath = '/v1/consent-manager/records';
        const apiPayload: Payload = {};
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof consentId !== 'undefined') {
            apiPayload['consent_id'] = consentId;
        }
        if (typeof action !== 'undefined') {
            apiPayload['action'] = action;
        }
        if (typeof surface !== 'undefined') {
            apiPayload['surface'] = surface;
        }
        if (typeof policyVersionId !== 'undefined') {
            apiPayload['policy_version_id'] = policyVersionId;
        }
        if (typeof policyNumber !== 'undefined') {
            apiPayload['policy_number'] = policyNumber;
        }
        if (typeof policySha256 !== 'undefined') {
            apiPayload['policy_sha256'] = policySha256;
        }
        if (typeof locale !== 'undefined') {
            apiPayload['locale'] = locale;
        }
        if (typeof market !== 'undefined') {
            apiPayload['market'] = market;
        }
        if (typeof recordedAt !== 'undefined') {
            apiPayload['recorded_at'] = recordedAt;
        }
        if (typeof clientTs !== 'undefined') {
            apiPayload['client_ts'] = clientTs;
        }
        if (typeof expiresAt !== 'undefined') {
            apiPayload['expires_at'] = expiresAt;
        }
        if (typeof userAgentClass !== 'undefined') {
            apiPayload['user_agent_class'] = userAgentClass;
        }
        if (typeof pagePath !== 'undefined') {
            apiPayload['page_path'] = pagePath;
        }
        if (typeof contactId !== 'undefined') {
            apiPayload['contact_id'] = contactId;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Stores one decision under the version that was shown. Every purpose of that version is stored explicitly — a consent purpose left out is denied. The contact comes from the identity the gateway injected, never from the body. No IP address, full user agent or query string is stored, whatever the request carries. Two identical decisions in a row under one version answer the existing record with 200 and `deduplicated: true`.
     *
     * @param {Action} params.action - What the visitor did: accept_all, reject_all, custom, vendor_grant, withdraw or renew.
     * @param {string} params.consentId - The random uuid v4 in the visitor's own `rvx_consent` cookie. It chains one browser's decisions and nothing else — it is never handed to a tag, and a full withdrawal mints a new one.
     * @param {string} params.locale - The language the visitor was shown; one the version holds.
     * @param {string} params.policyVersionId - The published version the visitor was shown.
     * @param {Surface} params.surface - Where they did it: first_layer, preferences, privacy_link or content_gate.
     * @param {string} params.clientTs - The visitor's clock when they decided, kept as a hint — a record retried on a later page view carries it.
     * @param {object} params.decisions - What was decided. Purposes and vendors by code, each granted, denied or objected. A consent purpose left out is stored denied.
     * @param {string} params.pagePath - The page the decision was made on. Any query or fragment is cut off before storing.
     * @param {string} params.userAgentClass - The browser as family and major version. A longer value is reduced to that; a full user agent is never stored.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentRecord>}
     */
    consentManagerRecordsCreate(params: { action: Action, consentId: string, locale: string, policyVersionId: string, surface: Surface, clientTs?: string, decisions?: object, pagePath?: string, userAgentClass?: string }): Promise<Models.ConsentRecord>;
    /**
     * Stores one decision under the version that was shown. Every purpose of that version is stored explicitly — a consent purpose left out is denied. The contact comes from the identity the gateway injected, never from the body. No IP address, full user agent or query string is stored, whatever the request carries. Two identical decisions in a row under one version answer the existing record with 200 and `deduplicated: true`.
     *
     * @param {Action} action - What the visitor did: accept_all, reject_all, custom, vendor_grant, withdraw or renew.
     * @param {string} consentId - The random uuid v4 in the visitor's own `rvx_consent` cookie. It chains one browser's decisions and nothing else — it is never handed to a tag, and a full withdrawal mints a new one.
     * @param {string} locale - The language the visitor was shown; one the version holds.
     * @param {string} policyVersionId - The published version the visitor was shown.
     * @param {Surface} surface - Where they did it: first_layer, preferences, privacy_link or content_gate.
     * @param {string} clientTs - The visitor's clock when they decided, kept as a hint — a record retried on a later page view carries it.
     * @param {object} decisions - What was decided. Purposes and vendors by code, each granted, denied or objected. A consent purpose left out is stored denied.
     * @param {string} pagePath - The page the decision was made on. Any query or fragment is cut off before storing.
     * @param {string} userAgentClass - The browser as family and major version. A longer value is reduced to that; a full user agent is never stored.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentRecord>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    consentManagerRecordsCreate(action: Action, consentId: string, locale: string, policyVersionId: string, surface: Surface, clientTs?: string, decisions?: object, pagePath?: string, userAgentClass?: string): Promise<Models.ConsentRecord>;
    consentManagerRecordsCreate(
        paramsOrFirst: { action: Action, consentId: string, locale: string, policyVersionId: string, surface: Surface, clientTs?: string, decisions?: object, pagePath?: string, userAgentClass?: string } | Action,
        ...rest: [(string)?, (string)?, (string)?, (Surface)?, (string)?, (object)?, (string)?, (string)?]    
    ): Promise<Models.ConsentRecord> {
        let params: { action: Action, consentId: string, locale: string, policyVersionId: string, surface: Surface, clientTs?: string, decisions?: object, pagePath?: string, userAgentClass?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst) && ('action' in paramsOrFirst || 'consentId' in paramsOrFirst || 'locale' in paramsOrFirst || 'policyVersionId' in paramsOrFirst || 'surface' in paramsOrFirst || 'clientTs' in paramsOrFirst || 'decisions' in paramsOrFirst || 'pagePath' in paramsOrFirst || 'userAgentClass' in paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { action: Action, consentId: string, locale: string, policyVersionId: string, surface: Surface, clientTs?: string, decisions?: object, pagePath?: string, userAgentClass?: string };
        } else {
            params = {
                action: paramsOrFirst as Action,
                consentId: rest[0] as string,
                locale: rest[1] as string,
                policyVersionId: rest[2] as string,
                surface: rest[3] as Surface,
                clientTs: rest[4] as string,
                decisions: rest[5] as object,
                pagePath: rest[6] as string,
                userAgentClass: rest[7] as string            
            };
        }
        
        const action = params.action;
        const consentId = params.consentId;
        const locale = params.locale;
        const policyVersionId = params.policyVersionId;
        const surface = params.surface;
        const clientTs = params.clientTs;
        const decisions = params.decisions;
        const pagePath = params.pagePath;
        const userAgentClass = params.userAgentClass;

        if (typeof action === 'undefined') {
            throw new RevenexxException('Missing required parameter: "action"');
        }
        if (typeof consentId === 'undefined') {
            throw new RevenexxException('Missing required parameter: "consentId"');
        }
        if (typeof locale === 'undefined') {
            throw new RevenexxException('Missing required parameter: "locale"');
        }
        if (typeof policyVersionId === 'undefined') {
            throw new RevenexxException('Missing required parameter: "policyVersionId"');
        }
        if (typeof surface === 'undefined') {
            throw new RevenexxException('Missing required parameter: "surface"');
        }

        const apiPath = '/v1/consent-manager/records';
        const apiPayload: Payload = {};
        if (typeof action !== 'undefined') {
            apiPayload['action'] = action;
        }
        if (typeof clientTs !== 'undefined') {
            apiPayload['client_ts'] = clientTs;
        }
        if (typeof consentId !== 'undefined') {
            apiPayload['consent_id'] = consentId;
        }
        if (typeof decisions !== 'undefined') {
            apiPayload['decisions'] = decisions;
        }
        if (typeof locale !== 'undefined') {
            apiPayload['locale'] = locale;
        }
        if (typeof pagePath !== 'undefined') {
            apiPayload['page_path'] = pagePath;
        }
        if (typeof policyVersionId !== 'undefined') {
            apiPayload['policy_version_id'] = policyVersionId;
        }
        if (typeof surface !== 'undefined') {
            apiPayload['surface'] = surface;
        }
        if (typeof userAgentClass !== 'undefined') {
            apiPayload['user_agent_class'] = userAgentClass;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Every record of one consent id, oldest first, each naming the version it was shown under.
     *
     * @param {string} params.consentId - The consent id from the visitor's cookie.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentHistory>}
     */
    consentManagerRecordsHistory(params: { consentId: string }): Promise<Models.ConsentHistory>;
    /**
     * Every record of one consent id, oldest first, each naming the version it was shown under.
     *
     * @param {string} consentId - The consent id from the visitor's cookie.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentHistory>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    consentManagerRecordsHistory(consentId: string): Promise<Models.ConsentHistory>;
    consentManagerRecordsHistory(
        paramsOrFirst: { consentId: string } | string    
    ): Promise<Models.ConsentHistory> {
        let params: { consentId: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { consentId: string };
        } else {
            params = {
                consentId: paramsOrFirst as string            
            };
        }
        
        const consentId = params.consentId;

        if (typeof consentId === 'undefined') {
            throw new RevenexxException('Missing required parameter: "consentId"');
        }

        const apiPath = '/v1/consent-manager/records/by-consent/{consent_id}'.replace('{consent_id}', consentId);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * The records received from `from` (inclusive) to `to` (exclusive), oldest first, as rows and as one CSV rendering. Every row names the version and hash it points to. At most 1000 rows per call; continue with `next_offset`.
     *
     * @param {string} params.from - Start of the period, inclusive.
     * @param {string} params.to - End of the period, exclusive.
     * @param {string} params.market - Only this market ('' = the shop).
     * @param {number} params.limit - Rows per call (max 1000).
     * @param {number} params.offset - Continue from here.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentExport>}
     */
    consentManagerRecordsExport(params?: { from?: string, to?: string, market?: string, limit?: number, offset?: number }): Promise<Models.ConsentExport>;
    /**
     * The records received from `from` (inclusive) to `to` (exclusive), oldest first, as rows and as one CSV rendering. Every row names the version and hash it points to. At most 1000 rows per call; continue with `next_offset`.
     *
     * @param {string} from - Start of the period, inclusive.
     * @param {string} to - End of the period, exclusive.
     * @param {string} market - Only this market ('' = the shop).
     * @param {number} limit - Rows per call (max 1000).
     * @param {number} offset - Continue from here.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentExport>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    consentManagerRecordsExport(from?: string, to?: string, market?: string, limit?: number, offset?: number): Promise<Models.ConsentExport>;
    consentManagerRecordsExport(
        paramsOrFirst?: { from?: string, to?: string, market?: string, limit?: number, offset?: number } | string,
        ...rest: [(string)?, (string)?, (number)?, (number)?]    
    ): Promise<Models.ConsentExport> {
        let params: { from?: string, to?: string, market?: string, limit?: number, offset?: number };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { from?: string, to?: string, market?: string, limit?: number, offset?: number };
        } else {
            params = {
                from: paramsOrFirst as string,
                to: rest[0] as string,
                market: rest[1] as string,
                limit: rest[2] as number,
                offset: rest[3] as number            
            };
        }
        
        const from = params.from;
        const to = params.to;
        const market = params.market;
        const limit = params.limit;
        const offset = params.offset;


        const apiPath = '/v1/consent-manager/records/export';
        const apiPayload: Payload = {};
        if (typeof from !== 'undefined') {
            apiPayload['from'] = from;
        }
        if (typeof to !== 'undefined') {
            apiPayload['to'] = to;
        }
        if (typeof market !== 'undefined') {
            apiPayload['market'] = market;
        }
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Deletes records that ended longer ago than `proof_retention_days` (never less than 365): superseded records from the time the same browser decided again, the newest one from its expiry. The newest record of a browser therefore stays while it is current. Previews unless `dry_run: false` is sent; the daily `prune-records` schedule runs it for real. Bounded per call — `has_more` says whether to call again.
     *
     * @param {boolean} params.dryRun - Defaults to true: report, delete nothing.
     * @throws {RevenexxException}
     * @returns {Promise<Models.PruneResponse>}
     */
    consentManagerRecordsPrune(params?: { dryRun?: boolean }): Promise<Models.PruneResponse>;
    /**
     * Deletes records that ended longer ago than `proof_retention_days` (never less than 365): superseded records from the time the same browser decided again, the newest one from its expiry. The newest record of a browser therefore stays while it is current. Previews unless `dry_run: false` is sent; the daily `prune-records` schedule runs it for real. Bounded per call — `has_more` says whether to call again.
     *
     * @param {boolean} dryRun - Defaults to true: report, delete nothing.
     * @throws {RevenexxException}
     * @returns {Promise<Models.PruneResponse>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    consentManagerRecordsPrune(dryRun?: boolean): Promise<Models.PruneResponse>;
    consentManagerRecordsPrune(
        paramsOrFirst?: { dryRun?: boolean } | boolean    
    ): Promise<Models.PruneResponse> {
        let params: { dryRun?: boolean };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { dryRun?: boolean };
        } else {
            params = {
                dryRun: paramsOrFirst as boolean            
            };
        }
        
        const dryRun = params.dryRun;


        const apiPath = '/v1/consent-manager/records/prune';
        const apiPayload: Payload = {};
        if (typeof dryRun !== 'undefined') {
            apiPayload['dry_run'] = dryRun;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Granted, denied and objected counts per purpose and counts per action for one market (`?market=`, else `x-revenexx-market`, else the shop) and an optional period. A statistic: it carries no consent id, record id or contact.
     *
     * @param {string} params.market - The market ('' = the shop).
     * @param {string} params.from - Start, inclusive.
     * @param {string} params.to - End, exclusive.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentSummary>}
     */
    consentManagerRecordsSummary(params?: { market?: string, from?: string, to?: string }): Promise<Models.ConsentSummary>;
    /**
     * Granted, denied and objected counts per purpose and counts per action for one market (`?market=`, else `x-revenexx-market`, else the shop) and an optional period. A statistic: it carries no consent id, record id or contact.
     *
     * @param {string} market - The market ('' = the shop).
     * @param {string} from - Start, inclusive.
     * @param {string} to - End, exclusive.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentSummary>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    consentManagerRecordsSummary(market?: string, from?: string, to?: string): Promise<Models.ConsentSummary>;
    consentManagerRecordsSummary(
        paramsOrFirst?: { market?: string, from?: string, to?: string } | string,
        ...rest: [(string)?, (string)?]    
    ): Promise<Models.ConsentSummary> {
        let params: { market?: string, from?: string, to?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { market?: string, from?: string, to?: string };
        } else {
            params = {
                market: paramsOrFirst as string,
                from: rest[0] as string,
                to: rest[1] as string            
            };
        }
        
        const market = params.market;
        const from = params.from;
        const to = params.to;


        const apiPath = '/v1/consent-manager/records/summary';
        const apiPayload: Payload = {};
        if (typeof market !== 'undefined') {
            apiPayload['market'] = market;
        }
        if (typeof from !== 'undefined') {
            apiPayload['from'] = from;
        }
        if (typeof to !== 'undefined') {
            apiPayload['to'] = to;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An erasure request for a signed-in contact: sets `contact_id` to null on every record of that contact and changes nothing else. The proof stays, because it is kept for legal claims (Art. 17 (3) e GDPR). The only mutation a record ever sees.
     *
     * @param {string} params.contactId - The contact to unlink.
     * @throws {RevenexxException}
     * @returns {Promise<Models.UnlinkContactResponse>}
     */
    consentManagerRecordsUnlinkContact(params: { contactId: string }): Promise<Models.UnlinkContactResponse>;
    /**
     * An erasure request for a signed-in contact: sets `contact_id` to null on every record of that contact and changes nothing else. The proof stays, because it is kept for legal claims (Art. 17 (3) e GDPR). The only mutation a record ever sees.
     *
     * @param {string} contactId - The contact to unlink.
     * @throws {RevenexxException}
     * @returns {Promise<Models.UnlinkContactResponse>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    consentManagerRecordsUnlinkContact(contactId: string): Promise<Models.UnlinkContactResponse>;
    consentManagerRecordsUnlinkContact(
        paramsOrFirst: { contactId: string } | string    
    ): Promise<Models.UnlinkContactResponse> {
        let params: { contactId: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { contactId: string };
        } else {
            params = {
                contactId: paramsOrFirst as string            
            };
        }
        
        const contactId = params.contactId;

        if (typeof contactId === 'undefined') {
            throw new RevenexxException('Missing required parameter: "contactId"');
        }

        const apiPath = '/v1/consent-manager/records/unlink-contact';
        const apiPayload: Payload = {};
        if (typeof contactId !== 'undefined') {
            apiPayload['contact_id'] = contactId;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * One record.
     *
     * @param {string} params.id - The record.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentRecord>}
     */
    consentManagerRecordsGet(params: { id: string }): Promise<Models.ConsentRecord>;
    /**
     * One record.
     *
     * @param {string} id - The record.
     * @throws {RevenexxException}
     * @returns {Promise<Models.ConsentRecord>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    consentManagerRecordsGet(id: string): Promise<Models.ConsentRecord>;
    consentManagerRecordsGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.ConsentRecord> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/consent-manager/records/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }
}
