import { Service } from '../service';
import { RevenexxException, Client, type Payload, UploadProgress } from '../client';
import type { Models } from '../models';

import { Tone } from '../enums/tone';
import { DocumentKindTone } from '../enums/document-kind-tone';
import { DocumentVocabularyPathName } from '../enums/document-vocabulary-path-name';

export class DocumentsKinds {
    client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. This is the list `documents.kind` is validated against on every write, so it is the first thing to read when a document is refused as an unknown kind. It SEEDS on read: a tenant whose table is empty — one whose install announcement never arrived — is given the four kinds here rather than being told it has none and then being unable to file anything. Exactly one row carries `is_default`, and the read repairs that too, so a client may rely on finding one.
     *
     * @param {string} params.id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} params.code - Look one kind up by the code a document stores. Unique per tenant, so this resolves a code a caller already holds without paging the list.
     * @param {string} params.title - Filter to rows whose `title` is exactly this value. What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.
     * @param {string} params.description - Filter to rows whose `description` is exactly this value. One sentence a person reads under the title — what this value is for. Optional.
     * @param {boolean} params.isDefault - Filter to the default kind. Exactly one row carries the flag, so `true` answers one.
     * @param {Tone} params.tone - Filter to rows whose `tone` is exactly this value. The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'.
     * @param {number} params.position - Filter to rows whose `position` is exactly this value. Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order.
     * @param {boolean} params.isSystem - Filter by whether this app seeded the value. `false` is the set a merchant added themselves.
     * @param {string} params.createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {string} params.updatedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} params.offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} params.order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    documentsKindsList(params?: { id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string }): Promise<{}>;
    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. This is the list `documents.kind` is validated against on every write, so it is the first thing to read when a document is refused as an unknown kind. It SEEDS on read: a tenant whose table is empty — one whose install announcement never arrived — is given the four kinds here rather than being told it has none and then being unable to file anything. Exactly one row carries `is_default`, and the read repairs that too, so a client may rely on finding one.
     *
     * @param {string} id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} code - Look one kind up by the code a document stores. Unique per tenant, so this resolves a code a caller already holds without paging the list.
     * @param {string} title - Filter to rows whose `title` is exactly this value. What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.
     * @param {string} description - Filter to rows whose `description` is exactly this value. One sentence a person reads under the title — what this value is for. Optional.
     * @param {boolean} isDefault - Filter to the default kind. Exactly one row carries the flag, so `true` answers one.
     * @param {Tone} tone - Filter to rows whose `tone` is exactly this value. The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'.
     * @param {number} position - Filter to rows whose `position` is exactly this value. Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order.
     * @param {boolean} isSystem - Filter by whether this app seeded the value. `false` is the set a merchant added themselves.
     * @param {string} createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {string} updatedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    documentsKindsList(id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string): Promise<{}>;
    documentsKindsList(
        paramsOrFirst?: { id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string } | string,
        ...rest: [(string)?, (string)?, (string)?, (boolean)?, (Tone)?, (number)?, (boolean)?, (string)?, (string)?, (number)?, (number)?, (string)?]    
    ): Promise<{}> {
        let params: { id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                code: rest[0] as string,
                title: rest[1] as string,
                description: rest[2] as string,
                isDefault: rest[3] as boolean,
                tone: rest[4] as Tone,
                position: rest[5] as number,
                isSystem: rest[6] as boolean,
                createdAt: rest[7] as string,
                updatedAt: rest[8] as string,
                limit: rest[9] as number,
                offset: rest[10] as number,
                order: rest[11] as string            
            };
        }
        
        const id = params.id;
        const code = params.code;
        const title = params.title;
        const description = params.description;
        const isDefault = params.isDefault;
        const tone = params.tone;
        const position = params.position;
        const isSystem = params.isSystem;
        const createdAt = params.createdAt;
        const updatedAt = params.updatedAt;
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;


        const apiPath = '/v1/documents/kinds';
        const apiPayload: Payload = {};
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof title !== 'undefined') {
            apiPayload['title'] = title;
        }
        if (typeof description !== 'undefined') {
            apiPayload['description'] = description;
        }
        if (typeof isDefault !== 'undefined') {
            apiPayload['is_default'] = isDefault;
        }
        if (typeof tone !== 'undefined') {
            apiPayload['tone'] = tone;
        }
        if (typeof position !== 'undefined') {
            apiPayload['position'] = position;
        }
        if (typeof isSystem !== 'undefined') {
            apiPayload['is_system'] = isSystem;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof updatedAt !== 'undefined') {
            apiPayload['updated_at'] = updatedAt;
        }
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. This is the route that makes the set open. A proforma invoice, a dunning letter, a works certificate or a scrap certificate is a kind this app was never going to enumerate, and a document may name it the moment it exists here — no release, no migration. `code` is lowercase letters, digits, `-` and `_`, unique per tenant and FIXED from here on; `title` is what a merchant renames later. The value is created as the merchant's own (`is_system: false`) and not as the default unless `is_default: true` says so, in which case whichever row held the flag is demoted in the same call.
     *
     * @param {string} params.code - The value's stable identifier, and the string a document stores in `kind`. Lowercase letters, digits, `-` and `_`, starting with a letter. Unique per tenant and FIXED once created: renaming it would orphan every document carrying it, so an edit that changes it is refused and the title is what a merchant renames.
     * @param {string} params.title - What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.
     * @param {string} params.description - One sentence a person reads under the title — what this value is for. Optional.
     * @param {object} params.descriptions - The description per language tag. Falls back to `description` when a tag is missing.
     * @param {boolean} params.isDefault - Whether this is the value a caller falls back to. Exactly ONE row of the table carries it: promoting another demotes the current one, so a client can mark the default without reading anything else. Deleting the default hands the flag to the first remaining row. Sending `true` promotes this value and demotes whichever held the flag. `false` is ignored — demote by promoting another.
     * @param {object} params.labels - The title per language tag, for a UI that has to render it in the reader's language. Falls back to `title` when a tag is missing.
     * @param {number} params.position - Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order. Defaults to 0.
     * @param {DocumentKindTone} params.tone - The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'. Defaults to 'neutral' on a value a merchant creates.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKind>}
     */
    documentsKindsCreate(params: { code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, tone?: DocumentKindTone }): Promise<Models.DocumentKind>;
    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. This is the route that makes the set open. A proforma invoice, a dunning letter, a works certificate or a scrap certificate is a kind this app was never going to enumerate, and a document may name it the moment it exists here — no release, no migration. `code` is lowercase letters, digits, `-` and `_`, unique per tenant and FIXED from here on; `title` is what a merchant renames later. The value is created as the merchant's own (`is_system: false`) and not as the default unless `is_default: true` says so, in which case whichever row held the flag is demoted in the same call.
     *
     * @param {string} code - The value's stable identifier, and the string a document stores in `kind`. Lowercase letters, digits, `-` and `_`, starting with a letter. Unique per tenant and FIXED once created: renaming it would orphan every document carrying it, so an edit that changes it is refused and the title is what a merchant renames.
     * @param {string} title - What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.
     * @param {string} description - One sentence a person reads under the title — what this value is for. Optional.
     * @param {object} descriptions - The description per language tag. Falls back to `description` when a tag is missing.
     * @param {boolean} isDefault - Whether this is the value a caller falls back to. Exactly ONE row of the table carries it: promoting another demotes the current one, so a client can mark the default without reading anything else. Deleting the default hands the flag to the first remaining row. Sending `true` promotes this value and demotes whichever held the flag. `false` is ignored — demote by promoting another.
     * @param {object} labels - The title per language tag, for a UI that has to render it in the reader's language. Falls back to `title` when a tag is missing.
     * @param {number} position - Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order. Defaults to 0.
     * @param {DocumentKindTone} tone - The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'. Defaults to 'neutral' on a value a merchant creates.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKind>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    documentsKindsCreate(code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, tone?: DocumentKindTone): Promise<Models.DocumentKind>;
    documentsKindsCreate(
        paramsOrFirst: { code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, tone?: DocumentKindTone } | string,
        ...rest: [(string)?, (string)?, (object)?, (boolean)?, (object)?, (number)?, (DocumentKindTone)?]    
    ): Promise<Models.DocumentKind> {
        let params: { code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, tone?: DocumentKindTone };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, tone?: DocumentKindTone };
        } else {
            params = {
                code: paramsOrFirst as string,
                title: rest[0] as string,
                description: rest[1] as string,
                descriptions: rest[2] as object,
                isDefault: rest[3] as boolean,
                labels: rest[4] as object,
                position: rest[5] as number,
                tone: rest[6] as DocumentKindTone            
            };
        }
        
        const code = params.code;
        const title = params.title;
        const description = params.description;
        const descriptions = params.descriptions;
        const isDefault = params.isDefault;
        const labels = params.labels;
        const position = params.position;
        const tone = params.tone;

        if (typeof code === 'undefined') {
            throw new RevenexxException('Missing required parameter: "code"');
        }
        if (typeof title === 'undefined') {
            throw new RevenexxException('Missing required parameter: "title"');
        }

        const apiPath = '/v1/documents/kinds';
        const apiPayload: Payload = {};
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof description !== 'undefined') {
            apiPayload['description'] = description;
        }
        if (typeof descriptions !== 'undefined') {
            apiPayload['descriptions'] = descriptions;
        }
        if (typeof isDefault !== 'undefined') {
            apiPayload['is_default'] = isDefault;
        }
        if (typeof labels !== 'undefined') {
            apiPayload['labels'] = labels;
        }
        if (typeof position !== 'undefined') {
            apiPayload['position'] = position;
        }
        if (typeof title !== 'undefined') {
            apiPayload['title'] = title;
        }
        if (typeof tone !== 'undefined') {
            apiPayload['tone'] = tone;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. Seeds `invoice`, `delivery_note`, `credit_note` and `return_receipt`, with `invoice` as the default. IDEMPOTENT BY CODE: a kind the tenant already has is left exactly as it is, including a title they changed and a tone they re-picked, so a second call reports it under `existing` and writes nothing. The same seed runs on the app.installed announcement and lazily on the first list read — three paths, because the marketplace does not reliably fire the install event and a tenant with no kinds can file no documents.
     *
     * @param {object} params.data - Request body
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKindsSeedResult>}
     */
    documentsKindsDefaults(params: { data: object }): Promise<Models.DocumentKindsSeedResult>;
    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. Seeds `invoice`, `delivery_note`, `credit_note` and `return_receipt`, with `invoice` as the default. IDEMPOTENT BY CODE: a kind the tenant already has is left exactly as it is, including a title they changed and a tone they re-picked, so a second call reports it under `existing` and writes nothing. The same seed runs on the app.installed announcement and lazily on the first list read — three paths, because the marketplace does not reliably fire the install event and a tenant with no kinds can file no documents.
     *
     * @param {object} data - Request body
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKindsSeedResult>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    documentsKindsDefaults(data: object): Promise<Models.DocumentKindsSeedResult>;
    documentsKindsDefaults(
        paramsOrFirst: { data: object } | object    
    ): Promise<Models.DocumentKindsSeedResult> {
        let params: { data: object };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst) && ('data' in paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { data: object };
        } else {
            params = {
                data: paramsOrFirst as object            
            };
        }
        
        const data = params.data;

        if (typeof data === 'undefined') {
            throw new RevenexxException('Missing required parameter: "data"');
        }

        const apiPath = '/v1/documents/kinds/defaults';
        const apiPayload: Payload = {};
        if (typeof data !== 'undefined') {
            Object.assign(apiPayload, data);
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. Two refusals stand in for the foreign key these rows deliberately have not got. A kind at least one document still carries is a 409, because there is no reference to break — the alternative is a document whose kind nothing can render. And the LAST kind is a 409 whatever else is true, because every document carries one and a merchant with none could file nothing. Deleting the default hands the flag to the first remaining row, so a client may still rely on finding one.
     *
     * @param {string} params.id - The document kind to remove.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    documentsKindsDelete(params: { id: string }): Promise<{}>;
    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. Two refusals stand in for the foreign key these rows deliberately have not got. A kind at least one document still carries is a 409, because there is no reference to break — the alternative is a document whose kind nothing can render. And the LAST kind is a 409 whatever else is true, because every document carries one and a merchant with none could file nothing. Deleting the default hands the flag to the first remaining row, so a client may still rely on finding one.
     *
     * @param {string} id - The document kind to remove.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    documentsKindsDelete(id: string): Promise<{}>;
    documentsKindsDelete(
        paramsOrFirst: { id: string } | string    
    ): Promise<{}> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/documents/kinds/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'delete',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. The route that turns an id back into a kind. Unlike the list it does NOT seed, so on a fresh tenant read the list first — and note that a document stores the `code`, never this id, which is why the code cannot change.
     *
     * @param {string} params.id - The document kind to read.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKind>}
     */
    documentsKindsGet(params: { id: string }): Promise<Models.DocumentKind>;
    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. The route that turns an id back into a kind. Unlike the list it does NOT seed, so on a fresh tenant read the list first — and note that a document stores the `code`, never this id, which is why the code cannot change.
     *
     * @param {string} id - The document kind to read.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKind>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    documentsKindsGet(id: string): Promise<Models.DocumentKind>;
    documentsKindsGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.DocumentKind> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/documents/kinds/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. What a merchant edits here is the WORDS: the title, the per-language labels, the description, the badge tone and the position in a select. What they cannot edit is the `code` — every document stores it, so renaming it would orphan each one, and a body that changes it is refused with a 400 that says to create a new kind and move the documents over. A seeded kind is as editable as any other: `is_system` records that this app put the row there and grants it no protection.
     *
     * @param {string} params.id - The document kind to edit.
     * @param {string} params.code - The value's stable identifier, and the string a document stores in `kind`. Lowercase letters, digits, `-` and `_`, starting with a letter. Unique per tenant and FIXED once created: renaming it would orphan every document carrying it, so an edit that changes it is refused and the title is what a merchant renames.
     * @param {string} params.description - One sentence a person reads under the title — what this value is for. Optional.
     * @param {object} params.descriptions - The description per language tag. Falls back to `description` when a tag is missing.
     * @param {boolean} params.isDefault - Whether this is the value a caller falls back to. Exactly ONE row of the table carries it: promoting another demotes the current one, so a client can mark the default without reading anything else. Deleting the default hands the flag to the first remaining row. Sending `true` promotes this value and demotes whichever held the flag. `false` is ignored — demote by promoting another.
     * @param {object} params.labels - The title per language tag, for a UI that has to render it in the reader's language. Falls back to `title` when a tag is missing.
     * @param {number} params.position - Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order. Defaults to 0.
     * @param {string} params.title - What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.
     * @param {DocumentKindTone} params.tone - The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'. Defaults to 'neutral' on a value a merchant creates.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKind>}
     */
    documentsKindsUpdate(params: { id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, title?: string, tone?: DocumentKindTone }): Promise<Models.DocumentKind>;
    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. What a merchant edits here is the WORDS: the title, the per-language labels, the description, the badge tone and the position in a select. What they cannot edit is the `code` — every document stores it, so renaming it would orphan each one, and a body that changes it is refused with a 400 that says to create a new kind and move the documents over. A seeded kind is as editable as any other: `is_system` records that this app put the row there and grants it no protection.
     *
     * @param {string} id - The document kind to edit.
     * @param {string} code - The value's stable identifier, and the string a document stores in `kind`. Lowercase letters, digits, `-` and `_`, starting with a letter. Unique per tenant and FIXED once created: renaming it would orphan every document carrying it, so an edit that changes it is refused and the title is what a merchant renames.
     * @param {string} description - One sentence a person reads under the title — what this value is for. Optional.
     * @param {object} descriptions - The description per language tag. Falls back to `description` when a tag is missing.
     * @param {boolean} isDefault - Whether this is the value a caller falls back to. Exactly ONE row of the table carries it: promoting another demotes the current one, so a client can mark the default without reading anything else. Deleting the default hands the flag to the first remaining row. Sending `true` promotes this value and demotes whichever held the flag. `false` is ignored — demote by promoting another.
     * @param {object} labels - The title per language tag, for a UI that has to render it in the reader's language. Falls back to `title` when a tag is missing.
     * @param {number} position - Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order. Defaults to 0.
     * @param {string} title - What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.
     * @param {DocumentKindTone} tone - The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'. Defaults to 'neutral' on a value a merchant creates.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKind>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    documentsKindsUpdate(id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, title?: string, tone?: DocumentKindTone): Promise<Models.DocumentKind>;
    documentsKindsUpdate(
        paramsOrFirst: { id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, title?: string, tone?: DocumentKindTone } | string,
        ...rest: [(string)?, (string)?, (object)?, (boolean)?, (object)?, (number)?, (string)?, (DocumentKindTone)?]    
    ): Promise<Models.DocumentKind> {
        let params: { id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, title?: string, tone?: DocumentKindTone };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, labels?: object, position?: number, title?: string, tone?: DocumentKindTone };
        } else {
            params = {
                id: paramsOrFirst as string,
                code: rest[0] as string,
                description: rest[1] as string,
                descriptions: rest[2] as object,
                isDefault: rest[3] as boolean,
                labels: rest[4] as object,
                position: rest[5] as number,
                title: rest[6] as string,
                tone: rest[7] as DocumentKindTone            
            };
        }
        
        const id = params.id;
        const code = params.code;
        const description = params.description;
        const descriptions = params.descriptions;
        const isDefault = params.isDefault;
        const labels = params.labels;
        const position = params.position;
        const title = params.title;
        const tone = params.tone;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/documents/kinds/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof description !== 'undefined') {
            apiPayload['description'] = description;
        }
        if (typeof descriptions !== 'undefined') {
            apiPayload['descriptions'] = descriptions;
        }
        if (typeof isDefault !== 'undefined') {
            apiPayload['is_default'] = isDefault;
        }
        if (typeof labels !== 'undefined') {
            apiPayload['labels'] = labels;
        }
        if (typeof position !== 'undefined') {
            apiPayload['position'] = position;
        }
        if (typeof title !== 'undefined') {
            apiPayload['title'] = title;
        }
        if (typeof tone !== 'undefined') {
            apiPayload['tone'] = tone;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'put',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. The default flag is a SINGLE answer, not a per-row opinion, so moving it is a single call: this row is promoted and whichever held it is demoted, in one request. `PUT` with `is_default: true` does the same thing as a side effect of an edit — this exists because a client that wants nothing but the flag moved should not have to send one, and because promoting and demoting in two calls can leave two defaults or none.
     *
     * @param {string} params.id - The document kind to make the default.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKind>}
     */
    documentsKindsMakeDefault(params: { id: string }): Promise<Models.DocumentKind>;
    /**
     * A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. The default flag is a SINGLE answer, not a per-row opinion, so moving it is a single call: this row is promoted and whichever held it is demoted, in one request. `PUT` with `is_default: true` does the same thing as a side effect of an edit — this exists because a client that wants nothing but the flag moved should not have to send one, and because promoting and demoting in two calls can leave two defaults or none.
     *
     * @param {string} id - The document kind to make the default.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentKind>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    documentsKindsMakeDefault(id: string): Promise<Models.DocumentKind>;
    documentsKindsMakeDefault(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.DocumentKind> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/documents/kinds/{id}/make-default'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * The index of the value sets this app owns, with their titles and no values — the cheap read a client makes once. Two are published, and they differ in WHO owns the set: `kinds` is the merchant's own table, so it is read per request and a merchant may extend it; `visibilities` is the database CHECK, so it is closed and a merchant cannot. A client holding `'documents.kinds'` builds `GET /documents/vocabularies/kinds` with no further knowledge, which is the point of every app serving these two routes under its own prefix.
     *
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentVocabularyIndex>}
     */
    documentsVocabulariesList(): Promise<Models.DocumentVocabularyIndex> {

        const apiPath = '/v1/documents/vocabularies';
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * One vocabulary and every value in it, each with the title, description and badge tone a screen renders — which is the reason this route exists at all: a UI that keeps its own copy of the list is a UI that eventually offers a value the data refuses. `source` says where the set comes from and is the field to branch on: 'table' means the merchant owns it (`kinds`), so the answer is their rows in their order and `is_default` marks the fallback; 'schema' means a database CHECK owns it (`visibilities`), so the served set is the enforced set by construction. `closed` is true either way — the set is exhaustive at this moment, so a value outside it is stale data rather than a missing label. Reading `kinds` SEEDS an empty table, exactly as the kinds list does.
     *
     * @param {DocumentVocabularyPathName} params.name - The vocabulary to read, as GET /documents/vocabularies names it.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentVocabulary>}
     */
    documentsVocabulariesGet(params: { name: DocumentVocabularyPathName }): Promise<Models.DocumentVocabulary>;
    /**
     * One vocabulary and every value in it, each with the title, description and badge tone a screen renders — which is the reason this route exists at all: a UI that keeps its own copy of the list is a UI that eventually offers a value the data refuses. `source` says where the set comes from and is the field to branch on: 'table' means the merchant owns it (`kinds`), so the answer is their rows in their order and `is_default` marks the fallback; 'schema' means a database CHECK owns it (`visibilities`), so the served set is the enforced set by construction. `closed` is true either way — the set is exhaustive at this moment, so a value outside it is stale data rather than a missing label. Reading `kinds` SEEDS an empty table, exactly as the kinds list does.
     *
     * @param {DocumentVocabularyPathName} name - The vocabulary to read, as GET /documents/vocabularies names it.
     * @throws {RevenexxException}
     * @returns {Promise<Models.DocumentVocabulary>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    documentsVocabulariesGet(name: DocumentVocabularyPathName): Promise<Models.DocumentVocabulary>;
    documentsVocabulariesGet(
        paramsOrFirst: { name: DocumentVocabularyPathName } | DocumentVocabularyPathName    
    ): Promise<Models.DocumentVocabulary> {
        let params: { name: DocumentVocabularyPathName };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst) && ('name' in paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { name: DocumentVocabularyPathName };
        } else {
            params = {
                name: paramsOrFirst as DocumentVocabularyPathName            
            };
        }
        
        const name = params.name;

        if (typeof name === 'undefined') {
            throw new RevenexxException('Missing required parameter: "name"');
        }

        const apiPath = '/v1/documents/vocabularies/{name}'.replace('{name}', name);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }
}
