import { Service } from '../service';
import { RevenexxException, Client, type Payload, UploadProgress } from '../client';
import type { Models } from '../models';

import { InventoriesLocationsListType } from '../enums/inventories-locations-list-type';
import { LocationType } from '../enums/location-type';

export class InventoriesLocations {
    client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * A location is WHERE stock is kept — a warehouse, a shop floor, a supplier that dropships, or a virtual bucket for pre-orders and quarantine. It holds no quantity of its own: what is at it is a stock level. `type` is descriptive and nothing branches on it; `priority` is the number that decides which location a reservation is served from, and `enabled` decides whether it is offered at all. This is the list a `location_code` is resolved against on every stock call, so it is the first thing to read when a receipt answers "unknown location". It answers no quantities at all — how much is at a location is GET /inventories/stock?location_id=…, and what may still be sold is POST /inventories/availability. Filter `?enabled=true` for the operational subset: availability and reserve only ever look at enabled locations, so a disabled one is invisible to a shop while keeping every row that points at it.
     *
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} params.offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} params.order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @param {string} params.id - Exact-match filter on `id`. The row's own id, generated by the database.
     * @param {string} params.code - Exact-match filter on `code`. Unique per tenant, so this resolves a code a caller already holds without paging the whole list.
     * @param {string} params.name - Exact-match filter on `name`. What the place is called for an operator, in the tenant's working language.
     * @param {string} params.labels - Exact-match filter on `labels`. The location name per language tag, for a UI that has to render it in the reader's language. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {InventoriesLocationsListType} params.type - Exact-match filter on `type`. What kind of place holds the stock. Descriptive only — sourcing order comes from `priority`.
     * @param {number} params.priority - Exact-match filter on `priority`. Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred.
     * @param {boolean} params.enabled - Exact-match filter on `enabled`. Only enabled locations are ever served by availability or reserve, so `true` is the operational subset.
     * @param {string} params.address - Exact-match filter on `address`. Where the location physically is. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {string} params.metadata - Exact-match filter on `metadata`. Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {string} params.externalId - Exact-match filter on `external_id`. The key this row has in the system that OWNS it.
     * @param {string} params.externalRefs - Exact-match filter on `external_refs`. Every OTHER system that knows this row, keyed by system name. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {string} params.sourceSyncedAt - Exact-match filter on `source_synced_at`. When this row was last confirmed against its source.
     * @param {string} params.sourceData - Exact-match filter on `source_data`. What the source said about this row, kept as it said it. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {string} params.createdAt - Exact-match filter on `created_at`. When the row was created.
     * @param {string} params.updatedAt - Exact-match filter on `updated_at`. When the row was last written.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    inventoriesLocationsList(params?: { limit?: number, offset?: number, order?: string, id?: string, code?: string, name?: string, labels?: string, type?: InventoriesLocationsListType, priority?: number, enabled?: boolean, address?: string, metadata?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string }): Promise<{}>;
    /**
     * A location is WHERE stock is kept — a warehouse, a shop floor, a supplier that dropships, or a virtual bucket for pre-orders and quarantine. It holds no quantity of its own: what is at it is a stock level. `type` is descriptive and nothing branches on it; `priority` is the number that decides which location a reservation is served from, and `enabled` decides whether it is offered at all. This is the list a `location_code` is resolved against on every stock call, so it is the first thing to read when a receipt answers "unknown location". It answers no quantities at all — how much is at a location is GET /inventories/stock?location_id=…, and what may still be sold is POST /inventories/availability. Filter `?enabled=true` for the operational subset: availability and reserve only ever look at enabled locations, so a disabled one is invisible to a shop while keeping every row that points at it.
     *
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @param {string} id - Exact-match filter on `id`. The row's own id, generated by the database.
     * @param {string} code - Exact-match filter on `code`. Unique per tenant, so this resolves a code a caller already holds without paging the whole list.
     * @param {string} name - Exact-match filter on `name`. What the place is called for an operator, in the tenant's working language.
     * @param {string} labels - Exact-match filter on `labels`. The location name per language tag, for a UI that has to render it in the reader's language. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {InventoriesLocationsListType} type - Exact-match filter on `type`. What kind of place holds the stock. Descriptive only — sourcing order comes from `priority`.
     * @param {number} priority - Exact-match filter on `priority`. Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred.
     * @param {boolean} enabled - Exact-match filter on `enabled`. Only enabled locations are ever served by availability or reserve, so `true` is the operational subset.
     * @param {string} address - Exact-match filter on `address`. Where the location physically is. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {string} metadata - Exact-match filter on `metadata`. Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {string} externalId - Exact-match filter on `external_id`. The key this row has in the system that OWNS it.
     * @param {string} externalRefs - Exact-match filter on `external_refs`. Every OTHER system that knows this row, keyed by system name. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {string} sourceSyncedAt - Exact-match filter on `source_synced_at`. When this row was last confirmed against its source.
     * @param {string} sourceData - Exact-match filter on `source_data`. What the source said about this row, kept as it said it. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
     * @param {string} createdAt - Exact-match filter on `created_at`. When the row was created.
     * @param {string} updatedAt - Exact-match filter on `updated_at`. When the row was last written.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    inventoriesLocationsList(limit?: number, offset?: number, order?: string, id?: string, code?: string, name?: string, labels?: string, type?: InventoriesLocationsListType, priority?: number, enabled?: boolean, address?: string, metadata?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string): Promise<{}>;
    inventoriesLocationsList(
        paramsOrFirst?: { limit?: number, offset?: number, order?: string, id?: string, code?: string, name?: string, labels?: string, type?: InventoriesLocationsListType, priority?: number, enabled?: boolean, address?: string, metadata?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string } | number,
        ...rest: [(number)?, (string)?, (string)?, (string)?, (string)?, (string)?, (InventoriesLocationsListType)?, (number)?, (boolean)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?]    
    ): Promise<{}> {
        let params: { limit?: number, offset?: number, order?: string, id?: string, code?: string, name?: string, labels?: string, type?: InventoriesLocationsListType, priority?: number, enabled?: boolean, address?: string, metadata?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { limit?: number, offset?: number, order?: string, id?: string, code?: string, name?: string, labels?: string, type?: InventoriesLocationsListType, priority?: number, enabled?: boolean, address?: string, metadata?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string };
        } else {
            params = {
                limit: paramsOrFirst as number,
                offset: rest[0] as number,
                order: rest[1] as string,
                id: rest[2] as string,
                code: rest[3] as string,
                name: rest[4] as string,
                labels: rest[5] as string,
                type: rest[6] as InventoriesLocationsListType,
                priority: rest[7] as number,
                enabled: rest[8] as boolean,
                address: rest[9] as string,
                metadata: rest[10] as string,
                externalId: rest[11] as string,
                externalRefs: rest[12] as string,
                sourceSyncedAt: rest[13] as string,
                sourceData: rest[14] as string,
                createdAt: rest[15] as string,
                updatedAt: rest[16] as string            
            };
        }
        
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;
        const id = params.id;
        const code = params.code;
        const name = params.name;
        const labels = params.labels;
        const type = params.type;
        const priority = params.priority;
        const enabled = params.enabled;
        const address = params.address;
        const metadata = params.metadata;
        const externalId = params.externalId;
        const externalRefs = params.externalRefs;
        const sourceSyncedAt = params.sourceSyncedAt;
        const sourceData = params.sourceData;
        const createdAt = params.createdAt;
        const updatedAt = params.updatedAt;


        const apiPath = '/v1/inventories/locations';
        const apiPayload: Payload = {};
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof name !== 'undefined') {
            apiPayload['name'] = name;
        }
        if (typeof labels !== 'undefined') {
            apiPayload['labels'] = labels;
        }
        if (typeof type !== 'undefined') {
            apiPayload['type'] = type;
        }
        if (typeof priority !== 'undefined') {
            apiPayload['priority'] = priority;
        }
        if (typeof enabled !== 'undefined') {
            apiPayload['enabled'] = enabled;
        }
        if (typeof address !== 'undefined') {
            apiPayload['address'] = address;
        }
        if (typeof metadata !== 'undefined') {
            apiPayload['metadata'] = metadata;
        }
        if (typeof externalId !== 'undefined') {
            apiPayload['external_id'] = externalId;
        }
        if (typeof externalRefs !== 'undefined') {
            apiPayload['external_refs'] = externalRefs;
        }
        if (typeof sourceSyncedAt !== 'undefined') {
            apiPayload['source_synced_at'] = sourceSyncedAt;
        }
        if (typeof sourceData !== 'undefined') {
            apiPayload['source_data'] = sourceData;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof updatedAt !== 'undefined') {
            apiPayload['updated_at'] = updatedAt;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Registers a new place stock can be kept, and `type` says what kind of place it is: a warehouse of your own, a store whose shop floor a click-and-collect order draws on, a dropship supplier whose stock this row only tracks, or a virtual bucket that is not a building at all — pre-orders, consignment, a quarantine shelf. A create cannot omit `code` and `name`; every other column is optional or defaulted by the database. Two rows of this tenant may not share `code` and `external_id` — that is the 409, and it answers an update that moves a row onto a sibling's value exactly as it answers a second insert. A new location starts EMPTY and creating one moves nothing: stock arrives through POST /inventories/receive, or is transferred by two adjustments, one negative at the old location and one positive here. Mind the two columns that are not decoration — `priority` decides where a reservation is served from before `type` ever does (nothing branches on `type`), and `enabled` defaults to true, so a location created for a warehouse that has not opened yet starts being offered by availability and reserve immediately.
     *
     * @param {string} params.code - The location's stable identifier, and the name every stock call uses instead of an id: `location_code` on receive / adjust / restock / reserve, and the `default_location_code` setting. Unique per tenant, at least one character (CHECK `length(code) > 0`). Every tenant starts with `main` — POST /inventories/locations/defaults seeds it and the app.installed event runs the same seed — so `main` is the one code that resolves everywhere.
     * @param {string} params.name - What the place is called for an operator, in the tenant's working language. At least one character (CHECK `length(name) > 0`). It is a label only: nothing addresses a location by name.
     * @param {object} params.address - Where the location physically is. Free-form, and one key is READ: `country`, an ISO country code, which POST /inventories/reserve compares (case-insensitively) against `ship_to.country` when `allocation_strategy` is 'nearest' — that is what stops a German order pulling from the US warehouse because it happens to sort first. The keys the cockpit form writes are `street`, `postal_code`, `city`, `country`; anything else a tenant stores is kept and ignored.
     * @param {boolean} params.enabled - Whether this location takes part in stock at all. POST /inventories/availability and POST /inventories/reserve look at enabled locations and nothing else, so switching this off hides a location's stock from the storefront without deleting a row or losing a single ledger booking; its stock stays readable through GET /inventories/stock. Defaults to true.
     * @param {object} params.labels - The location name per language tag, for a UI that has to render it in the reader's language. Falls back to `name` when a tag is missing. Keys are language tags, values plain strings.
     * @param {object} params.metadata - Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. No route in this app reads it; it is stored and handed back unchanged.
     * @param {number} params.priority - Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred. Locations that tie keep the order the database returns them in — give every location a distinct priority if the order matters. Defaults to 0.
     * @param {LocationType} params.type - What kind of place holds the stock. 'warehouse' — own stock, the default. 'store' — a retail floor, the stock a click-and-collect order draws on. 'dropship' — a supplier ships it and this row tracks what they say they hold. 'virtual' — a bucket that is not a building (pre-orders, consignment, a quarantine shelf). Descriptive only: sourcing order comes from `priority`, and no route in this app treats one type differently from another. Defaults to 'warehouse'.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Location>}
     */
    inventoriesLocationsCreate(params: { code: string, name: string, address?: object, enabled?: boolean, labels?: object, metadata?: object, priority?: number, type?: LocationType }): Promise<Models.Location>;
    /**
     * Registers a new place stock can be kept, and `type` says what kind of place it is: a warehouse of your own, a store whose shop floor a click-and-collect order draws on, a dropship supplier whose stock this row only tracks, or a virtual bucket that is not a building at all — pre-orders, consignment, a quarantine shelf. A create cannot omit `code` and `name`; every other column is optional or defaulted by the database. Two rows of this tenant may not share `code` and `external_id` — that is the 409, and it answers an update that moves a row onto a sibling's value exactly as it answers a second insert. A new location starts EMPTY and creating one moves nothing: stock arrives through POST /inventories/receive, or is transferred by two adjustments, one negative at the old location and one positive here. Mind the two columns that are not decoration — `priority` decides where a reservation is served from before `type` ever does (nothing branches on `type`), and `enabled` defaults to true, so a location created for a warehouse that has not opened yet starts being offered by availability and reserve immediately.
     *
     * @param {string} code - The location's stable identifier, and the name every stock call uses instead of an id: `location_code` on receive / adjust / restock / reserve, and the `default_location_code` setting. Unique per tenant, at least one character (CHECK `length(code) > 0`). Every tenant starts with `main` — POST /inventories/locations/defaults seeds it and the app.installed event runs the same seed — so `main` is the one code that resolves everywhere.
     * @param {string} name - What the place is called for an operator, in the tenant's working language. At least one character (CHECK `length(name) > 0`). It is a label only: nothing addresses a location by name.
     * @param {object} address - Where the location physically is. Free-form, and one key is READ: `country`, an ISO country code, which POST /inventories/reserve compares (case-insensitively) against `ship_to.country` when `allocation_strategy` is 'nearest' — that is what stops a German order pulling from the US warehouse because it happens to sort first. The keys the cockpit form writes are `street`, `postal_code`, `city`, `country`; anything else a tenant stores is kept and ignored.
     * @param {boolean} enabled - Whether this location takes part in stock at all. POST /inventories/availability and POST /inventories/reserve look at enabled locations and nothing else, so switching this off hides a location's stock from the storefront without deleting a row or losing a single ledger booking; its stock stays readable through GET /inventories/stock. Defaults to true.
     * @param {object} labels - The location name per language tag, for a UI that has to render it in the reader's language. Falls back to `name` when a tag is missing. Keys are language tags, values plain strings.
     * @param {object} metadata - Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. No route in this app reads it; it is stored and handed back unchanged.
     * @param {number} priority - Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred. Locations that tie keep the order the database returns them in — give every location a distinct priority if the order matters. Defaults to 0.
     * @param {LocationType} type - What kind of place holds the stock. 'warehouse' — own stock, the default. 'store' — a retail floor, the stock a click-and-collect order draws on. 'dropship' — a supplier ships it and this row tracks what they say they hold. 'virtual' — a bucket that is not a building (pre-orders, consignment, a quarantine shelf). Descriptive only: sourcing order comes from `priority`, and no route in this app treats one type differently from another. Defaults to 'warehouse'.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Location>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    inventoriesLocationsCreate(code: string, name: string, address?: object, enabled?: boolean, labels?: object, metadata?: object, priority?: number, type?: LocationType): Promise<Models.Location>;
    inventoriesLocationsCreate(
        paramsOrFirst: { code: string, name: string, address?: object, enabled?: boolean, labels?: object, metadata?: object, priority?: number, type?: LocationType } | string,
        ...rest: [(string)?, (object)?, (boolean)?, (object)?, (object)?, (number)?, (LocationType)?]    
    ): Promise<Models.Location> {
        let params: { code: string, name: string, address?: object, enabled?: boolean, labels?: object, metadata?: object, priority?: number, type?: LocationType };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { code: string, name: string, address?: object, enabled?: boolean, labels?: object, metadata?: object, priority?: number, type?: LocationType };
        } else {
            params = {
                code: paramsOrFirst as string,
                name: rest[0] as string,
                address: rest[1] as object,
                enabled: rest[2] as boolean,
                labels: rest[3] as object,
                metadata: rest[4] as object,
                priority: rest[5] as number,
                type: rest[6] as LocationType            
            };
        }
        
        const code = params.code;
        const name = params.name;
        const address = params.address;
        const enabled = params.enabled;
        const labels = params.labels;
        const metadata = params.metadata;
        const priority = params.priority;
        const type = params.type;

        if (typeof code === 'undefined') {
            throw new RevenexxException('Missing required parameter: "code"');
        }
        if (typeof name === 'undefined') {
            throw new RevenexxException('Missing required parameter: "name"');
        }

        const apiPath = '/v1/inventories/locations';
        const apiPayload: Payload = {};
        if (typeof address !== 'undefined') {
            apiPayload['address'] = address;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof enabled !== 'undefined') {
            apiPayload['enabled'] = enabled;
        }
        if (typeof labels !== 'undefined') {
            apiPayload['labels'] = labels;
        }
        if (typeof metadata !== 'undefined') {
            apiPayload['metadata'] = metadata;
        }
        if (typeof name !== 'undefined') {
            apiPayload['name'] = name;
        }
        if (typeof priority !== 'undefined') {
            apiPayload['priority'] = priority;
        }
        if (typeof type !== 'undefined') {
            apiPayload['type'] = type;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Gives a tenant the two sets it cannot start without. First its first location, `main`, so the stock calls have somewhere to book into: `receive`, `adjust` and `restock` fall back to the `default_location_code` setting when a caller names no `location_code`, and a tenant with no location at all answers 400 on its first receipt. Then the four availability states this app ships with, reported under `availability_states` and kept out of the two lists above because a state is not a location. The platform already runs this on `app.installed`, so calling it by hand is the repair for an install that predates the event or a `main` somebody deleted. Idempotent by CODE, not by contents: a row already carrying that code is reported under `existing` and is NOT touched, so a renamed or disabled `main` stays renamed and disabled and a state whose `orderable` a merchant corrected keeps the correction. It creates nothing else and never removes anything.
     *
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    inventoriesLocationsDefaults(): Promise<{}> {

        const apiPath = '/v1/inventories/locations/defaults';
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Deleting one takes every `stock_levels` row that points at it with it — the foreign key decides that, not this route. What the database does NOT clean up is everything else carrying the same id: `stock_movements.location_id` and `reservations.location_id` are plain uuid columns and not foreign keys, so those rows stay exactly where they are, pointing at a row that no longer exists, and nothing nulls the pointer. That asymmetry destroys the balances and keeps everything that refers to them, so the route REFUSES while anything still depends on the location and answers 409 with the count — taken here rather than left to whoever is about to click delete, because a client that pre-counts asks a second question whose answer disagrees the moment a receipt lands between the two calls. Two things block it. A stock row still carrying `on_hand`: the cascade would destroy recorded inventory and nothing in this app ever replays the ledger to rebuild a balance, so there is no undo. And a reservation still `active`: a promise to a customer must not outlive the row backing it — such a hold used to survive its stock row, after which /release lowered no `reserved` and still wrote its `release` booking, and /commit booked the whole quantity as a shortfall, neither of them an error. A stock row at zero does not block: it records no quantity. HISTORY never blocks, and is never deleted either — a movement is an accounting record and removing one would falsify it, so the bookings stay, naming a location that no longer resolves, BY DESIGN. A location that once had traffic and now holds nothing is exactly what a merchant closes. To get past the 409, adjust the stock to zero and release or commit the holds; where the location is merely out of service, PUT `enabled: false` keeps every row and can be undone.
     *
     * @param {string} params.id - The location.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    inventoriesLocationsDelete(params: { id: string }): Promise<{}>;
    /**
     * Deleting one takes every `stock_levels` row that points at it with it — the foreign key decides that, not this route. What the database does NOT clean up is everything else carrying the same id: `stock_movements.location_id` and `reservations.location_id` are plain uuid columns and not foreign keys, so those rows stay exactly where they are, pointing at a row that no longer exists, and nothing nulls the pointer. That asymmetry destroys the balances and keeps everything that refers to them, so the route REFUSES while anything still depends on the location and answers 409 with the count — taken here rather than left to whoever is about to click delete, because a client that pre-counts asks a second question whose answer disagrees the moment a receipt lands between the two calls. Two things block it. A stock row still carrying `on_hand`: the cascade would destroy recorded inventory and nothing in this app ever replays the ledger to rebuild a balance, so there is no undo. And a reservation still `active`: a promise to a customer must not outlive the row backing it — such a hold used to survive its stock row, after which /release lowered no `reserved` and still wrote its `release` booking, and /commit booked the whole quantity as a shortfall, neither of them an error. A stock row at zero does not block: it records no quantity. HISTORY never blocks, and is never deleted either — a movement is an accounting record and removing one would falsify it, so the bookings stay, naming a location that no longer resolves, BY DESIGN. A location that once had traffic and now holds nothing is exactly what a merchant closes. To get past the 409, adjust the stock to zero and release or commit the holds; where the location is merely out of service, PUT `enabled: false` keeps every row and can be undone.
     *
     * @param {string} id - The location.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    inventoriesLocationsDelete(id: string): Promise<{}>;
    inventoriesLocationsDelete(
        paramsOrFirst: { id: string } | string    
    ): Promise<{}> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/inventories/locations/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'delete',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A location is WHERE stock is kept — a warehouse, a shop floor, a supplier that dropships, or a virtual bucket for pre-orders and quarantine. It holds no quantity of its own: what is at it is a stock level. `type` is descriptive and nothing branches on it; `priority` is the number that decides which location a reservation is served from, and `enabled` decides whether it is offered at all. This is the route that turns an id back into a place: `location_id` is on every stock row, every ledger booking and every reservation, and none of them carries the code or the name. Reading it also answers the two questions those rows raise — whether the location is still `enabled` (a disabled one is skipped by availability and reserve while its stock stays exactly where it is) and where its `priority` puts it when the allocation strategy picks somewhere to reserve from.
     *
     * @param {string} params.id - The location.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Location>}
     */
    inventoriesLocationsGet(params: { id: string }): Promise<Models.Location>;
    /**
     * A location is WHERE stock is kept — a warehouse, a shop floor, a supplier that dropships, or a virtual bucket for pre-orders and quarantine. It holds no quantity of its own: what is at it is a stock level. `type` is descriptive and nothing branches on it; `priority` is the number that decides which location a reservation is served from, and `enabled` decides whether it is offered at all. This is the route that turns an id back into a place: `location_id` is on every stock row, every ledger booking and every reservation, and none of them carries the code or the name. Reading it also answers the two questions those rows raise — whether the location is still `enabled` (a disabled one is skipped by availability and reserve while its stock stays exactly where it is) and where its `priority` puts it when the allocation strategy picks somewhere to reserve from.
     *
     * @param {string} id - The location.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Location>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    inventoriesLocationsGet(id: string): Promise<Models.Location>;
    inventoriesLocationsGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.Location> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/inventories/locations/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Partial update: send the fields that change. The one with consequences is `enabled` — setting it to false is how a location is taken out of service WITHOUT losing anything. Availability and reserve stop looking at it, so its stock stops being sellable, while every stock row, ledger booking and reservation that points at it survives untouched and comes back the moment it is enabled again. That is the reversible alternative to DELETE, which is not reversible at all. Changing `code` is the other sharp edge: rows keep their `location_id` so nothing moves, but every caller that names the old code in `location_code` starts getting 400 "unknown location". Two rows of this tenant may not share `code` and `external_id` — that is the 409, and it answers an update that moves a row onto a sibling's value exactly as it answers a second insert.
     *
     * @param {string} params.id - The location.
     * @param {object} params.address - Where the location physically is. Free-form, and one key is READ: `country`, an ISO country code, which POST /inventories/reserve compares (case-insensitively) against `ship_to.country` when `allocation_strategy` is 'nearest' — that is what stops a German order pulling from the US warehouse because it happens to sort first. The keys the cockpit form writes are `street`, `postal_code`, `city`, `country`; anything else a tenant stores is kept and ignored.
     * @param {string} params.code - The location's stable identifier, and the name every stock call uses instead of an id: `location_code` on receive / adjust / restock / reserve, and the `default_location_code` setting. Unique per tenant, at least one character (CHECK `length(code) > 0`). Every tenant starts with `main` — POST /inventories/locations/defaults seeds it and the app.installed event runs the same seed — so `main` is the one code that resolves everywhere.
     * @param {boolean} params.enabled - Whether this location takes part in stock at all. POST /inventories/availability and POST /inventories/reserve look at enabled locations and nothing else, so switching this off hides a location's stock from the storefront without deleting a row or losing a single ledger booking; its stock stays readable through GET /inventories/stock. Defaults to true.
     * @param {object} params.labels - The location name per language tag, for a UI that has to render it in the reader's language. Falls back to `name` when a tag is missing. Keys are language tags, values plain strings.
     * @param {object} params.metadata - Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. No route in this app reads it; it is stored and handed back unchanged.
     * @param {string} params.name - What the place is called for an operator, in the tenant's working language. At least one character (CHECK `length(name) > 0`). It is a label only: nothing addresses a location by name.
     * @param {number} params.priority - Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred. Locations that tie keep the order the database returns them in — give every location a distinct priority if the order matters. Defaults to 0.
     * @param {LocationType} params.type - What kind of place holds the stock. 'warehouse' — own stock, the default. 'store' — a retail floor, the stock a click-and-collect order draws on. 'dropship' — a supplier ships it and this row tracks what they say they hold. 'virtual' — a bucket that is not a building (pre-orders, consignment, a quarantine shelf). Descriptive only: sourcing order comes from `priority`, and no route in this app treats one type differently from another. Defaults to 'warehouse'.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Location>}
     */
    inventoriesLocationsUpdate(params: { id: string, address?: object, code?: string, enabled?: boolean, labels?: object, metadata?: object, name?: string, priority?: number, type?: LocationType }): Promise<Models.Location>;
    /**
     * Partial update: send the fields that change. The one with consequences is `enabled` — setting it to false is how a location is taken out of service WITHOUT losing anything. Availability and reserve stop looking at it, so its stock stops being sellable, while every stock row, ledger booking and reservation that points at it survives untouched and comes back the moment it is enabled again. That is the reversible alternative to DELETE, which is not reversible at all. Changing `code` is the other sharp edge: rows keep their `location_id` so nothing moves, but every caller that names the old code in `location_code` starts getting 400 "unknown location". Two rows of this tenant may not share `code` and `external_id` — that is the 409, and it answers an update that moves a row onto a sibling's value exactly as it answers a second insert.
     *
     * @param {string} id - The location.
     * @param {object} address - Where the location physically is. Free-form, and one key is READ: `country`, an ISO country code, which POST /inventories/reserve compares (case-insensitively) against `ship_to.country` when `allocation_strategy` is 'nearest' — that is what stops a German order pulling from the US warehouse because it happens to sort first. The keys the cockpit form writes are `street`, `postal_code`, `city`, `country`; anything else a tenant stores is kept and ignored.
     * @param {string} code - The location's stable identifier, and the name every stock call uses instead of an id: `location_code` on receive / adjust / restock / reserve, and the `default_location_code` setting. Unique per tenant, at least one character (CHECK `length(code) > 0`). Every tenant starts with `main` — POST /inventories/locations/defaults seeds it and the app.installed event runs the same seed — so `main` is the one code that resolves everywhere.
     * @param {boolean} enabled - Whether this location takes part in stock at all. POST /inventories/availability and POST /inventories/reserve look at enabled locations and nothing else, so switching this off hides a location's stock from the storefront without deleting a row or losing a single ledger booking; its stock stays readable through GET /inventories/stock. Defaults to true.
     * @param {object} labels - The location name per language tag, for a UI that has to render it in the reader's language. Falls back to `name` when a tag is missing. Keys are language tags, values plain strings.
     * @param {object} metadata - Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. No route in this app reads it; it is stored and handed back unchanged.
     * @param {string} name - What the place is called for an operator, in the tenant's working language. At least one character (CHECK `length(name) > 0`). It is a label only: nothing addresses a location by name.
     * @param {number} priority - Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred. Locations that tie keep the order the database returns them in — give every location a distinct priority if the order matters. Defaults to 0.
     * @param {LocationType} type - What kind of place holds the stock. 'warehouse' — own stock, the default. 'store' — a retail floor, the stock a click-and-collect order draws on. 'dropship' — a supplier ships it and this row tracks what they say they hold. 'virtual' — a bucket that is not a building (pre-orders, consignment, a quarantine shelf). Descriptive only: sourcing order comes from `priority`, and no route in this app treats one type differently from another. Defaults to 'warehouse'.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Location>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    inventoriesLocationsUpdate(id: string, address?: object, code?: string, enabled?: boolean, labels?: object, metadata?: object, name?: string, priority?: number, type?: LocationType): Promise<Models.Location>;
    inventoriesLocationsUpdate(
        paramsOrFirst: { id: string, address?: object, code?: string, enabled?: boolean, labels?: object, metadata?: object, name?: string, priority?: number, type?: LocationType } | string,
        ...rest: [(object)?, (string)?, (boolean)?, (object)?, (object)?, (string)?, (number)?, (LocationType)?]    
    ): Promise<Models.Location> {
        let params: { id: string, address?: object, code?: string, enabled?: boolean, labels?: object, metadata?: object, name?: string, priority?: number, type?: LocationType };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string, address?: object, code?: string, enabled?: boolean, labels?: object, metadata?: object, name?: string, priority?: number, type?: LocationType };
        } else {
            params = {
                id: paramsOrFirst as string,
                address: rest[0] as object,
                code: rest[1] as string,
                enabled: rest[2] as boolean,
                labels: rest[3] as object,
                metadata: rest[4] as object,
                name: rest[5] as string,
                priority: rest[6] as number,
                type: rest[7] as LocationType            
            };
        }
        
        const id = params.id;
        const address = params.address;
        const code = params.code;
        const enabled = params.enabled;
        const labels = params.labels;
        const metadata = params.metadata;
        const name = params.name;
        const priority = params.priority;
        const type = params.type;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/inventories/locations/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        if (typeof address !== 'undefined') {
            apiPayload['address'] = address;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof enabled !== 'undefined') {
            apiPayload['enabled'] = enabled;
        }
        if (typeof labels !== 'undefined') {
            apiPayload['labels'] = labels;
        }
        if (typeof metadata !== 'undefined') {
            apiPayload['metadata'] = metadata;
        }
        if (typeof name !== 'undefined') {
            apiPayload['name'] = name;
        }
        if (typeof priority !== 'undefined') {
            apiPayload['priority'] = priority;
        }
        if (typeof type !== 'undefined') {
            apiPayload['type'] = type;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'put',
            uri,
            apiHeaders,
            apiPayload
        );
    }
}
