import { Service } from '../service';
import { RevenexxException, Client, type Payload, UploadProgress } from '../client';
import type { Models } from '../models';

import { DocumentsDocumentsListSource } from '../enums/documents-documents-list-source';
import { AssetsSource } from '../enums/assets-source';

export class ProductsAssets {
    client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
     * 
     * Every column of `assets` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.
     * 
     * Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.
     *
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} params.offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} params.order - Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
     * @param {string} params.id - Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
     * @param {string} params.assetFamilyId - Exact match on `asset_family_id`. The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
     * @param {string} params.code - Exact match on `code`. The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
     * @param {DocumentsDocumentsListSource} params.source - Exact match on `source`. Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
     * @param {string} params.storageAssetId - Exact match on `storage_asset_id`. The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
     * @param {string} params.deliveryPath - Exact match on `delivery_path`. The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
     * @param {string} params.externalUrl - Exact match on `external_url`. Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
     * @param {string} params.attributeValues - Exact match on `attribute_values`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
     * @param {string} params.externalId - Exact match on `external_id`. The key this asset has in the DAM that owns it, and what a media import upserts on. Neither of the other two ids can serve: `code` is unique only within its asset family, and `storage_asset_id` names the BYTES in this platform's store rather than the record in somebody else's system. Unique per tenant where set.
     * @param {string} params.externalRefs - Exact match on `external_refs`. Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
     * @param {string} params.sourceSyncedAt - Exact match on `source_synced_at`. When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.
     * @param {string} params.sourceData - Exact match on `source_data`. What the source said about this row, kept as it said it: `{"system": …, "etag": …, "raw": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
     * @param {string} params.createdAt - Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
     * @param {string} params.updatedAt - Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    productsAssetsList(params?: { limit?: number, offset?: number, order?: string, id?: string, assetFamilyId?: string, code?: string, source?: DocumentsDocumentsListSource, storageAssetId?: string, deliveryPath?: string, externalUrl?: string, attributeValues?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string }): Promise<{}>;
    /**
     * One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
     * 
     * Every column of `assets` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.
     * 
     * Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.
     *
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} order - Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
     * @param {string} id - Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
     * @param {string} assetFamilyId - Exact match on `asset_family_id`. The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
     * @param {string} code - Exact match on `code`. The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
     * @param {DocumentsDocumentsListSource} source - Exact match on `source`. Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
     * @param {string} storageAssetId - Exact match on `storage_asset_id`. The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
     * @param {string} deliveryPath - Exact match on `delivery_path`. The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
     * @param {string} externalUrl - Exact match on `external_url`. Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
     * @param {string} attributeValues - Exact match on `attribute_values`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
     * @param {string} externalId - Exact match on `external_id`. The key this asset has in the DAM that owns it, and what a media import upserts on. Neither of the other two ids can serve: `code` is unique only within its asset family, and `storage_asset_id` names the BYTES in this platform's store rather than the record in somebody else's system. Unique per tenant where set.
     * @param {string} externalRefs - Exact match on `external_refs`. Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
     * @param {string} sourceSyncedAt - Exact match on `source_synced_at`. When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.
     * @param {string} sourceData - Exact match on `source_data`. What the source said about this row, kept as it said it: `{"system": …, "etag": …, "raw": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
     * @param {string} createdAt - Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
     * @param {string} updatedAt - Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    productsAssetsList(limit?: number, offset?: number, order?: string, id?: string, assetFamilyId?: string, code?: string, source?: DocumentsDocumentsListSource, storageAssetId?: string, deliveryPath?: string, externalUrl?: string, attributeValues?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string): Promise<{}>;
    productsAssetsList(
        paramsOrFirst?: { limit?: number, offset?: number, order?: string, id?: string, assetFamilyId?: string, code?: string, source?: DocumentsDocumentsListSource, storageAssetId?: string, deliveryPath?: string, externalUrl?: string, attributeValues?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string } | number,
        ...rest: [(number)?, (string)?, (string)?, (string)?, (string)?, (DocumentsDocumentsListSource)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?]    
    ): Promise<{}> {
        let params: { limit?: number, offset?: number, order?: string, id?: string, assetFamilyId?: string, code?: string, source?: DocumentsDocumentsListSource, storageAssetId?: string, deliveryPath?: string, externalUrl?: string, attributeValues?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { limit?: number, offset?: number, order?: string, id?: string, assetFamilyId?: string, code?: string, source?: DocumentsDocumentsListSource, storageAssetId?: string, deliveryPath?: string, externalUrl?: string, attributeValues?: string, externalId?: string, externalRefs?: string, sourceSyncedAt?: string, sourceData?: string, createdAt?: string, updatedAt?: string };
        } else {
            params = {
                limit: paramsOrFirst as number,
                offset: rest[0] as number,
                order: rest[1] as string,
                id: rest[2] as string,
                assetFamilyId: rest[3] as string,
                code: rest[4] as string,
                source: rest[5] as DocumentsDocumentsListSource,
                storageAssetId: rest[6] as string,
                deliveryPath: rest[7] as string,
                externalUrl: rest[8] as string,
                attributeValues: rest[9] as string,
                externalId: rest[10] as string,
                externalRefs: rest[11] as string,
                sourceSyncedAt: rest[12] as string,
                sourceData: rest[13] as string,
                createdAt: rest[14] as string,
                updatedAt: rest[15] as string            
            };
        }
        
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;
        const id = params.id;
        const assetFamilyId = params.assetFamilyId;
        const code = params.code;
        const source = params.source;
        const storageAssetId = params.storageAssetId;
        const deliveryPath = params.deliveryPath;
        const externalUrl = params.externalUrl;
        const attributeValues = params.attributeValues;
        const externalId = params.externalId;
        const externalRefs = params.externalRefs;
        const sourceSyncedAt = params.sourceSyncedAt;
        const sourceData = params.sourceData;
        const createdAt = params.createdAt;
        const updatedAt = params.updatedAt;


        const apiPath = '/v1/products/assets';
        const apiPayload: Payload = {};
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof assetFamilyId !== 'undefined') {
            apiPayload['asset_family_id'] = assetFamilyId;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof source !== 'undefined') {
            apiPayload['source'] = source;
        }
        if (typeof storageAssetId !== 'undefined') {
            apiPayload['storage_asset_id'] = storageAssetId;
        }
        if (typeof deliveryPath !== 'undefined') {
            apiPayload['delivery_path'] = deliveryPath;
        }
        if (typeof externalUrl !== 'undefined') {
            apiPayload['external_url'] = externalUrl;
        }
        if (typeof attributeValues !== 'undefined') {
            apiPayload['attribute_values'] = attributeValues;
        }
        if (typeof externalId !== 'undefined') {
            apiPayload['external_id'] = externalId;
        }
        if (typeof externalRefs !== 'undefined') {
            apiPayload['external_refs'] = externalRefs;
        }
        if (typeof sourceSyncedAt !== 'undefined') {
            apiPayload['source_synced_at'] = sourceSyncedAt;
        }
        if (typeof sourceData !== 'undefined') {
            apiPayload['source_data'] = sourceData;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof updatedAt !== 'undefined') {
            apiPayload['updated_at'] = updatedAt;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Creates one asset and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
     * 
     * One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
     * 
     * `asset_family_id` and `code` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same `asset_family_id` and `code` answers 409. This app owns the create, because it is the only place an external URL can enter the catalog: an asset with no family falls back to the `default_asset_family` setting, and an `external` one is refused unless the tenant allows external media and the URL's host is on its allow-list.
     *
     * @param {string} params.assetFamilyId - The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
     * @param {string} params.code - The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
     * @param {object} params.attributeValues - Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.

Four buckets, and an attribute's own flags decide which one it writes to:

  `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                              `{"common": {"net_weight": 2.4, "colour": "black"}}`
  `locale_specific`           `localizable`: one value per language tag.
                              `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
  `channel_specific`          `scopable`: one value per channel.
                              `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
  `channel_locale_specific`   both: one value per channel AND language tag.
                              `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`

A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.

The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.

Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.

Which attributes an asset of this family has comes from `attributes` rows with `entity_type: "asset"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.
     * @param {string} params.deliveryPath - The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
     * @param {string} params.externalId - The key this asset has in the DAM that owns it, and what a media import upserts on. Neither of the other two ids can serve: `code` is unique only within its asset family, and `storage_asset_id` names the BYTES in this platform's store rather than the record in somebody else's system. Unique per tenant where set.
     * @param {object} params.externalRefs - Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer.
     * @param {string} params.externalUrl - Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
     * @param {AssetsSource} params.source - Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
     * @param {object} params.sourceData - What the source said about this row, kept as it said it: `{"system": …, "etag": …, "raw": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.
     * @param {string} params.sourceSyncedAt - When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.
     * @param {string} params.storageAssetId - The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assets>}
     */
    productsAssetsCreate(params: { assetFamilyId: string, code: string, attributeValues?: object, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string }): Promise<Models.Assets>;
    /**
     * Creates one asset and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
     * 
     * One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
     * 
     * `asset_family_id` and `code` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same `asset_family_id` and `code` answers 409. This app owns the create, because it is the only place an external URL can enter the catalog: an asset with no family falls back to the `default_asset_family` setting, and an `external` one is refused unless the tenant allows external media and the URL's host is on its allow-list.
     *
     * @param {string} assetFamilyId - The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
     * @param {string} code - The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
     * @param {object} attributeValues - Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.

Four buckets, and an attribute's own flags decide which one it writes to:

  `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                              `{"common": {"net_weight": 2.4, "colour": "black"}}`
  `locale_specific`           `localizable`: one value per language tag.
                              `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
  `channel_specific`          `scopable`: one value per channel.
                              `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
  `channel_locale_specific`   both: one value per channel AND language tag.
                              `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`

A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.

The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.

Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.

Which attributes an asset of this family has comes from `attributes` rows with `entity_type: "asset"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.
     * @param {string} deliveryPath - The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
     * @param {string} externalId - The key this asset has in the DAM that owns it, and what a media import upserts on. Neither of the other two ids can serve: `code` is unique only within its asset family, and `storage_asset_id` names the BYTES in this platform's store rather than the record in somebody else's system. Unique per tenant where set.
     * @param {object} externalRefs - Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer.
     * @param {string} externalUrl - Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
     * @param {AssetsSource} source - Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
     * @param {object} sourceData - What the source said about this row, kept as it said it: `{"system": …, "etag": …, "raw": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.
     * @param {string} sourceSyncedAt - When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.
     * @param {string} storageAssetId - The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assets>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    productsAssetsCreate(assetFamilyId: string, code: string, attributeValues?: object, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string): Promise<Models.Assets>;
    productsAssetsCreate(
        paramsOrFirst: { assetFamilyId: string, code: string, attributeValues?: object, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string } | string,
        ...rest: [(string)?, (object)?, (string)?, (string)?, (object)?, (string)?, (AssetsSource)?, (object)?, (string)?, (string)?]    
    ): Promise<Models.Assets> {
        let params: { assetFamilyId: string, code: string, attributeValues?: object, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { assetFamilyId: string, code: string, attributeValues?: object, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string };
        } else {
            params = {
                assetFamilyId: paramsOrFirst as string,
                code: rest[0] as string,
                attributeValues: rest[1] as object,
                deliveryPath: rest[2] as string,
                externalId: rest[3] as string,
                externalRefs: rest[4] as object,
                externalUrl: rest[5] as string,
                source: rest[6] as AssetsSource,
                sourceData: rest[7] as object,
                sourceSyncedAt: rest[8] as string,
                storageAssetId: rest[9] as string            
            };
        }
        
        const assetFamilyId = params.assetFamilyId;
        const code = params.code;
        const attributeValues = params.attributeValues;
        const deliveryPath = params.deliveryPath;
        const externalId = params.externalId;
        const externalRefs = params.externalRefs;
        const externalUrl = params.externalUrl;
        const source = params.source;
        const sourceData = params.sourceData;
        const sourceSyncedAt = params.sourceSyncedAt;
        const storageAssetId = params.storageAssetId;

        if (typeof assetFamilyId === 'undefined') {
            throw new RevenexxException('Missing required parameter: "assetFamilyId"');
        }
        if (typeof code === 'undefined') {
            throw new RevenexxException('Missing required parameter: "code"');
        }

        const apiPath = '/v1/products/assets';
        const apiPayload: Payload = {};
        if (typeof assetFamilyId !== 'undefined') {
            apiPayload['asset_family_id'] = assetFamilyId;
        }
        if (typeof attributeValues !== 'undefined') {
            apiPayload['attribute_values'] = attributeValues;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof deliveryPath !== 'undefined') {
            apiPayload['delivery_path'] = deliveryPath;
        }
        if (typeof externalId !== 'undefined') {
            apiPayload['external_id'] = externalId;
        }
        if (typeof externalRefs !== 'undefined') {
            apiPayload['external_refs'] = externalRefs;
        }
        if (typeof externalUrl !== 'undefined') {
            apiPayload['external_url'] = externalUrl;
        }
        if (typeof source !== 'undefined') {
            apiPayload['source'] = source;
        }
        if (typeof sourceData !== 'undefined') {
            apiPayload['source_data'] = sourceData;
        }
        if (typeof sourceSyncedAt !== 'undefined') {
            apiPayload['source_synced_at'] = sourceSyncedAt;
        }
        if (typeof storageAssetId !== 'undefined') {
            apiPayload['storage_asset_id'] = storageAssetId;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Deletes one asset by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
     * 
     * Nothing in this schema references it, so nothing else changes.
     * 
     * An id no asset of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.
     *
     * @param {string} params.id - The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    productsAssetsDelete(params: { id: string }): Promise<{}>;
    /**
     * Deletes one asset by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
     * 
     * Nothing in this schema references it, so nothing else changes.
     * 
     * An id no asset of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.
     *
     * @param {string} id - The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    productsAssetsDelete(id: string): Promise<{}>;
    productsAssetsDelete(
        paramsOrFirst: { id: string } | string    
    ): Promise<{}> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/products/assets/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'delete',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Reads one asset by its id — the whole row, every column, as it is stored.
     * 
     * One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
     * 
     * An id no asset of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.
     * 
     * Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.
     *
     * @param {string} params.id - The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assets>}
     */
    productsAssetsGet(params: { id: string }): Promise<Models.Assets>;
    /**
     * Reads one asset by its id — the whole row, every column, as it is stored.
     * 
     * One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
     * 
     * An id no asset of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.
     * 
     * Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.
     *
     * @param {string} id - The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assets>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    productsAssetsGet(id: string): Promise<Models.Assets>;
    productsAssetsGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.Assets> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/products/assets/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Updates one asset by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
     * 
     * One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
     * 
     * A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `asset_family_id` and `code` answers 409.
     *
     * @param {string} params.id - The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
     * @param {string} params.assetFamilyId - The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
     * @param {object} params.attributeValues - Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.

Four buckets, and an attribute's own flags decide which one it writes to:

  `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                              `{"common": {"net_weight": 2.4, "colour": "black"}}`
  `locale_specific`           `localizable`: one value per language tag.
                              `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
  `channel_specific`          `scopable`: one value per channel.
                              `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
  `channel_locale_specific`   both: one value per channel AND language tag.
                              `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`

A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.

The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.

Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.

Which attributes an asset of this family has comes from `attributes` rows with `entity_type: "asset"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.
     * @param {string} params.code - The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
     * @param {string} params.deliveryPath - The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
     * @param {string} params.externalId - The key this asset has in the DAM that owns it, and what a media import upserts on. Neither of the other two ids can serve: `code` is unique only within its asset family, and `storage_asset_id` names the BYTES in this platform's store rather than the record in somebody else's system. Unique per tenant where set.
     * @param {object} params.externalRefs - Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer.
     * @param {string} params.externalUrl - Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
     * @param {AssetsSource} params.source - Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
     * @param {object} params.sourceData - What the source said about this row, kept as it said it: `{"system": …, "etag": …, "raw": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.
     * @param {string} params.sourceSyncedAt - When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.
     * @param {string} params.storageAssetId - The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assets>}
     */
    productsAssetsUpdate(params: { id: string, assetFamilyId?: string, attributeValues?: object, code?: string, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string }): Promise<Models.Assets>;
    /**
     * Updates one asset by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
     * 
     * One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
     * 
     * A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `asset_family_id` and `code` answers 409.
     *
     * @param {string} id - The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
     * @param {string} assetFamilyId - The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
     * @param {object} attributeValues - Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.

Four buckets, and an attribute's own flags decide which one it writes to:

  `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                              `{"common": {"net_weight": 2.4, "colour": "black"}}`
  `locale_specific`           `localizable`: one value per language tag.
                              `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
  `channel_specific`          `scopable`: one value per channel.
                              `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
  `channel_locale_specific`   both: one value per channel AND language tag.
                              `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`

A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.

The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.

Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.

Which attributes an asset of this family has comes from `attributes` rows with `entity_type: "asset"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.
     * @param {string} code - The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
     * @param {string} deliveryPath - The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
     * @param {string} externalId - The key this asset has in the DAM that owns it, and what a media import upserts on. Neither of the other two ids can serve: `code` is unique only within its asset family, and `storage_asset_id` names the BYTES in this platform's store rather than the record in somebody else's system. Unique per tenant where set.
     * @param {object} externalRefs - Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer.
     * @param {string} externalUrl - Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
     * @param {AssetsSource} source - Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
     * @param {object} sourceData - What the source said about this row, kept as it said it: `{"system": …, "etag": …, "raw": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.
     * @param {string} sourceSyncedAt - When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.
     * @param {string} storageAssetId - The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assets>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    productsAssetsUpdate(id: string, assetFamilyId?: string, attributeValues?: object, code?: string, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string): Promise<Models.Assets>;
    productsAssetsUpdate(
        paramsOrFirst: { id: string, assetFamilyId?: string, attributeValues?: object, code?: string, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string } | string,
        ...rest: [(string)?, (object)?, (string)?, (string)?, (string)?, (object)?, (string)?, (AssetsSource)?, (object)?, (string)?, (string)?]    
    ): Promise<Models.Assets> {
        let params: { id: string, assetFamilyId?: string, attributeValues?: object, code?: string, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string, assetFamilyId?: string, attributeValues?: object, code?: string, deliveryPath?: string, externalId?: string, externalRefs?: object, externalUrl?: string, source?: AssetsSource, sourceData?: object, sourceSyncedAt?: string, storageAssetId?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                assetFamilyId: rest[0] as string,
                attributeValues: rest[1] as object,
                code: rest[2] as string,
                deliveryPath: rest[3] as string,
                externalId: rest[4] as string,
                externalRefs: rest[5] as object,
                externalUrl: rest[6] as string,
                source: rest[7] as AssetsSource,
                sourceData: rest[8] as object,
                sourceSyncedAt: rest[9] as string,
                storageAssetId: rest[10] as string            
            };
        }
        
        const id = params.id;
        const assetFamilyId = params.assetFamilyId;
        const attributeValues = params.attributeValues;
        const code = params.code;
        const deliveryPath = params.deliveryPath;
        const externalId = params.externalId;
        const externalRefs = params.externalRefs;
        const externalUrl = params.externalUrl;
        const source = params.source;
        const sourceData = params.sourceData;
        const sourceSyncedAt = params.sourceSyncedAt;
        const storageAssetId = params.storageAssetId;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/products/assets/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        if (typeof assetFamilyId !== 'undefined') {
            apiPayload['asset_family_id'] = assetFamilyId;
        }
        if (typeof attributeValues !== 'undefined') {
            apiPayload['attribute_values'] = attributeValues;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof deliveryPath !== 'undefined') {
            apiPayload['delivery_path'] = deliveryPath;
        }
        if (typeof externalId !== 'undefined') {
            apiPayload['external_id'] = externalId;
        }
        if (typeof externalRefs !== 'undefined') {
            apiPayload['external_refs'] = externalRefs;
        }
        if (typeof externalUrl !== 'undefined') {
            apiPayload['external_url'] = externalUrl;
        }
        if (typeof source !== 'undefined') {
            apiPayload['source'] = source;
        }
        if (typeof sourceData !== 'undefined') {
            apiPayload['source_data'] = sourceData;
        }
        if (typeof sourceSyncedAt !== 'undefined') {
            apiPayload['source_synced_at'] = sourceSyncedAt;
        }
        if (typeof storageAssetId !== 'undefined') {
            apiPayload['storage_asset_id'] = storageAssetId;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'put',
            uri,
            apiHeaders,
            apiPayload
        );
    }
}
