import { Service } from '../service';
import { RevenexxException, Client, type Payload, UploadProgress } from '../client';
import type { Models } from '../models';

import { PagesSeedMode } from '../enums/pages-seed-mode';

export class QuotesRanges {
    client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * The counters quote numbers are drawn from. A market points at one by its `code`; the app seeds `quote` with the prefix `ANG-`.
     *
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} params.offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} params.order - Sort by one column: 'column' | 'column.asc' | 'column.desc'. The column has to be one this entity has.
     * @throws {RevenexxException}
     * @returns {Promise<Models.NumberRangeList>}
     */
    quotesRangesList(params?: { limit?: number, offset?: number, order?: string }): Promise<Models.NumberRangeList>;
    /**
     * The counters quote numbers are drawn from. A market points at one by its `code`; the app seeds `quote` with the prefix `ANG-`.
     *
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} order - Sort by one column: 'column' | 'column.asc' | 'column.desc'. The column has to be one this entity has.
     * @throws {RevenexxException}
     * @returns {Promise<Models.NumberRangeList>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    quotesRangesList(limit?: number, offset?: number, order?: string): Promise<Models.NumberRangeList>;
    quotesRangesList(
        paramsOrFirst?: { limit?: number, offset?: number, order?: string } | number,
        ...rest: [(number)?, (string)?]    
    ): Promise<Models.NumberRangeList> {
        let params: { limit?: number, offset?: number, order?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { limit?: number, offset?: number, order?: string };
        } else {
            params = {
                limit: paramsOrFirst as number,
                offset: rest[0] as number,
                order: rest[1] as string            
            };
        }
        
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;


        const apiPath = '/v1/quotes/number-ranges';
        const apiPayload: Payload = {};
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Adds a counter, so one market can number its quotes differently from another. The code is unique per tenant.
     *
     * @param {string} params.code - What a market points at to draw from this range. Unique per tenant; `quote` is the one this app seeds.
     * @param {number} params.counter - The last number drawn. The next draw adds `step` and stores the result, so a number is never handed out twice.
     * @param {string} params.createdAt - When the row was written, stamped by the database.
     * @param {string} params.id - The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {number} params.padding - How many digits the counter is padded to. 6 gives `000001`.
     * @param {number} params.positionStep - How far apart position numbers sit on a new quote — 10 leaves room to insert a line later without renumbering.
     * @param {string} params.prefix - Put in front of the counter — `ANG-` produces `ANG-000001`.
     * @param {number} params.step - How far the counter moves per draw. 1 is consecutive; a larger step leaves gaps on purpose.
     * @param {string} params.suffix - Put after the counter. Empty on the standard range.
     * @param {string} params.tenantId - The tenant this row belongs to. Set by the data plane from the request identity and never accepted from a caller.
     * @param {string} params.updatedAt - When the row last changed, stamped by the app on every write.
     * @throws {RevenexxException}
     * @returns {Promise<Models.NumberRange>}
     */
    quotesRangesCreate(params: { code: string, counter?: number, createdAt?: string, id?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string }): Promise<Models.NumberRange>;
    /**
     * Adds a counter, so one market can number its quotes differently from another. The code is unique per tenant.
     *
     * @param {string} code - What a market points at to draw from this range. Unique per tenant; `quote` is the one this app seeds.
     * @param {number} counter - The last number drawn. The next draw adds `step` and stores the result, so a number is never handed out twice.
     * @param {string} createdAt - When the row was written, stamped by the database.
     * @param {string} id - The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {number} padding - How many digits the counter is padded to. 6 gives `000001`.
     * @param {number} positionStep - How far apart position numbers sit on a new quote — 10 leaves room to insert a line later without renumbering.
     * @param {string} prefix - Put in front of the counter — `ANG-` produces `ANG-000001`.
     * @param {number} step - How far the counter moves per draw. 1 is consecutive; a larger step leaves gaps on purpose.
     * @param {string} suffix - Put after the counter. Empty on the standard range.
     * @param {string} tenantId - The tenant this row belongs to. Set by the data plane from the request identity and never accepted from a caller.
     * @param {string} updatedAt - When the row last changed, stamped by the app on every write.
     * @throws {RevenexxException}
     * @returns {Promise<Models.NumberRange>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    quotesRangesCreate(code: string, counter?: number, createdAt?: string, id?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string): Promise<Models.NumberRange>;
    quotesRangesCreate(
        paramsOrFirst: { code: string, counter?: number, createdAt?: string, id?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string } | string,
        ...rest: [(number)?, (string)?, (string)?, (number)?, (number)?, (string)?, (number)?, (string)?, (string)?, (string)?]    
    ): Promise<Models.NumberRange> {
        let params: { code: string, counter?: number, createdAt?: string, id?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { code: string, counter?: number, createdAt?: string, id?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string };
        } else {
            params = {
                code: paramsOrFirst as string,
                counter: rest[0] as number,
                createdAt: rest[1] as string,
                id: rest[2] as string,
                padding: rest[3] as number,
                positionStep: rest[4] as number,
                prefix: rest[5] as string,
                step: rest[6] as number,
                suffix: rest[7] as string,
                tenantId: rest[8] as string,
                updatedAt: rest[9] as string            
            };
        }
        
        const code = params.code;
        const counter = params.counter;
        const createdAt = params.createdAt;
        const id = params.id;
        const padding = params.padding;
        const positionStep = params.positionStep;
        const prefix = params.prefix;
        const step = params.step;
        const suffix = params.suffix;
        const tenantId = params.tenantId;
        const updatedAt = params.updatedAt;

        if (typeof code === 'undefined') {
            throw new RevenexxException('Missing required parameter: "code"');
        }

        const apiPath = '/v1/quotes/number-ranges';
        const apiPayload: Payload = {};
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof counter !== 'undefined') {
            apiPayload['counter'] = counter;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof padding !== 'undefined') {
            apiPayload['padding'] = padding;
        }
        if (typeof positionStep !== 'undefined') {
            apiPayload['position_step'] = positionStep;
        }
        if (typeof prefix !== 'undefined') {
            apiPayload['prefix'] = prefix;
        }
        if (typeof step !== 'undefined') {
            apiPayload['step'] = step;
        }
        if (typeof suffix !== 'undefined') {
            apiPayload['suffix'] = suffix;
        }
        if (typeof tenantId !== 'undefined') {
            apiPayload['tenant_id'] = tenantId;
        }
        if (typeof updatedAt !== 'undefined') {
            apiPayload['updated_at'] = updatedAt;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Creates the `quote` range if it is missing. Idempotent, and what an integration calls first — the install event does not reliably fire on a marketplace install.
     *
     * @param {object[]} params.library - The reusable blocks to create. Idempotent by label among live items. One without a label or without a block tree is reported under `skipped`.
     * @param {object[]} params.menus - The menus to create. One with no key or no label is reported under `skipped`.
     * @param {PagesSeedMode} params.mode - `fill` (the default) adds what is missing and keeps everything that exists. `reset` replaces every section that is sent — pages, menus and library items go to the trash first, site settings are removed — and must be asked for by name.
     * @param {object[]} params.pages - The pages to create. One that has no `slug` or no `title` is reported under `skipped` rather than refused, so one bad entry never loses the rest.
     * @param {object} params.settings - Site settings by key — the same values `PUT /pages/settings/site/{key}` stores. In fill only keys the tenant has not set are written; in reset every existing key is removed first. A key that is not a valid setting name, an empty value or one over 128 KiB is reported under `skipped`.
     * @throws {RevenexxException}
     * @returns {Promise<Models.SeedResult>}
     */
    quotesRangesDefaults(params?: { library?: object[], menus?: object[], mode?: PagesSeedMode, pages?: object[], settings?: object }): Promise<Models.SeedResult>;
    /**
     * Creates the `quote` range if it is missing. Idempotent, and what an integration calls first — the install event does not reliably fire on a marketplace install.
     *
     * @param {object[]} library - The reusable blocks to create. Idempotent by label among live items. One without a label or without a block tree is reported under `skipped`.
     * @param {object[]} menus - The menus to create. One with no key or no label is reported under `skipped`.
     * @param {PagesSeedMode} mode - `fill` (the default) adds what is missing and keeps everything that exists. `reset` replaces every section that is sent — pages, menus and library items go to the trash first, site settings are removed — and must be asked for by name.
     * @param {object[]} pages - The pages to create. One that has no `slug` or no `title` is reported under `skipped` rather than refused, so one bad entry never loses the rest.
     * @param {object} settings - Site settings by key — the same values `PUT /pages/settings/site/{key}` stores. In fill only keys the tenant has not set are written; in reset every existing key is removed first. A key that is not a valid setting name, an empty value or one over 128 KiB is reported under `skipped`.
     * @throws {RevenexxException}
     * @returns {Promise<Models.SeedResult>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    quotesRangesDefaults(library?: object[], menus?: object[], mode?: PagesSeedMode, pages?: object[], settings?: object): Promise<Models.SeedResult>;
    quotesRangesDefaults(
        paramsOrFirst?: { library?: object[], menus?: object[], mode?: PagesSeedMode, pages?: object[], settings?: object } | object[],
        ...rest: [(object[])?, (PagesSeedMode)?, (object[])?, (object)?]    
    ): Promise<Models.SeedResult> {
        let params: { library?: object[], menus?: object[], mode?: PagesSeedMode, pages?: object[], settings?: object };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst) && ('library' in paramsOrFirst || 'menus' in paramsOrFirst || 'mode' in paramsOrFirst || 'pages' in paramsOrFirst || 'settings' in paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { library?: object[], menus?: object[], mode?: PagesSeedMode, pages?: object[], settings?: object };
        } else {
            params = {
                library: paramsOrFirst as object[],
                menus: rest[0] as object[],
                mode: rest[1] as PagesSeedMode,
                pages: rest[2] as object[],
                settings: rest[3] as object            
            };
        }
        
        const library = params.library;
        const menus = params.menus;
        const mode = params.mode;
        const pages = params.pages;
        const settings = params.settings;


        const apiPath = '/v1/quotes/number-ranges/defaults';
        const apiPayload: Payload = {};
        if (typeof library !== 'undefined') {
            apiPayload['library'] = Client.toWireKeys(library, {"tree":{"wire":"tree","children":{"fragmentName":{"wire":"fragment_name","children":null},"propsI18n":{"wire":"props_i18n","children":null}}}});
        }
        if (typeof menus !== 'undefined') {
            apiPayload['menus'] = menus;
        }
        if (typeof mode !== 'undefined') {
            apiPayload['mode'] = mode;
        }
        if (typeof pages !== 'undefined') {
            apiPayload['pages'] = Client.toWireKeys(pages, {"blocks":{"wire":"blocks","children":{"fragmentName":{"wire":"fragment_name","children":null},"propsI18n":{"wire":"props_i18n","children":null}}}});
        }
        if (typeof settings !== 'undefined') {
            apiPayload['settings'] = settings;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Removes a counter. The standard one comes back on the next draw rather than breaking quoting.
     *
     * @param {string} params.id - The number range.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Deleted>}
     */
    quotesRangesDelete(params: { id: string }): Promise<Models.Deleted>;
    /**
     * Removes a counter. The standard one comes back on the next draw rather than breaking quoting.
     *
     * @param {string} id - The number range.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Deleted>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    quotesRangesDelete(id: string): Promise<Models.Deleted>;
    quotesRangesDelete(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.Deleted> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/quotes/number-ranges/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'delete',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Reads one counter, including where it currently stands.
     *
     * @param {string} params.id - The number range.
     * @throws {RevenexxException}
     * @returns {Promise<Models.NumberRange>}
     */
    quotesRangesGet(params: { id: string }): Promise<Models.NumberRange>;
    /**
     * Reads one counter, including where it currently stands.
     *
     * @param {string} id - The number range.
     * @throws {RevenexxException}
     * @returns {Promise<Models.NumberRange>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    quotesRangesGet(id: string): Promise<Models.NumberRange>;
    quotesRangesGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.NumberRange> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/quotes/number-ranges/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Changes a counter — its prefix, its padding, or the counter itself. Lowering the counter will hand out numbers that already exist, which the unique index then refuses.
     *
     * @param {string} params.id - The number range.
     * @param {string} params.code - What a market points at to draw from this range. Unique per tenant; `quote` is the one this app seeds.
     * @param {number} params.counter - The last number drawn. The next draw adds `step` and stores the result, so a number is never handed out twice.
     * @param {string} params.createdAt - When the row was written, stamped by the database.
     * @param {string} params.idBody - The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {number} params.padding - How many digits the counter is padded to. 6 gives `000001`.
     * @param {number} params.positionStep - How far apart position numbers sit on a new quote — 10 leaves room to insert a line later without renumbering.
     * @param {string} params.prefix - Put in front of the counter — `ANG-` produces `ANG-000001`.
     * @param {number} params.step - How far the counter moves per draw. 1 is consecutive; a larger step leaves gaps on purpose.
     * @param {string} params.suffix - Put after the counter. Empty on the standard range.
     * @param {string} params.tenantId - The tenant this row belongs to. Set by the data plane from the request identity and never accepted from a caller.
     * @param {string} params.updatedAt - When the row last changed, stamped by the app on every write.
     * @throws {RevenexxException}
     * @returns {Promise<Models.NumberRange>}
     */
    quotesRangesUpdate(params: { id: string, code?: string, counter?: number, createdAt?: string, idBody?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string }): Promise<Models.NumberRange>;
    /**
     * Changes a counter — its prefix, its padding, or the counter itself. Lowering the counter will hand out numbers that already exist, which the unique index then refuses.
     *
     * @param {string} id - The number range.
     * @param {string} code - What a market points at to draw from this range. Unique per tenant; `quote` is the one this app seeds.
     * @param {number} counter - The last number drawn. The next draw adds `step` and stores the result, so a number is never handed out twice.
     * @param {string} createdAt - When the row was written, stamped by the database.
     * @param {string} idBody - The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {number} padding - How many digits the counter is padded to. 6 gives `000001`.
     * @param {number} positionStep - How far apart position numbers sit on a new quote — 10 leaves room to insert a line later without renumbering.
     * @param {string} prefix - Put in front of the counter — `ANG-` produces `ANG-000001`.
     * @param {number} step - How far the counter moves per draw. 1 is consecutive; a larger step leaves gaps on purpose.
     * @param {string} suffix - Put after the counter. Empty on the standard range.
     * @param {string} tenantId - The tenant this row belongs to. Set by the data plane from the request identity and never accepted from a caller.
     * @param {string} updatedAt - When the row last changed, stamped by the app on every write.
     * @throws {RevenexxException}
     * @returns {Promise<Models.NumberRange>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    quotesRangesUpdate(id: string, code?: string, counter?: number, createdAt?: string, idBody?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string): Promise<Models.NumberRange>;
    quotesRangesUpdate(
        paramsOrFirst: { id: string, code?: string, counter?: number, createdAt?: string, idBody?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string } | string,
        ...rest: [(string)?, (number)?, (string)?, (string)?, (number)?, (number)?, (string)?, (number)?, (string)?, (string)?, (string)?]    
    ): Promise<Models.NumberRange> {
        let params: { id: string, code?: string, counter?: number, createdAt?: string, idBody?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string, code?: string, counter?: number, createdAt?: string, idBody?: string, padding?: number, positionStep?: number, prefix?: string, step?: number, suffix?: string, tenantId?: string, updatedAt?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                code: rest[0] as string,
                counter: rest[1] as number,
                createdAt: rest[2] as string,
                idBody: rest[3] as string,
                padding: rest[4] as number,
                positionStep: rest[5] as number,
                prefix: rest[6] as string,
                step: rest[7] as number,
                suffix: rest[8] as string,
                tenantId: rest[9] as string,
                updatedAt: rest[10] as string            
            };
        }
        
        const id = params.id;
        const code = params.code;
        const counter = params.counter;
        const createdAt = params.createdAt;
        const idBody = params.idBody;
        const padding = params.padding;
        const positionStep = params.positionStep;
        const prefix = params.prefix;
        const step = params.step;
        const suffix = params.suffix;
        const tenantId = params.tenantId;
        const updatedAt = params.updatedAt;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/quotes/number-ranges/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof counter !== 'undefined') {
            apiPayload['counter'] = counter;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof idBody !== 'undefined') {
            apiPayload['id'] = idBody;
        }
        if (typeof padding !== 'undefined') {
            apiPayload['padding'] = padding;
        }
        if (typeof positionStep !== 'undefined') {
            apiPayload['position_step'] = positionStep;
        }
        if (typeof prefix !== 'undefined') {
            apiPayload['prefix'] = prefix;
        }
        if (typeof step !== 'undefined') {
            apiPayload['step'] = step;
        }
        if (typeof suffix !== 'undefined') {
            apiPayload['suffix'] = suffix;
        }
        if (typeof tenantId !== 'undefined') {
            apiPayload['tenant_id'] = tenantId;
        }
        if (typeof updatedAt !== 'undefined') {
            apiPayload['updated_at'] = updatedAt;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'put',
            uri,
            apiHeaders,
            apiPayload
        );
    }
}
