import { Service } from '../service';
import { RevenexxException, Client, type Payload, UploadProgress } from '../client';
import type { Models } from '../models';


export class SalesRepsRoster {
    client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. This is the roster: `?code=` resolves the one rep an ERP or a customer record names, `?active=false` is the list of the ones who have left, and `?territory=` groups a patch. Nothing in the answer is narrowed by who is asking — this app resolves no principal of its own, so an operator and a storefront caller read the same rows. That is a stated gap rather than an oversight: the gateway injects its identity with no subject header, and a rep resolved as a principal would arrive at every other app as a buyer.
     *
     * @param {string} params.id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} params.code - Look ONE rep up by the code an ERP knows them by — the read a synchronisation makes before deciding between a create and an edit, and the read a screen makes when a customer record names a salesperson code. Unique per tenant, so this answers at most one rep.
     * @param {string} params.name - Filter by the exact name. It is an equality and not a search: two reps may share a name, and nothing here is unique about it.
     * @param {string} params.email - Filter by address. Deliberately NOT unique — two reps may share a shared mailbox and a rep may have none — so this can answer more than one rep, which is the whole reason the address is not the identity.
     * @param {string} params.phone - Filter to rows whose `phone` is exactly this value. How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.
     * @param {string} params.territory - Filter by the patch a rep covers. An exact match on one label, because a territory here is text and not a tree — there is no "inside" to search.
     * @param {boolean} params.active - Filter to the reps who are working (`true`) or the ones who have left (`false`). This is the selector a screen uses instead of deleting anybody: a deactivated rep keeps their record and their assignments.
     * @param {string} params.platformUserId - Find the rep behind a platform identity — the reverse lookup a sign-in will need. It answers nothing today, because no rep has one yet.
     * @param {string} params.externalId - Look a rep up by the key the system that owns them knows them by. Unique per tenant where it is set, so this answers at most one rep.
     * @param {string} params.sourceSyncedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.
     * @param {string} params.createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {string} params.updatedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} params.offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} params.order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    salesRepsRepsList(params?: { id?: string, code?: string, name?: string, email?: string, phone?: string, territory?: string, active?: boolean, platformUserId?: string, externalId?: string, sourceSyncedAt?: string, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string }): Promise<{}>;
    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. This is the roster: `?code=` resolves the one rep an ERP or a customer record names, `?active=false` is the list of the ones who have left, and `?territory=` groups a patch. Nothing in the answer is narrowed by who is asking — this app resolves no principal of its own, so an operator and a storefront caller read the same rows. That is a stated gap rather than an oversight: the gateway injects its identity with no subject header, and a rep resolved as a principal would arrive at every other app as a buyer.
     *
     * @param {string} id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} code - Look ONE rep up by the code an ERP knows them by — the read a synchronisation makes before deciding between a create and an edit, and the read a screen makes when a customer record names a salesperson code. Unique per tenant, so this answers at most one rep.
     * @param {string} name - Filter by the exact name. It is an equality and not a search: two reps may share a name, and nothing here is unique about it.
     * @param {string} email - Filter by address. Deliberately NOT unique — two reps may share a shared mailbox and a rep may have none — so this can answer more than one rep, which is the whole reason the address is not the identity.
     * @param {string} phone - Filter to rows whose `phone` is exactly this value. How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.
     * @param {string} territory - Filter by the patch a rep covers. An exact match on one label, because a territory here is text and not a tree — there is no "inside" to search.
     * @param {boolean} active - Filter to the reps who are working (`true`) or the ones who have left (`false`). This is the selector a screen uses instead of deleting anybody: a deactivated rep keeps their record and their assignments.
     * @param {string} platformUserId - Find the rep behind a platform identity — the reverse lookup a sign-in will need. It answers nothing today, because no rep has one yet.
     * @param {string} externalId - Look a rep up by the key the system that owns them knows them by. Unique per tenant where it is set, so this answers at most one rep.
     * @param {string} sourceSyncedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.
     * @param {string} createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {string} updatedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsRepsList(id?: string, code?: string, name?: string, email?: string, phone?: string, territory?: string, active?: boolean, platformUserId?: string, externalId?: string, sourceSyncedAt?: string, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string): Promise<{}>;
    salesRepsRepsList(
        paramsOrFirst?: { id?: string, code?: string, name?: string, email?: string, phone?: string, territory?: string, active?: boolean, platformUserId?: string, externalId?: string, sourceSyncedAt?: string, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string } | string,
        ...rest: [(string)?, (string)?, (string)?, (string)?, (string)?, (boolean)?, (string)?, (string)?, (string)?, (string)?, (string)?, (number)?, (number)?, (string)?]    
    ): Promise<{}> {
        let params: { id?: string, code?: string, name?: string, email?: string, phone?: string, territory?: string, active?: boolean, platformUserId?: string, externalId?: string, sourceSyncedAt?: string, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id?: string, code?: string, name?: string, email?: string, phone?: string, territory?: string, active?: boolean, platformUserId?: string, externalId?: string, sourceSyncedAt?: string, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                code: rest[0] as string,
                name: rest[1] as string,
                email: rest[2] as string,
                phone: rest[3] as string,
                territory: rest[4] as string,
                active: rest[5] as boolean,
                platformUserId: rest[6] as string,
                externalId: rest[7] as string,
                sourceSyncedAt: rest[8] as string,
                createdAt: rest[9] as string,
                updatedAt: rest[10] as string,
                limit: rest[11] as number,
                offset: rest[12] as number,
                order: rest[13] as string            
            };
        }
        
        const id = params.id;
        const code = params.code;
        const name = params.name;
        const email = params.email;
        const phone = params.phone;
        const territory = params.territory;
        const active = params.active;
        const platformUserId = params.platformUserId;
        const externalId = params.externalId;
        const sourceSyncedAt = params.sourceSyncedAt;
        const createdAt = params.createdAt;
        const updatedAt = params.updatedAt;
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;


        const apiPath = '/v1/sales-reps/reps';
        const apiPayload: Payload = {};
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof name !== 'undefined') {
            apiPayload['name'] = name;
        }
        if (typeof email !== 'undefined') {
            apiPayload['email'] = email;
        }
        if (typeof phone !== 'undefined') {
            apiPayload['phone'] = phone;
        }
        if (typeof territory !== 'undefined') {
            apiPayload['territory'] = territory;
        }
        if (typeof active !== 'undefined') {
            apiPayload['active'] = active;
        }
        if (typeof platformUserId !== 'undefined') {
            apiPayload['platform_user_id'] = platformUserId;
        }
        if (typeof externalId !== 'undefined') {
            apiPayload['external_id'] = externalId;
        }
        if (typeof sourceSyncedAt !== 'undefined') {
            apiPayload['source_synced_at'] = sourceSyncedAt;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof updatedAt !== 'undefined') {
            apiPayload['updated_at'] = updatedAt;
        }
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. Two fields are owed and no more: `code` and `name`. That is deliberate and it is the whole difference from the package this replaces — an import that knows only a salesperson code and a name records a usable rep, where an app keyed on the email address would have had to invent one. A code this tenant already holds is refused with 409 rather than merged into: the unique index `(tenant_id, code)` is the guard, the pre-flight read only makes the refusal readable, and two simultaneous creates are separated by the index rather than by that read. Nothing is mailed and nobody is told — creating a rep grants no access at all, because this release has no login to grant.
     *
     * @param {string} params.code - The rep's STABLE IDENTITY, and the deliberate difference from the IntelliShop predecessor — where a rep is identified by their email address, so an ERP import loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. This is a short code the ERP already owns (`salespersonCode` on a Business Central customer, `Representative_Code_RAITS` on the customer row), unique per tenant, and FIXED once created: every assignment and every impersonation entry stores it, and neither has a reference this app could follow to rename. Letters, digits, '.', '-' and '_', starting with a letter or a digit — the case is kept rather than folded, because the ERP's codes are upper case and a column that folded them would stop matching the system it points at.
     * @param {string} params.name - What the rep is called, as a person reads it — the one field every list of reps has to show. At least one character. It is the field a merchant renames after a marriage or a typo, which is precisely why it is not the identity.
     * @param {boolean} params.active - Whether this rep is currently working. Deactivating is what 'this person has left' means here, and it is NOT a delete: the record stays, the assignments stay, and the impersonation entries that name the code keep pointing at somebody. That is the whole reason the column exists — the history has to remain answerable. Defaults to true, because a rep is created in order to work. Defaults to true.
     * @param {string} params.email - The rep's address, and NOTHING depends on it being unique or even present. That is the point: it is the column the predecessor used as the primary key, so here it is an ordinary attribute a merchant may leave empty, change, or share between two reps who work one shared mailbox. An import that only knows a code and a name records a usable rep. What a login is bound to is `platform_user_id`, which is a different column for a reason.
     * @param {string} params.externalId - The key this rep has in the system that OWNS them — the ERP's own row id, as distinct from the `code` printed on a customer record. Unique per tenant where it is set. It is the second handle a feed can find a rep by: `code` is the one a human quotes and the one this app's other tables store, and this is the one a synchronisation matches on when even the code has been re-issued.
     * @param {object} params.externalRefs - Every OTHER system that knows this rep, keyed by system name. `external_id` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on `metadata`.
     * @param {object} params.metadata - Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so `?metadata=north` is refused with 400 `invalid_value` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.
     * @param {string} params.phone - How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.
     * @param {string} params.platformUserId - The bridge to a login: the platform identity a rep signs in with, once this app has an auth surface. Null on every rep today, because nothing mints one yet — a rep created now is a RECORD, not an account. It is an id and not a secret: no credential, no password hash and no session token is stored in this app at all, which is why there is nothing here a read has to withhold. Nothing mints one yet; a value sent here is stored and acted on by nothing.
     * @param {object} params.sourceData - What the source said about this rep, kept as it said it. Carries the ETag a write-back has to return in `If-Match`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on `metadata`.
     * @param {string} params.sourceSyncedAt - When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.
     * @param {string} params.territory - The patch this rep covers, as ONE piece of text and not a tree. A hierarchy of territories is deliberately out of scope: the rows that decide what a rep actually sees are the assignments, and a territory here is a label an operator groups a list by. Nothing in this app branches on it.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Rep>}
     */
    salesRepsRepsCreate(params: { code: string, name: string, active?: boolean, email?: string, externalId?: string, externalRefs?: object, metadata?: object, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string }): Promise<Models.Rep>;
    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. Two fields are owed and no more: `code` and `name`. That is deliberate and it is the whole difference from the package this replaces — an import that knows only a salesperson code and a name records a usable rep, where an app keyed on the email address would have had to invent one. A code this tenant already holds is refused with 409 rather than merged into: the unique index `(tenant_id, code)` is the guard, the pre-flight read only makes the refusal readable, and two simultaneous creates are separated by the index rather than by that read. Nothing is mailed and nobody is told — creating a rep grants no access at all, because this release has no login to grant.
     *
     * @param {string} code - The rep's STABLE IDENTITY, and the deliberate difference from the IntelliShop predecessor — where a rep is identified by their email address, so an ERP import loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. This is a short code the ERP already owns (`salespersonCode` on a Business Central customer, `Representative_Code_RAITS` on the customer row), unique per tenant, and FIXED once created: every assignment and every impersonation entry stores it, and neither has a reference this app could follow to rename. Letters, digits, '.', '-' and '_', starting with a letter or a digit — the case is kept rather than folded, because the ERP's codes are upper case and a column that folded them would stop matching the system it points at.
     * @param {string} name - What the rep is called, as a person reads it — the one field every list of reps has to show. At least one character. It is the field a merchant renames after a marriage or a typo, which is precisely why it is not the identity.
     * @param {boolean} active - Whether this rep is currently working. Deactivating is what 'this person has left' means here, and it is NOT a delete: the record stays, the assignments stay, and the impersonation entries that name the code keep pointing at somebody. That is the whole reason the column exists — the history has to remain answerable. Defaults to true, because a rep is created in order to work. Defaults to true.
     * @param {string} email - The rep's address, and NOTHING depends on it being unique or even present. That is the point: it is the column the predecessor used as the primary key, so here it is an ordinary attribute a merchant may leave empty, change, or share between two reps who work one shared mailbox. An import that only knows a code and a name records a usable rep. What a login is bound to is `platform_user_id`, which is a different column for a reason.
     * @param {string} externalId - The key this rep has in the system that OWNS them — the ERP's own row id, as distinct from the `code` printed on a customer record. Unique per tenant where it is set. It is the second handle a feed can find a rep by: `code` is the one a human quotes and the one this app's other tables store, and this is the one a synchronisation matches on when even the code has been re-issued.
     * @param {object} externalRefs - Every OTHER system that knows this rep, keyed by system name. `external_id` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on `metadata`.
     * @param {object} metadata - Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so `?metadata=north` is refused with 400 `invalid_value` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.
     * @param {string} phone - How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.
     * @param {string} platformUserId - The bridge to a login: the platform identity a rep signs in with, once this app has an auth surface. Null on every rep today, because nothing mints one yet — a rep created now is a RECORD, not an account. It is an id and not a secret: no credential, no password hash and no session token is stored in this app at all, which is why there is nothing here a read has to withhold. Nothing mints one yet; a value sent here is stored and acted on by nothing.
     * @param {object} sourceData - What the source said about this rep, kept as it said it. Carries the ETag a write-back has to return in `If-Match`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on `metadata`.
     * @param {string} sourceSyncedAt - When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.
     * @param {string} territory - The patch this rep covers, as ONE piece of text and not a tree. A hierarchy of territories is deliberately out of scope: the rows that decide what a rep actually sees are the assignments, and a territory here is a label an operator groups a list by. Nothing in this app branches on it.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Rep>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsRepsCreate(code: string, name: string, active?: boolean, email?: string, externalId?: string, externalRefs?: object, metadata?: object, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string): Promise<Models.Rep>;
    salesRepsRepsCreate(
        paramsOrFirst: { code: string, name: string, active?: boolean, email?: string, externalId?: string, externalRefs?: object, metadata?: object, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string } | string,
        ...rest: [(string)?, (boolean)?, (string)?, (string)?, (object)?, (object)?, (string)?, (string)?, (object)?, (string)?, (string)?]    
    ): Promise<Models.Rep> {
        let params: { code: string, name: string, active?: boolean, email?: string, externalId?: string, externalRefs?: object, metadata?: object, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { code: string, name: string, active?: boolean, email?: string, externalId?: string, externalRefs?: object, metadata?: object, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string };
        } else {
            params = {
                code: paramsOrFirst as string,
                name: rest[0] as string,
                active: rest[1] as boolean,
                email: rest[2] as string,
                externalId: rest[3] as string,
                externalRefs: rest[4] as object,
                metadata: rest[5] as object,
                phone: rest[6] as string,
                platformUserId: rest[7] as string,
                sourceData: rest[8] as object,
                sourceSyncedAt: rest[9] as string,
                territory: rest[10] as string            
            };
        }
        
        const code = params.code;
        const name = params.name;
        const active = params.active;
        const email = params.email;
        const externalId = params.externalId;
        const externalRefs = params.externalRefs;
        const metadata = params.metadata;
        const phone = params.phone;
        const platformUserId = params.platformUserId;
        const sourceData = params.sourceData;
        const sourceSyncedAt = params.sourceSyncedAt;
        const territory = params.territory;

        if (typeof code === 'undefined') {
            throw new RevenexxException('Missing required parameter: "code"');
        }
        if (typeof name === 'undefined') {
            throw new RevenexxException('Missing required parameter: "name"');
        }

        const apiPath = '/v1/sales-reps/reps';
        const apiPayload: Payload = {};
        if (typeof active !== 'undefined') {
            apiPayload['active'] = active;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof email !== 'undefined') {
            apiPayload['email'] = email;
        }
        if (typeof externalId !== 'undefined') {
            apiPayload['external_id'] = externalId;
        }
        if (typeof externalRefs !== 'undefined') {
            apiPayload['external_refs'] = externalRefs;
        }
        if (typeof metadata !== 'undefined') {
            apiPayload['metadata'] = metadata;
        }
        if (typeof name !== 'undefined') {
            apiPayload['name'] = name;
        }
        if (typeof phone !== 'undefined') {
            apiPayload['phone'] = phone;
        }
        if (typeof platformUserId !== 'undefined') {
            apiPayload['platform_user_id'] = platformUserId;
        }
        if (typeof sourceData !== 'undefined') {
            apiPayload['source_data'] = sourceData;
        }
        if (typeof sourceSyncedAt !== 'undefined') {
            apiPayload['source_synced_at'] = sourceSyncedAt;
        }
        if (typeof territory !== 'undefined') {
            apiPayload['territory'] = territory;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. Almost always the wrong call, and the refusals say so. A rep who still carries customers is a 409 naming how many, and a rep who has ever acted for a buyer is a 409 too — the log references them by code and has no reference this app could cascade, so deleting them would leave the only record that a person acted for a buyer pointing at nobody. `PUT` with `active: false` is what "this person has left" means, and it keeps everything the history needs. What this route is for is a row created by mistake: a typo in a code, a duplicate an import filed before it was fixed.
     *
     * @param {string} params.id - The rep to remove.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    salesRepsRepsDelete(params: { id: string }): Promise<{}>;
    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. Almost always the wrong call, and the refusals say so. A rep who still carries customers is a 409 naming how many, and a rep who has ever acted for a buyer is a 409 too — the log references them by code and has no reference this app could cascade, so deleting them would leave the only record that a person acted for a buyer pointing at nobody. `PUT` with `active: false` is what "this person has left" means, and it keeps everything the history needs. What this route is for is a row created by mistake: a typo in a code, a duplicate an import filed before it was fixed.
     *
     * @param {string} id - The rep to remove.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsRepsDelete(id: string): Promise<{}>;
    salesRepsRepsDelete(
        paramsOrFirst: { id: string } | string    
    ): Promise<{}> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/reps/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'delete',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. The route that turns an id back into a rep. Note which handle goes where: this path takes the row's own `id`, while `assignments` and `impersonations` reference the rep by `code` — so a caller holding a code reads GET /sales-reps/reps?code=… instead of putting it here, where it would fail the uuid cast.
     *
     * @param {string} params.id - The rep to read.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Rep>}
     */
    salesRepsRepsGet(params: { id: string }): Promise<Models.Rep>;
    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. The route that turns an id back into a rep. Note which handle goes where: this path takes the row's own `id`, while `assignments` and `impersonations` reference the rep by `code` — so a caller holding a code reads GET /sales-reps/reps?code=… instead of putting it here, where it would fail the uuid cast.
     *
     * @param {string} id - The rep to read.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Rep>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsRepsGet(id: string): Promise<Models.Rep>;
    salesRepsRepsGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.Rep> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/reps/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. A partial update: omitted fields keep their value, and a body carrying no field at all is refused rather than answered as a no-op. ⚠ This is where a rep is DEACTIVATED, with `active: false`, and that is what "this person has left" means here — the record stays, the assignments stay, and the impersonation entries naming their code keep pointing at somebody, so the history stays answerable. `code` may be sent only unchanged: both other tables store it and neither has a reference this app could follow, so a rename would silently orphan every one of them. The provenance columns are the other ones to leave alone — `source_data` holds the ETag a write-back to the ERP has to return, and an edit here does not touch it.
     *
     * @param {string} params.id - The rep to edit.
     * @param {boolean} params.active - Whether this rep is currently working. Deactivating is what 'this person has left' means here, and it is NOT a delete: the record stays, the assignments stay, and the impersonation entries that name the code keep pointing at somebody. That is the whole reason the column exists — the history has to remain answerable. Defaults to true, because a rep is created in order to work. Defaults to true.
     * @param {string} params.code - The rep's STABLE IDENTITY, and the deliberate difference from the IntelliShop predecessor — where a rep is identified by their email address, so an ERP import loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. This is a short code the ERP already owns (`salespersonCode` on a Business Central customer, `Representative_Code_RAITS` on the customer row), unique per tenant, and FIXED once created: every assignment and every impersonation entry stores it, and neither has a reference this app could follow to rename. Letters, digits, '.', '-' and '_', starting with a letter or a digit — the case is kept rather than folded, because the ERP's codes are upper case and a column that folded them would stop matching the system it points at.
     * @param {string} params.email - The rep's address, and NOTHING depends on it being unique or even present. That is the point: it is the column the predecessor used as the primary key, so here it is an ordinary attribute a merchant may leave empty, change, or share between two reps who work one shared mailbox. An import that only knows a code and a name records a usable rep. What a login is bound to is `platform_user_id`, which is a different column for a reason.
     * @param {string} params.externalId - The key this rep has in the system that OWNS them — the ERP's own row id, as distinct from the `code` printed on a customer record. Unique per tenant where it is set. It is the second handle a feed can find a rep by: `code` is the one a human quotes and the one this app's other tables store, and this is the one a synchronisation matches on when even the code has been re-issued.
     * @param {object} params.externalRefs - Every OTHER system that knows this rep, keyed by system name. `external_id` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on `metadata`.
     * @param {object} params.metadata - Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so `?metadata=north` is refused with 400 `invalid_value` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.
     * @param {string} params.name - What the rep is called, as a person reads it — the one field every list of reps has to show. At least one character. It is the field a merchant renames after a marriage or a typo, which is precisely why it is not the identity.
     * @param {string} params.phone - How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.
     * @param {string} params.platformUserId - The bridge to a login: the platform identity a rep signs in with, once this app has an auth surface. Null on every rep today, because nothing mints one yet — a rep created now is a RECORD, not an account. It is an id and not a secret: no credential, no password hash and no session token is stored in this app at all, which is why there is nothing here a read has to withhold. Nothing mints one yet; a value sent here is stored and acted on by nothing.
     * @param {object} params.sourceData - What the source said about this rep, kept as it said it. Carries the ETag a write-back has to return in `If-Match`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on `metadata`.
     * @param {string} params.sourceSyncedAt - When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.
     * @param {string} params.territory - The patch this rep covers, as ONE piece of text and not a tree. A hierarchy of territories is deliberately out of scope: the rows that decide what a rep actually sees are the assignments, and a territory here is a label an operator groups a list by. Nothing in this app branches on it.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Rep>}
     */
    salesRepsRepsUpdate(params: { id: string, active?: boolean, code?: string, email?: string, externalId?: string, externalRefs?: object, metadata?: object, name?: string, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string }): Promise<Models.Rep>;
    /**
     * A rep is one field sales person, as a record this platform owns. They are identified by a `code` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. A partial update: omitted fields keep their value, and a body carrying no field at all is refused rather than answered as a no-op. ⚠ This is where a rep is DEACTIVATED, with `active: false`, and that is what "this person has left" means here — the record stays, the assignments stay, and the impersonation entries naming their code keep pointing at somebody, so the history stays answerable. `code` may be sent only unchanged: both other tables store it and neither has a reference this app could follow, so a rename would silently orphan every one of them. The provenance columns are the other ones to leave alone — `source_data` holds the ETag a write-back to the ERP has to return, and an edit here does not touch it.
     *
     * @param {string} id - The rep to edit.
     * @param {boolean} active - Whether this rep is currently working. Deactivating is what 'this person has left' means here, and it is NOT a delete: the record stays, the assignments stay, and the impersonation entries that name the code keep pointing at somebody. That is the whole reason the column exists — the history has to remain answerable. Defaults to true, because a rep is created in order to work. Defaults to true.
     * @param {string} code - The rep's STABLE IDENTITY, and the deliberate difference from the IntelliShop predecessor — where a rep is identified by their email address, so an ERP import loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. This is a short code the ERP already owns (`salespersonCode` on a Business Central customer, `Representative_Code_RAITS` on the customer row), unique per tenant, and FIXED once created: every assignment and every impersonation entry stores it, and neither has a reference this app could follow to rename. Letters, digits, '.', '-' and '_', starting with a letter or a digit — the case is kept rather than folded, because the ERP's codes are upper case and a column that folded them would stop matching the system it points at.
     * @param {string} email - The rep's address, and NOTHING depends on it being unique or even present. That is the point: it is the column the predecessor used as the primary key, so here it is an ordinary attribute a merchant may leave empty, change, or share between two reps who work one shared mailbox. An import that only knows a code and a name records a usable rep. What a login is bound to is `platform_user_id`, which is a different column for a reason.
     * @param {string} externalId - The key this rep has in the system that OWNS them — the ERP's own row id, as distinct from the `code` printed on a customer record. Unique per tenant where it is set. It is the second handle a feed can find a rep by: `code` is the one a human quotes and the one this app's other tables store, and this is the one a synchronisation matches on when even the code has been re-issued.
     * @param {object} externalRefs - Every OTHER system that knows this rep, keyed by system name. `external_id` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on `metadata`.
     * @param {object} metadata - Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so `?metadata=north` is refused with 400 `invalid_value` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.
     * @param {string} name - What the rep is called, as a person reads it — the one field every list of reps has to show. At least one character. It is the field a merchant renames after a marriage or a typo, which is precisely why it is not the identity.
     * @param {string} phone - How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.
     * @param {string} platformUserId - The bridge to a login: the platform identity a rep signs in with, once this app has an auth surface. Null on every rep today, because nothing mints one yet — a rep created now is a RECORD, not an account. It is an id and not a secret: no credential, no password hash and no session token is stored in this app at all, which is why there is nothing here a read has to withhold. Nothing mints one yet; a value sent here is stored and acted on by nothing.
     * @param {object} sourceData - What the source said about this rep, kept as it said it. Carries the ETag a write-back has to return in `If-Match`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on `metadata`.
     * @param {string} sourceSyncedAt - When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.
     * @param {string} territory - The patch this rep covers, as ONE piece of text and not a tree. A hierarchy of territories is deliberately out of scope: the rows that decide what a rep actually sees are the assignments, and a territory here is a label an operator groups a list by. Nothing in this app branches on it.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Rep>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsRepsUpdate(id: string, active?: boolean, code?: string, email?: string, externalId?: string, externalRefs?: object, metadata?: object, name?: string, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string): Promise<Models.Rep>;
    salesRepsRepsUpdate(
        paramsOrFirst: { id: string, active?: boolean, code?: string, email?: string, externalId?: string, externalRefs?: object, metadata?: object, name?: string, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string } | string,
        ...rest: [(boolean)?, (string)?, (string)?, (string)?, (object)?, (object)?, (string)?, (string)?, (string)?, (object)?, (string)?, (string)?]    
    ): Promise<Models.Rep> {
        let params: { id: string, active?: boolean, code?: string, email?: string, externalId?: string, externalRefs?: object, metadata?: object, name?: string, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string, active?: boolean, code?: string, email?: string, externalId?: string, externalRefs?: object, metadata?: object, name?: string, phone?: string, platformUserId?: string, sourceData?: object, sourceSyncedAt?: string, territory?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                active: rest[0] as boolean,
                code: rest[1] as string,
                email: rest[2] as string,
                externalId: rest[3] as string,
                externalRefs: rest[4] as object,
                metadata: rest[5] as object,
                name: rest[6] as string,
                phone: rest[7] as string,
                platformUserId: rest[8] as string,
                sourceData: rest[9] as object,
                sourceSyncedAt: rest[10] as string,
                territory: rest[11] as string            
            };
        }
        
        const id = params.id;
        const active = params.active;
        const code = params.code;
        const email = params.email;
        const externalId = params.externalId;
        const externalRefs = params.externalRefs;
        const metadata = params.metadata;
        const name = params.name;
        const phone = params.phone;
        const platformUserId = params.platformUserId;
        const sourceData = params.sourceData;
        const sourceSyncedAt = params.sourceSyncedAt;
        const territory = params.territory;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/reps/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        if (typeof active !== 'undefined') {
            apiPayload['active'] = active;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof email !== 'undefined') {
            apiPayload['email'] = email;
        }
        if (typeof externalId !== 'undefined') {
            apiPayload['external_id'] = externalId;
        }
        if (typeof externalRefs !== 'undefined') {
            apiPayload['external_refs'] = externalRefs;
        }
        if (typeof metadata !== 'undefined') {
            apiPayload['metadata'] = metadata;
        }
        if (typeof name !== 'undefined') {
            apiPayload['name'] = name;
        }
        if (typeof phone !== 'undefined') {
            apiPayload['phone'] = phone;
        }
        if (typeof platformUserId !== 'undefined') {
            apiPayload['platform_user_id'] = platformUserId;
        }
        if (typeof sourceData !== 'undefined') {
            apiPayload['source_data'] = sourceData;
        }
        if (typeof sourceSyncedAt !== 'undefined') {
            apiPayload['source_synced_at'] = sourceSyncedAt;
        }
        if (typeof territory !== 'undefined') {
            apiPayload['territory'] = territory;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'put',
            uri,
            apiHeaders,
            apiPayload
        );
    }
}
