import { Service } from '../service';
import { RevenexxException, Client, type Payload, UploadProgress } from '../client';
import type { Models } from '../models';

import { Tone } from '../enums/tone';
import { SalesRepsVocabulariesGetName } from '../enums/sales-reps-vocabularies-get-name';

export class SalesRepsCoverage {
    client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. This is the operator's view of the set — the rows, filterable and paged, in whatever order you ask for. A CLIENT that only wants to render a role does not want this route: GET /sales-reps/vocabularies/assignment-roles answers the same set keyed by code, ordered by `position`, with the titles per language already merged, and it is the shape every other vocabulary on this platform is read in. A tenant who has never been seeded reads an EMPTY list here, because the seed runs on install and on POST /sales-reps/assignment-roles/defaults; the vocabulary route seeds on an empty read and this one does not.
     *
     * @param {string} params.id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} params.code - Resolve one role by the code a coverage row carries, without paging the whole set. Unique per tenant, so this answers at most one role.
     * @param {string} params.title - Filter to rows whose `title` is exactly this value. What this role is called, as a person reads it — the text a list or a badge shows. At least one character. It carries one language; the per-language forms are in `labels`.
     * @param {string} params.description - Filter to rows whose `description` is exactly this value. What this role means, in the merchant's own words — the sentence an operator reads under the choice when they are deciding which one a rep has. Optional, one language, with the per-language forms in `descriptions`.
     * @param {boolean} params.isDefault - The role an import falls back to, which should be at most one — and is none at all until the tenant decides, because no seeded role carries the flag.
     * @param {Tone} params.tone - Filter to rows whose `tone` is exactly this value. The semantic badge colour a screen renders this role in. The client owns what each tone looks like; this only says what the role MEANS — that the desk which visits the customer reads differently from the one that answers the phone. Defaults to neutral.
     * @param {number} params.position - Filter to rows whose `position` is exactly this value. Where this role sits in the order a select offers the roles, ascending, ties broken by the code. It is presentation and nothing branches on it: a rep is not more senior for sorting first.
     * @param {boolean} params.isSystem - `true` is the roles this app seeded, `false` the ones this tenant added. It separates the two for a screen that wants to say so, and licenses nothing either way.
     * @param {string} params.createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {string} params.updatedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} params.offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} params.order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    salesRepsAssignmentRolesList(params?: { id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string }): Promise<{}>;
    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. This is the operator's view of the set — the rows, filterable and paged, in whatever order you ask for. A CLIENT that only wants to render a role does not want this route: GET /sales-reps/vocabularies/assignment-roles answers the same set keyed by code, ordered by `position`, with the titles per language already merged, and it is the shape every other vocabulary on this platform is read in. A tenant who has never been seeded reads an EMPTY list here, because the seed runs on install and on POST /sales-reps/assignment-roles/defaults; the vocabulary route seeds on an empty read and this one does not.
     *
     * @param {string} id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} code - Resolve one role by the code a coverage row carries, without paging the whole set. Unique per tenant, so this answers at most one role.
     * @param {string} title - Filter to rows whose `title` is exactly this value. What this role is called, as a person reads it — the text a list or a badge shows. At least one character. It carries one language; the per-language forms are in `labels`.
     * @param {string} description - Filter to rows whose `description` is exactly this value. What this role means, in the merchant's own words — the sentence an operator reads under the choice when they are deciding which one a rep has. Optional, one language, with the per-language forms in `descriptions`.
     * @param {boolean} isDefault - The role an import falls back to, which should be at most one — and is none at all until the tenant decides, because no seeded role carries the flag.
     * @param {Tone} tone - Filter to rows whose `tone` is exactly this value. The semantic badge colour a screen renders this role in. The client owns what each tone looks like; this only says what the role MEANS — that the desk which visits the customer reads differently from the one that answers the phone. Defaults to neutral.
     * @param {number} position - Filter to rows whose `position` is exactly this value. Where this role sits in the order a select offers the roles, ascending, ties broken by the code. It is presentation and nothing branches on it: a rep is not more senior for sorting first.
     * @param {boolean} isSystem - `true` is the roles this app seeded, `false` the ones this tenant added. It separates the two for a screen that wants to say so, and licenses nothing either way.
     * @param {string} createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {string} updatedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentRolesList(id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string): Promise<{}>;
    salesRepsAssignmentRolesList(
        paramsOrFirst?: { id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string } | string,
        ...rest: [(string)?, (string)?, (string)?, (boolean)?, (Tone)?, (number)?, (boolean)?, (string)?, (string)?, (number)?, (number)?, (string)?]    
    ): Promise<{}> {
        let params: { id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id?: string, code?: string, title?: string, description?: string, isDefault?: boolean, tone?: Tone, position?: number, isSystem?: boolean, createdAt?: string, updatedAt?: string, limit?: number, offset?: number, order?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                code: rest[0] as string,
                title: rest[1] as string,
                description: rest[2] as string,
                isDefault: rest[3] as boolean,
                tone: rest[4] as Tone,
                position: rest[5] as number,
                isSystem: rest[6] as boolean,
                createdAt: rest[7] as string,
                updatedAt: rest[8] as string,
                limit: rest[9] as number,
                offset: rest[10] as number,
                order: rest[11] as string            
            };
        }
        
        const id = params.id;
        const code = params.code;
        const title = params.title;
        const description = params.description;
        const isDefault = params.isDefault;
        const tone = params.tone;
        const position = params.position;
        const isSystem = params.isSystem;
        const createdAt = params.createdAt;
        const updatedAt = params.updatedAt;
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;


        const apiPath = '/v1/sales-reps/assignment-roles';
        const apiPayload: Payload = {};
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof title !== 'undefined') {
            apiPayload['title'] = title;
        }
        if (typeof description !== 'undefined') {
            apiPayload['description'] = description;
        }
        if (typeof isDefault !== 'undefined') {
            apiPayload['is_default'] = isDefault;
        }
        if (typeof tone !== 'undefined') {
            apiPayload['tone'] = tone;
        }
        if (typeof position !== 'undefined') {
            apiPayload['position'] = position;
        }
        if (typeof isSystem !== 'undefined') {
            apiPayload['is_system'] = isSystem;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof updatedAt !== 'undefined') {
            apiPayload['updated_at'] = updatedAt;
        }
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. Reach for this when a merchant's sales organisation distinguishes something the three seeded roles do not — a technical adviser, a branch counter, a desk that only handles framework terms. `code` and `title` are owed and the code should be treated as permanent: a coverage row stores it, nothing in the database points at it, so renaming it later leaves every row carrying the old one. Adding a role changes nothing on its own — a coverage row has to name it before it means anything, and the mapping from a source system's own values onto these codes is made where the import runs.
     *
     * @param {string} params.code - The role as STORED, and what a coverage row's `role` carries. Lowercase letters, digits, '-' and '_', starting with a letter — the shape every vocabulary code on this platform has, so a client may use it as a key. It should be treated as permanent even though the edit route accepts it: nothing in the database points at it, so renaming it leaves every coverage row that named the old value carrying a code the vocabulary no longer resolves.
     * @param {string} params.title - What this role is called, as a person reads it — the text a list or a badge shows. At least one character. It carries one language; the per-language forms are in `labels`.
     * @param {string} params.description - What this role means, in the merchant's own words — the sentence an operator reads under the choice when they are deciding which one a rep has. Optional, one language, with the per-language forms in `descriptions`.
     * @param {object} params.descriptions - The description per language tag, on the same rule as `labels`. Answered and NOT filterable.
     * @param {boolean} params.isDefault - Whether this is the role an import falls back to when a source value maps to none of the others. Nothing in this app reads it; it is served so an importer can find the fallback here instead of keeping a convention of its own. FALSE on every role this app seeds, and that is deliberate: a source system delivers no role at all, so a seeded default would not label the odd unmapped row — it would label every imported assignment as whichever role somebody guessed. Which role an unmapped value means is the tenant's to say. Defaults to false, and no role this app seeds carries it.
     * @param {boolean} params.isSystem - True for a role this app seeded, false for one the tenant added. It means "we put it there" and licenses nothing — a seeded role may be renamed, re-toned, reordered or removed exactly like any other, and nothing here treats the two differently. Send false or leave it out: it means this app seeded the row, and a tenant claiming it changes nothing but the truth of the flag.
     * @param {object} params.labels - The title per language tag, as the tenant stored it. `title` is the same text in their working language, so a client reading one tag can ignore this. It is a jsonb column: answered, and NOT a query parameter — see the note on `metadata`.
     * @param {number} params.position - Where this role sits in the order a select offers the roles, ascending, ties broken by the code. It is presentation and nothing branches on it: a rep is not more senior for sorting first. Defaults to 0.
     * @param {Tone} params.tone - The semantic badge colour a screen renders this role in. The client owns what each tone looks like; this only says what the role MEANS — that the desk which visits the customer reads differently from the one that answers the phone. Defaults to neutral. Defaults to neutral.
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentRole>}
     */
    salesRepsAssignmentRolesCreate(params: { code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, tone?: Tone }): Promise<Models.AssignmentRole>;
    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. Reach for this when a merchant's sales organisation distinguishes something the three seeded roles do not — a technical adviser, a branch counter, a desk that only handles framework terms. `code` and `title` are owed and the code should be treated as permanent: a coverage row stores it, nothing in the database points at it, so renaming it later leaves every row carrying the old one. Adding a role changes nothing on its own — a coverage row has to name it before it means anything, and the mapping from a source system's own values onto these codes is made where the import runs.
     *
     * @param {string} code - The role as STORED, and what a coverage row's `role` carries. Lowercase letters, digits, '-' and '_', starting with a letter — the shape every vocabulary code on this platform has, so a client may use it as a key. It should be treated as permanent even though the edit route accepts it: nothing in the database points at it, so renaming it leaves every coverage row that named the old value carrying a code the vocabulary no longer resolves.
     * @param {string} title - What this role is called, as a person reads it — the text a list or a badge shows. At least one character. It carries one language; the per-language forms are in `labels`.
     * @param {string} description - What this role means, in the merchant's own words — the sentence an operator reads under the choice when they are deciding which one a rep has. Optional, one language, with the per-language forms in `descriptions`.
     * @param {object} descriptions - The description per language tag, on the same rule as `labels`. Answered and NOT filterable.
     * @param {boolean} isDefault - Whether this is the role an import falls back to when a source value maps to none of the others. Nothing in this app reads it; it is served so an importer can find the fallback here instead of keeping a convention of its own. FALSE on every role this app seeds, and that is deliberate: a source system delivers no role at all, so a seeded default would not label the odd unmapped row — it would label every imported assignment as whichever role somebody guessed. Which role an unmapped value means is the tenant's to say. Defaults to false, and no role this app seeds carries it.
     * @param {boolean} isSystem - True for a role this app seeded, false for one the tenant added. It means "we put it there" and licenses nothing — a seeded role may be renamed, re-toned, reordered or removed exactly like any other, and nothing here treats the two differently. Send false or leave it out: it means this app seeded the row, and a tenant claiming it changes nothing but the truth of the flag.
     * @param {object} labels - The title per language tag, as the tenant stored it. `title` is the same text in their working language, so a client reading one tag can ignore this. It is a jsonb column: answered, and NOT a query parameter — see the note on `metadata`.
     * @param {number} position - Where this role sits in the order a select offers the roles, ascending, ties broken by the code. It is presentation and nothing branches on it: a rep is not more senior for sorting first. Defaults to 0.
     * @param {Tone} tone - The semantic badge colour a screen renders this role in. The client owns what each tone looks like; this only says what the role MEANS — that the desk which visits the customer reads differently from the one that answers the phone. Defaults to neutral. Defaults to neutral.
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentRole>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentRolesCreate(code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, tone?: Tone): Promise<Models.AssignmentRole>;
    salesRepsAssignmentRolesCreate(
        paramsOrFirst: { code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, tone?: Tone } | string,
        ...rest: [(string)?, (string)?, (object)?, (boolean)?, (boolean)?, (object)?, (number)?, (Tone)?]    
    ): Promise<Models.AssignmentRole> {
        let params: { code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, tone?: Tone };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { code: string, title: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, tone?: Tone };
        } else {
            params = {
                code: paramsOrFirst as string,
                title: rest[0] as string,
                description: rest[1] as string,
                descriptions: rest[2] as object,
                isDefault: rest[3] as boolean,
                isSystem: rest[4] as boolean,
                labels: rest[5] as object,
                position: rest[6] as number,
                tone: rest[7] as Tone            
            };
        }
        
        const code = params.code;
        const title = params.title;
        const description = params.description;
        const descriptions = params.descriptions;
        const isDefault = params.isDefault;
        const isSystem = params.isSystem;
        const labels = params.labels;
        const position = params.position;
        const tone = params.tone;

        if (typeof code === 'undefined') {
            throw new RevenexxException('Missing required parameter: "code"');
        }
        if (typeof title === 'undefined') {
            throw new RevenexxException('Missing required parameter: "title"');
        }

        const apiPath = '/v1/sales-reps/assignment-roles';
        const apiPayload: Payload = {};
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof description !== 'undefined') {
            apiPayload['description'] = description;
        }
        if (typeof descriptions !== 'undefined') {
            apiPayload['descriptions'] = descriptions;
        }
        if (typeof isDefault !== 'undefined') {
            apiPayload['is_default'] = isDefault;
        }
        if (typeof isSystem !== 'undefined') {
            apiPayload['is_system'] = isSystem;
        }
        if (typeof labels !== 'undefined') {
            apiPayload['labels'] = labels;
        }
        if (typeof position !== 'undefined') {
            apiPayload['position'] = position;
        }
        if (typeof title !== 'undefined') {
            apiPayload['title'] = title;
        }
        if (typeof tone !== 'undefined') {
            apiPayload['tone'] = tone;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Puts the three generic roles this app ships — `field_sales`, `inside_sales`, `key_account` — into a tenant that does not have them, and leaves alone every one they already do. Idempotent BY CODE: a role the merchant renamed, re-toned, reordered or retired is untouched, so calling it twice is free and calling it after a year changes nothing a merchant did. It exists because the platform's installed announcement does NOT reliably fire on a marketplace install, so anything that needs the set to be there calls this rather than trusting it. Nothing else is seeded — no rep and no coverage row, because a rep is somebody a merchant employs and an invented one would be a person nobody hired appearing on a customer record. None of the three carries `is_default`: which role an unmapped source value means is the tenant's to say, and a default seeded here would silently label every imported assignment.
     *
     * @param {object} params.data - Request body
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentRoleDefaultsResponse>}
     */
    salesRepsAssignmentRolesDefaults(params: { data: object }): Promise<Models.AssignmentRoleDefaultsResponse>;
    /**
     * Puts the three generic roles this app ships — `field_sales`, `inside_sales`, `key_account` — into a tenant that does not have them, and leaves alone every one they already do. Idempotent BY CODE: a role the merchant renamed, re-toned, reordered or retired is untouched, so calling it twice is free and calling it after a year changes nothing a merchant did. It exists because the platform's installed announcement does NOT reliably fire on a marketplace install, so anything that needs the set to be there calls this rather than trusting it. Nothing else is seeded — no rep and no coverage row, because a rep is somebody a merchant employs and an invented one would be a person nobody hired appearing on a customer record. None of the three carries `is_default`: which role an unmapped source value means is the tenant's to say, and a default seeded here would silently label every imported assignment.
     *
     * @param {object} data - Request body
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentRoleDefaultsResponse>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentRolesDefaults(data: object): Promise<Models.AssignmentRoleDefaultsResponse>;
    salesRepsAssignmentRolesDefaults(
        paramsOrFirst: { data: object } | object    
    ): Promise<Models.AssignmentRoleDefaultsResponse> {
        let params: { data: object };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst) && ('data' in paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { data: object };
        } else {
            params = {
                data: paramsOrFirst as object            
            };
        }
        
        const data = params.data;

        if (typeof data === 'undefined') {
            throw new RevenexxException('Missing required parameter: "data"');
        }

        const apiPath = '/v1/sales-reps/assignment-roles/defaults';
        const apiPayload: Payload = {};
        if (typeof data !== 'undefined') {
            Object.assign(apiPayload, data);
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. ⚠ What is NOT checked here is the thing that matters: a coverage row stores the CODE and not this id, so nothing refuses the delete while rows still carry it, and those rows keep a role code the vocabulary no longer resolves. The set is `closed`, so a client reads such a value as stale data rather than as a missing label — but it reads no title and no tone for it either, and a screen that was showing "Inside sales" starts showing a bare code. Move the rows onto another role first (PUT /sales-reps/assignments/{id}), or leave the role in place and give it a `title` that says it is retired. Deleting all of them is undone by the next read of GET /sales-reps/vocabularies/assignment-roles, which seeds the shipped set back into an empty table.
     *
     * @param {string} params.id - The row id of the role to remove, as the list answered it.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    salesRepsAssignmentRolesDelete(params: { id: string }): Promise<{}>;
    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. ⚠ What is NOT checked here is the thing that matters: a coverage row stores the CODE and not this id, so nothing refuses the delete while rows still carry it, and those rows keep a role code the vocabulary no longer resolves. The set is `closed`, so a client reads such a value as stale data rather than as a missing label — but it reads no title and no tone for it either, and a screen that was showing "Inside sales" starts showing a bare code. Move the rows onto another role first (PUT /sales-reps/assignments/{id}), or leave the role in place and give it a `title` that says it is retired. Deleting all of them is undone by the next read of GET /sales-reps/vocabularies/assignment-roles, which seeds the shipped set back into an empty table.
     *
     * @param {string} id - The row id of the role to remove, as the list answered it.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentRolesDelete(id: string): Promise<{}>;
    salesRepsAssignmentRolesDelete(
        paramsOrFirst: { id: string } | string    
    ): Promise<{}> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/assignment-roles/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'delete',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. This reads one of them by ROW ID, which is what an editor holds after listing the set and is not what anything else stores: a coverage row carries the CODE. A caller holding a code cannot use this route — filter the collection with `?code=`, or read GET /sales-reps/vocabularies/assignment-roles, which is keyed the way the rest of the platform refers to these values.
     *
     * @param {string} params.id - The row id of the role, as the list answered it. Not the code — a coverage row carries the code, and this route does not accept one.
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentRole>}
     */
    salesRepsAssignmentRolesGet(params: { id: string }): Promise<Models.AssignmentRole>;
    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. This reads one of them by ROW ID, which is what an editor holds after listing the set and is not what anything else stores: a coverage row carries the CODE. A caller holding a code cannot use this route — filter the collection with `?code=`, or read GET /sales-reps/vocabularies/assignment-roles, which is keyed the way the rest of the platform refers to these values.
     *
     * @param {string} id - The row id of the role, as the list answered it. Not the code — a coverage row carries the code, and this route does not accept one.
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentRole>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentRolesGet(id: string): Promise<Models.AssignmentRole>;
    salesRepsAssignmentRolesGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.AssignmentRole> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/assignment-roles/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. A partial update: omitted fields keep their value, and a body carrying no field at all is refused rather than answered as a no-op. The safe edits are the readable ones — `title`, `labels`, `description`, `descriptions`, `tone`, `position` — and they reach every screen at once, which is the point of the set living here. `code` is the one to leave alone: a coverage row stores it and nothing points at it, so moving it leaves every row that named the old value carrying a code the vocabulary no longer resolves. A role this app seeded may be edited exactly like one the tenant added; `is_system` records who put it there and licenses nothing.
     *
     * @param {string} params.id - The row id of the role to change, as the list answered it.
     * @param {string} params.code - The role as STORED, and what a coverage row's `role` carries. Lowercase letters, digits, '-' and '_', starting with a letter — the shape every vocabulary code on this platform has, so a client may use it as a key. It should be treated as permanent even though the edit route accepts it: nothing in the database points at it, so renaming it leaves every coverage row that named the old value carrying a code the vocabulary no longer resolves.
     * @param {string} params.description - What this role means, in the merchant's own words — the sentence an operator reads under the choice when they are deciding which one a rep has. Optional, one language, with the per-language forms in `descriptions`.
     * @param {object} params.descriptions - The description per language tag, on the same rule as `labels`. Answered and NOT filterable.
     * @param {boolean} params.isDefault - Whether this is the role an import falls back to when a source value maps to none of the others. Nothing in this app reads it; it is served so an importer can find the fallback here instead of keeping a convention of its own. FALSE on every role this app seeds, and that is deliberate: a source system delivers no role at all, so a seeded default would not label the odd unmapped row — it would label every imported assignment as whichever role somebody guessed. Which role an unmapped value means is the tenant's to say. Defaults to false, and no role this app seeds carries it.
     * @param {boolean} params.isSystem - True for a role this app seeded, false for one the tenant added. It means "we put it there" and licenses nothing — a seeded role may be renamed, re-toned, reordered or removed exactly like any other, and nothing here treats the two differently. Send false or leave it out: it means this app seeded the row, and a tenant claiming it changes nothing but the truth of the flag.
     * @param {object} params.labels - The title per language tag, as the tenant stored it. `title` is the same text in their working language, so a client reading one tag can ignore this. It is a jsonb column: answered, and NOT a query parameter — see the note on `metadata`.
     * @param {number} params.position - Where this role sits in the order a select offers the roles, ascending, ties broken by the code. It is presentation and nothing branches on it: a rep is not more senior for sorting first. Defaults to 0.
     * @param {string} params.title - What this role is called, as a person reads it — the text a list or a badge shows. At least one character. It carries one language; the per-language forms are in `labels`.
     * @param {Tone} params.tone - The semantic badge colour a screen renders this role in. The client owns what each tone looks like; this only says what the role MEANS — that the desk which visits the customer reads differently from the one that answers the phone. Defaults to neutral. Defaults to neutral.
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentRole>}
     */
    salesRepsAssignmentRolesUpdate(params: { id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, title?: string, tone?: Tone }): Promise<Models.AssignmentRole>;
    /**
     * An assignment role is one of the roles THIS TENANT keeps for what a rep does for a customer they carry — field sales, inside sales, a key-account desk, or whatever a merchant's own sales organisation distinguishes. A coverage row stores the `code`; this row carries the words a person reads for it and the tone a screen colours it in. The set is a table and not a fixed list because what those desks are called is the merchant's to state. A partial update: omitted fields keep their value, and a body carrying no field at all is refused rather than answered as a no-op. The safe edits are the readable ones — `title`, `labels`, `description`, `descriptions`, `tone`, `position` — and they reach every screen at once, which is the point of the set living here. `code` is the one to leave alone: a coverage row stores it and nothing points at it, so moving it leaves every row that named the old value carrying a code the vocabulary no longer resolves. A role this app seeded may be edited exactly like one the tenant added; `is_system` records who put it there and licenses nothing.
     *
     * @param {string} id - The row id of the role to change, as the list answered it.
     * @param {string} code - The role as STORED, and what a coverage row's `role` carries. Lowercase letters, digits, '-' and '_', starting with a letter — the shape every vocabulary code on this platform has, so a client may use it as a key. It should be treated as permanent even though the edit route accepts it: nothing in the database points at it, so renaming it leaves every coverage row that named the old value carrying a code the vocabulary no longer resolves.
     * @param {string} description - What this role means, in the merchant's own words — the sentence an operator reads under the choice when they are deciding which one a rep has. Optional, one language, with the per-language forms in `descriptions`.
     * @param {object} descriptions - The description per language tag, on the same rule as `labels`. Answered and NOT filterable.
     * @param {boolean} isDefault - Whether this is the role an import falls back to when a source value maps to none of the others. Nothing in this app reads it; it is served so an importer can find the fallback here instead of keeping a convention of its own. FALSE on every role this app seeds, and that is deliberate: a source system delivers no role at all, so a seeded default would not label the odd unmapped row — it would label every imported assignment as whichever role somebody guessed. Which role an unmapped value means is the tenant's to say. Defaults to false, and no role this app seeds carries it.
     * @param {boolean} isSystem - True for a role this app seeded, false for one the tenant added. It means "we put it there" and licenses nothing — a seeded role may be renamed, re-toned, reordered or removed exactly like any other, and nothing here treats the two differently. Send false or leave it out: it means this app seeded the row, and a tenant claiming it changes nothing but the truth of the flag.
     * @param {object} labels - The title per language tag, as the tenant stored it. `title` is the same text in their working language, so a client reading one tag can ignore this. It is a jsonb column: answered, and NOT a query parameter — see the note on `metadata`.
     * @param {number} position - Where this role sits in the order a select offers the roles, ascending, ties broken by the code. It is presentation and nothing branches on it: a rep is not more senior for sorting first. Defaults to 0.
     * @param {string} title - What this role is called, as a person reads it — the text a list or a badge shows. At least one character. It carries one language; the per-language forms are in `labels`.
     * @param {Tone} tone - The semantic badge colour a screen renders this role in. The client owns what each tone looks like; this only says what the role MEANS — that the desk which visits the customer reads differently from the one that answers the phone. Defaults to neutral. Defaults to neutral.
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentRole>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentRolesUpdate(id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, title?: string, tone?: Tone): Promise<Models.AssignmentRole>;
    salesRepsAssignmentRolesUpdate(
        paramsOrFirst: { id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, title?: string, tone?: Tone } | string,
        ...rest: [(string)?, (string)?, (object)?, (boolean)?, (boolean)?, (object)?, (number)?, (string)?, (Tone)?]    
    ): Promise<Models.AssignmentRole> {
        let params: { id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, title?: string, tone?: Tone };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string, code?: string, description?: string, descriptions?: object, isDefault?: boolean, isSystem?: boolean, labels?: object, position?: number, title?: string, tone?: Tone };
        } else {
            params = {
                id: paramsOrFirst as string,
                code: rest[0] as string,
                description: rest[1] as string,
                descriptions: rest[2] as object,
                isDefault: rest[3] as boolean,
                isSystem: rest[4] as boolean,
                labels: rest[5] as object,
                position: rest[6] as number,
                title: rest[7] as string,
                tone: rest[8] as Tone            
            };
        }
        
        const id = params.id;
        const code = params.code;
        const description = params.description;
        const descriptions = params.descriptions;
        const isDefault = params.isDefault;
        const isSystem = params.isSystem;
        const labels = params.labels;
        const position = params.position;
        const title = params.title;
        const tone = params.tone;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/assignment-roles/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        if (typeof code !== 'undefined') {
            apiPayload['code'] = code;
        }
        if (typeof description !== 'undefined') {
            apiPayload['description'] = description;
        }
        if (typeof descriptions !== 'undefined') {
            apiPayload['descriptions'] = descriptions;
        }
        if (typeof isDefault !== 'undefined') {
            apiPayload['is_default'] = isDefault;
        }
        if (typeof isSystem !== 'undefined') {
            apiPayload['is_system'] = isSystem;
        }
        if (typeof labels !== 'undefined') {
            apiPayload['labels'] = labels;
        }
        if (typeof position !== 'undefined') {
            apiPayload['position'] = position;
        }
        if (typeof title !== 'undefined') {
            apiPayload['title'] = title;
        }
        if (typeof tone !== 'undefined') {
            apiPayload['tone'] = tone;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'put',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. Read in either direction, and both are ordinary: `?rep_code=` is one rep's customers, `?organization_id=` is one customer's reps. The second is the reason this is a table and not a column on the organization — field sales plus inside sales share a customer, and a single column could hold only one of them. A deactivated rep's assignments are still here, and are not marked in any way: join the rep by code to find out whether the person is still working.
     *
     * @param {string} params.id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} params.repCode - ONE rep's customers — the read the coverage question starts from. It takes the rep's `code`, not their row id.
     * @param {string} params.organizationId - ONE customer's reps, which is the other direction of the same table and the reason the pair is not a single column on the organization: field sales plus inside sales is the ordinary case.
     * @param {string} params.role - The coverage carried in one role — `?role=field_sales` is every account somebody visits, and it is how the reps of one customer are told apart once they have been classified. The value has to be a code this tenant keeps; one they do not is an empty page rather than an error, because a filter is not a write. There is no way to ask for the rows carrying NO role, which is the ordinary state of imported coverage: this API has no is-null filter.
     * @param {boolean} params.isPrimary - Combined with `?organization_id=`, the responsible rep for one customer — the read that turns a many-to-many table back into the one answer a source system carries. `?is_primary=true` alone is every customer's responsible rep in one page, and it should answer at most one row per organization, because a partial unique index says so.
     * @param {string} params.createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} params.offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} params.order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    salesRepsAssignmentsList(params?: { id?: string, repCode?: string, organizationId?: string, role?: string, isPrimary?: boolean, createdAt?: string, limit?: number, offset?: number, order?: string }): Promise<{}>;
    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. Read in either direction, and both are ordinary: `?rep_code=` is one rep's customers, `?organization_id=` is one customer's reps. The second is the reason this is a table and not a column on the organization — field sales plus inside sales share a customer, and a single column could hold only one of them. A deactivated rep's assignments are still here, and are not marked in any way: join the rep by code to find out whether the person is still working.
     *
     * @param {string} id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} repCode - ONE rep's customers — the read the coverage question starts from. It takes the rep's `code`, not their row id.
     * @param {string} organizationId - ONE customer's reps, which is the other direction of the same table and the reason the pair is not a single column on the organization: field sales plus inside sales is the ordinary case.
     * @param {string} role - The coverage carried in one role — `?role=field_sales` is every account somebody visits, and it is how the reps of one customer are told apart once they have been classified. The value has to be a code this tenant keeps; one they do not is an empty page rather than an error, because a filter is not a write. There is no way to ask for the rows carrying NO role, which is the ordinary state of imported coverage: this API has no is-null filter.
     * @param {boolean} isPrimary - Combined with `?organization_id=`, the responsible rep for one customer — the read that turns a many-to-many table back into the one answer a source system carries. `?is_primary=true` alone is every customer's responsible rep in one page, and it should answer at most one row per organization, because a partial unique index says so.
     * @param {string} createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentsList(id?: string, repCode?: string, organizationId?: string, role?: string, isPrimary?: boolean, createdAt?: string, limit?: number, offset?: number, order?: string): Promise<{}>;
    salesRepsAssignmentsList(
        paramsOrFirst?: { id?: string, repCode?: string, organizationId?: string, role?: string, isPrimary?: boolean, createdAt?: string, limit?: number, offset?: number, order?: string } | string,
        ...rest: [(string)?, (string)?, (string)?, (boolean)?, (string)?, (number)?, (number)?, (string)?]    
    ): Promise<{}> {
        let params: { id?: string, repCode?: string, organizationId?: string, role?: string, isPrimary?: boolean, createdAt?: string, limit?: number, offset?: number, order?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id?: string, repCode?: string, organizationId?: string, role?: string, isPrimary?: boolean, createdAt?: string, limit?: number, offset?: number, order?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                repCode: rest[0] as string,
                organizationId: rest[1] as string,
                role: rest[2] as string,
                isPrimary: rest[3] as boolean,
                createdAt: rest[4] as string,
                limit: rest[5] as number,
                offset: rest[6] as number,
                order: rest[7] as string            
            };
        }
        
        const id = params.id;
        const repCode = params.repCode;
        const organizationId = params.organizationId;
        const role = params.role;
        const isPrimary = params.isPrimary;
        const createdAt = params.createdAt;
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;


        const apiPath = '/v1/sales-reps/assignments';
        const apiPayload: Payload = {};
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof repCode !== 'undefined') {
            apiPayload['rep_code'] = repCode;
        }
        if (typeof organizationId !== 'undefined') {
            apiPayload['organization_id'] = organizationId;
        }
        if (typeof role !== 'undefined') {
            apiPayload['role'] = role;
        }
        if (typeof isPrimary !== 'undefined') {
            apiPayload['is_primary'] = isPrimary;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. Both fields are owed. Recording the same pair twice is refused with a 409 that carries the id of the row already there — not answered as a no-op — so a caller that retried after a timeout learns which of the two things happened. The unique index `(tenant_id, rep_code, organization_id)` is the guard and the pre-flight read only makes the refusal readable. `rep_code` has to name a rep this tenant keeps, checked on every write because there is no foreign key to do it: the reference is by code precisely so an import can write coverage before it has read an id out of this app. There is deliberately no update route — changing either half of the pair is a different pair.
     *
     * @param {string} params.organizationId - WHICH customer, as the customers app knows the organization. Nothing here checks that the organization exists — it lives in another app, and a call on every write would fail a whole import for one organization somebody archived.
     * @param {string} params.repCode - WHICH rep this row is about, by their `code` rather than by their row id. The code is what an ERP already holds, so an import can write this row before it has ever read an id out of this app. There is no foreign key behind it: the check is a membership test against the rep table on every write, and a code that names no rep is refused with 400 `unknown_rep`. It is also why a rep's code cannot be renamed and why a rep carrying rows here cannot be deleted.
     * @param {string} params.role - WHAT this rep does for this customer, as one of the roles this tenant keeps (GET /sales-reps/assignment-roles, or GET /sales-reps/vocabularies/assignment-roles for the same set with the words a person reads for it). Deliberately not free text and deliberately not an enum of this app's: a code the tenant does not keep is refused with 400 naming the ones they do, and the set itself is a table they extend, because what a merchant's own sales desks are called is theirs to state. NULL is the ordinary case rather than a gap — a source system delivers one responsible salesperson per debtor and no role whatever, so an imported assignment honestly carries none. It answers a different question from `is_primary`: this says what the rep DOES, that says which of several reps is the responsible one. Optional: omit it and the row carries none, which is what an import that knows no role writes.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assignment>}
     */
    salesRepsAssignmentsCreate(params: { organizationId: string, repCode: string, role?: string }): Promise<Models.Assignment>;
    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. Both fields are owed. Recording the same pair twice is refused with a 409 that carries the id of the row already there — not answered as a no-op — so a caller that retried after a timeout learns which of the two things happened. The unique index `(tenant_id, rep_code, organization_id)` is the guard and the pre-flight read only makes the refusal readable. `rep_code` has to name a rep this tenant keeps, checked on every write because there is no foreign key to do it: the reference is by code precisely so an import can write coverage before it has read an id out of this app. There is deliberately no update route — changing either half of the pair is a different pair.
     *
     * @param {string} organizationId - WHICH customer, as the customers app knows the organization. Nothing here checks that the organization exists — it lives in another app, and a call on every write would fail a whole import for one organization somebody archived.
     * @param {string} repCode - WHICH rep this row is about, by their `code` rather than by their row id. The code is what an ERP already holds, so an import can write this row before it has ever read an id out of this app. There is no foreign key behind it: the check is a membership test against the rep table on every write, and a code that names no rep is refused with 400 `unknown_rep`. It is also why a rep's code cannot be renamed and why a rep carrying rows here cannot be deleted.
     * @param {string} role - WHAT this rep does for this customer, as one of the roles this tenant keeps (GET /sales-reps/assignment-roles, or GET /sales-reps/vocabularies/assignment-roles for the same set with the words a person reads for it). Deliberately not free text and deliberately not an enum of this app's: a code the tenant does not keep is refused with 400 naming the ones they do, and the set itself is a table they extend, because what a merchant's own sales desks are called is theirs to state. NULL is the ordinary case rather than a gap — a source system delivers one responsible salesperson per debtor and no role whatever, so an imported assignment honestly carries none. It answers a different question from `is_primary`: this says what the rep DOES, that says which of several reps is the responsible one. Optional: omit it and the row carries none, which is what an import that knows no role writes.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assignment>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentsCreate(organizationId: string, repCode: string, role?: string): Promise<Models.Assignment>;
    salesRepsAssignmentsCreate(
        paramsOrFirst: { organizationId: string, repCode: string, role?: string } | string,
        ...rest: [(string)?, (string)?]    
    ): Promise<Models.Assignment> {
        let params: { organizationId: string, repCode: string, role?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { organizationId: string, repCode: string, role?: string };
        } else {
            params = {
                organizationId: paramsOrFirst as string,
                repCode: rest[0] as string,
                role: rest[1] as string            
            };
        }
        
        const organizationId = params.organizationId;
        const repCode = params.repCode;
        const role = params.role;

        if (typeof organizationId === 'undefined') {
            throw new RevenexxException('Missing required parameter: "organizationId"');
        }
        if (typeof repCode === 'undefined') {
            throw new RevenexxException('Missing required parameter: "repCode"');
        }

        const apiPath = '/v1/sales-reps/assignments';
        const apiPayload: Payload = {};
        if (typeof organizationId !== 'undefined') {
            apiPayload['organization_id'] = organizationId;
        }
        if (typeof repCode !== 'undefined') {
            apiPayload['rep_code'] = repCode;
        }
        if (typeof role !== 'undefined') {
            apiPayload['role'] = role;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. Removing the pair says this rep no longer carries this customer. It touches neither side: the rep stays, the organization is another app's row entirely, and any impersonation entry recording that this rep once acted inside that organization stays exactly where it is — that is a fact about the past and not a permission. A rep who is leaving altogether is deactivated instead, which keeps their coverage readable.
     *
     * @param {string} params.id - The assignment to remove.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    salesRepsAssignmentsDelete(params: { id: string }): Promise<{}>;
    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. Removing the pair says this rep no longer carries this customer. It touches neither side: the rep stays, the organization is another app's row entirely, and any impersonation entry recording that this rep once acted inside that organization stays exactly where it is — that is a fact about the past and not a permission. A rep who is leaving altogether is deactivated instead, which keeps their coverage readable.
     *
     * @param {string} id - The assignment to remove.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentsDelete(id: string): Promise<{}>;
    salesRepsAssignmentsDelete(
        paramsOrFirst: { id: string } | string    
    ): Promise<{}> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/assignments/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'delete',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. The route that turns an id back into a pair. It exists for a client that held one — the create answers the id, and the 409 for a duplicate carries the id of the row that was already there — rather than because anything here is worth reading on its own.
     *
     * @param {string} params.id - The assignment to read.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assignment>}
     */
    salesRepsAssignmentsGet(params: { id: string }): Promise<Models.Assignment>;
    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. The route that turns an id back into a pair. It exists for a client that held one — the create answers the id, and the 409 for a duplicate carries the id of the row that was already there — rather than because anything here is worth reading on its own.
     *
     * @param {string} id - The assignment to read.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assignment>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentsGet(id: string): Promise<Models.Assignment>;
    salesRepsAssignmentsGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.Assignment> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/assignments/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. This route applies `role` and NOTHING else, and it exists for one reason: a source system delivers coverage with no role, so the classification is made here afterwards. The alternative — deleting the pair and recording it again — resets `created_at`, which is the only answer to "since when has this rep carried this account", and fires a delete and a create at every consumer, telling them coverage ended and restarted when it never lapsed. ⚠ The PAIR is still unchangeable: `rep_code` or `organization_id` sent with a different value is refused rather than ignored, because swapping either half is a different pair and a caller PUTting a whole record has to learn that the field was never going to be applied. `is_primary` is refused too, and for its own reason — promoting one rep has to demote the incumbent in the same call, which is what POST /sales-reps/assignments/{id}/make-primary is. Sending `role: null`, or an empty string, takes the role off again.
     *
     * @param {string} params.id - The assignment whose role is being corrected.
     * @param {string} params.role - WHAT this rep does for this customer, as one of the roles this tenant keeps (GET /sales-reps/assignment-roles, or GET /sales-reps/vocabularies/assignment-roles for the same set with the words a person reads for it). Deliberately not free text and deliberately not an enum of this app's: a code the tenant does not keep is refused with 400 naming the ones they do, and the set itself is a table they extend, because what a merchant's own sales desks are called is theirs to state. NULL is the ordinary case rather than a gap — a source system delivers one responsible salesperson per debtor and no role whatever, so an imported assignment honestly carries none. It answers a different question from `is_primary`: this says what the rep DOES, that says which of several reps is the responsible one.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assignment>}
     */
    salesRepsAssignmentsUpdate(params: { id: string, role?: string }): Promise<Models.Assignment>;
    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. This route applies `role` and NOTHING else, and it exists for one reason: a source system delivers coverage with no role, so the classification is made here afterwards. The alternative — deleting the pair and recording it again — resets `created_at`, which is the only answer to "since when has this rep carried this account", and fires a delete and a create at every consumer, telling them coverage ended and restarted when it never lapsed. ⚠ The PAIR is still unchangeable: `rep_code` or `organization_id` sent with a different value is refused rather than ignored, because swapping either half is a different pair and a caller PUTting a whole record has to learn that the field was never going to be applied. `is_primary` is refused too, and for its own reason — promoting one rep has to demote the incumbent in the same call, which is what POST /sales-reps/assignments/{id}/make-primary is. Sending `role: null`, or an empty string, takes the role off again.
     *
     * @param {string} id - The assignment whose role is being corrected.
     * @param {string} role - WHAT this rep does for this customer, as one of the roles this tenant keeps (GET /sales-reps/assignment-roles, or GET /sales-reps/vocabularies/assignment-roles for the same set with the words a person reads for it). Deliberately not free text and deliberately not an enum of this app's: a code the tenant does not keep is refused with 400 naming the ones they do, and the set itself is a table they extend, because what a merchant's own sales desks are called is theirs to state. NULL is the ordinary case rather than a gap — a source system delivers one responsible salesperson per debtor and no role whatever, so an imported assignment honestly carries none. It answers a different question from `is_primary`: this says what the rep DOES, that says which of several reps is the responsible one.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Assignment>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentsUpdate(id: string, role?: string): Promise<Models.Assignment>;
    salesRepsAssignmentsUpdate(
        paramsOrFirst: { id: string, role?: string } | string,
        ...rest: [(string)?]    
    ): Promise<Models.Assignment> {
        let params: { id: string, role?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string, role?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                role: rest[0] as string            
            };
        }
        
        const id = params.id;
        const role = params.role;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/assignments/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        if (typeof role !== 'undefined') {
            apiPayload['role'] = role;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'put',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. This promotes THIS assignment and demotes whoever held the flag for the SAME customer, in one call. The flag is a single answer per customer rather than a per-row opinion: a source system carries exactly one responsible salesperson per debtor while this table is many-to-many, so without it "the responsible one" cannot be told apart from "also covers them", and with two of them it cannot either.
     * 
     * It is a route and not a field for a reason worth knowing before reaching for the write instead. A plain `is_primary: true` runs into the partial unique index `(tenant_id, organization_id) WHERE is_primary` and answers 409, which leaves the caller to unset the incumbent first: two writes, in an order that matters, with a window in between where the customer has either no responsible rep or — if the second call never lands — still the old one, and no way to tell which happened.
     * 
     * The write is as small as the change: one write per row whose flag was wrong, and none at all for the rows that were already right. So an assignment that already holds the flag is answered 200 with nothing written and an empty `demoted`, which is what makes a repeated call free; a customer that had no responsible rep yet is answered with this one promoted and an empty `demoted` as well — the two cases differ in what was written, not in the answer's shape. A rep may be the responsible one for any number of customers: what is exclusive is the customer's side of the pair.
     *
     * @param {string} params.id - The assignment to make the primary one for its customer.
     * @param {object} params.data - Request body
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentMakePrimaryResponse>}
     */
    salesRepsAssignmentsMakePrimary(params: { id: string, data: object }): Promise<Models.AssignmentMakePrimaryResponse>;
    /**
     * An assignment is one rep carrying one customer. The pair is the row and the pair is unique per tenant: a rep carries many organizations, an organization may have several reps, and the same pair cannot be recorded twice. Two columns say what the pair alone cannot: `role` is what the rep DOES for this customer, as one of the roles this tenant keeps, and `is_primary` marks THE responsible rep — at most one per customer. This promotes THIS assignment and demotes whoever held the flag for the SAME customer, in one call. The flag is a single answer per customer rather than a per-row opinion: a source system carries exactly one responsible salesperson per debtor while this table is many-to-many, so without it "the responsible one" cannot be told apart from "also covers them", and with two of them it cannot either.
     * 
     * It is a route and not a field for a reason worth knowing before reaching for the write instead. A plain `is_primary: true` runs into the partial unique index `(tenant_id, organization_id) WHERE is_primary` and answers 409, which leaves the caller to unset the incumbent first: two writes, in an order that matters, with a window in between where the customer has either no responsible rep or — if the second call never lands — still the old one, and no way to tell which happened.
     * 
     * The write is as small as the change: one write per row whose flag was wrong, and none at all for the rows that were already right. So an assignment that already holds the flag is answered 200 with nothing written and an empty `demoted`, which is what makes a repeated call free; a customer that had no responsible rep yet is answered with this one promoted and an empty `demoted` as well — the two cases differ in what was written, not in the answer's shape. A rep may be the responsible one for any number of customers: what is exclusive is the customer's side of the pair.
     *
     * @param {string} id - The assignment to make the primary one for its customer.
     * @param {object} data - Request body
     * @throws {RevenexxException}
     * @returns {Promise<Models.AssignmentMakePrimaryResponse>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsAssignmentsMakePrimary(id: string, data: object): Promise<Models.AssignmentMakePrimaryResponse>;
    salesRepsAssignmentsMakePrimary(
        paramsOrFirst: { id: string, data: object } | string,
        ...rest: [(object)?]    
    ): Promise<Models.AssignmentMakePrimaryResponse> {
        let params: { id: string, data: object };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string, data: object };
        } else {
            params = {
                id: paramsOrFirst as string,
                data: rest[0] as object            
            };
        }
        
        const id = params.id;
        const data = params.data;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }
        if (typeof data === 'undefined') {
            throw new RevenexxException('Missing required parameter: "data"');
        }

        const apiPath = '/v1/sales-reps/assignments/{id}/make-primary'.replace('{id}', id);
        const apiPayload: Payload = {};
        if (typeof data !== 'undefined') {
            Object.assign(apiPayload, data);
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * Discovery for the vocabulary routes: the value sets this app publishes, each with its name, its title and its description and deliberately WITHOUT its values, so finding out what exists costs one small call and not one per vocabulary. Names: assignment-roles. Fetch one with GET /sales-reps/vocabularies/{name}; a client holding the qualified pair 'sales-reps.<name>' builds that URL from the pair alone and needs to know nothing else about this app.
     *
     * @throws {RevenexxException}
     * @returns {Promise<Models.SalesRepVocabularyIndex>}
     */
    salesRepsVocabulariesList(): Promise<Models.SalesRepVocabularyIndex> {

        const apiPath = '/v1/sales-reps/vocabularies';
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * One vocabulary in full: every permitted value, each carrying the title and description a person reads for it and the badge tone a UI colours it with, so a client renders a role without a hard-coded table of its own. `source` says who OWNS the set, and here it is always 'table' — the values are the TENANT's own rows, read per request and ordered by the position they gave them, so a merchant extends the set without waiting for a release of this app, and reading the set is what seeds the shipped one into a tenant that has never had it. `closed` is true all the same: the set is exhaustive at this moment, so a value outside it is stale data rather than a missing label — which is exactly the state a coverage row is left in when the role it names is deleted. Names: assignment-roles.
     *
     * @param {SalesRepsVocabulariesGetName} params.name - The vocabulary name — the part after the dot in the qualified id. One of: assignment-roles. Anything else is a 404, so the enum is the complete set and not a suggestion.
     * @throws {RevenexxException}
     * @returns {Promise<Models.SalesRepVocabulary>}
     */
    salesRepsVocabulariesGet(params: { name: SalesRepsVocabulariesGetName }): Promise<Models.SalesRepVocabulary>;
    /**
     * One vocabulary in full: every permitted value, each carrying the title and description a person reads for it and the badge tone a UI colours it with, so a client renders a role without a hard-coded table of its own. `source` says who OWNS the set, and here it is always 'table' — the values are the TENANT's own rows, read per request and ordered by the position they gave them, so a merchant extends the set without waiting for a release of this app, and reading the set is what seeds the shipped one into a tenant that has never had it. `closed` is true all the same: the set is exhaustive at this moment, so a value outside it is stale data rather than a missing label — which is exactly the state a coverage row is left in when the role it names is deleted. Names: assignment-roles.
     *
     * @param {SalesRepsVocabulariesGetName} name - The vocabulary name — the part after the dot in the qualified id. One of: assignment-roles. Anything else is a 404, so the enum is the complete set and not a suggestion.
     * @throws {RevenexxException}
     * @returns {Promise<Models.SalesRepVocabulary>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsVocabulariesGet(name: SalesRepsVocabulariesGetName): Promise<Models.SalesRepVocabulary>;
    salesRepsVocabulariesGet(
        paramsOrFirst: { name: SalesRepsVocabulariesGetName } | SalesRepsVocabulariesGetName    
    ): Promise<Models.SalesRepVocabulary> {
        let params: { name: SalesRepsVocabulariesGetName };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst) && ('name' in paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { name: SalesRepsVocabulariesGetName };
        } else {
            params = {
                name: paramsOrFirst as SalesRepsVocabulariesGetName            
            };
        }
        
        const name = params.name;

        if (typeof name === 'undefined') {
            throw new RevenexxException('Missing required parameter: "name"');
        }

        const apiPath = '/v1/sales-reps/vocabularies/{name}'.replace('{name}', name);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }
}
