import { Service } from '../service';
import { RevenexxException, Client, type Payload, UploadProgress } from '../client';
import type { Models } from '../models';


export class SalesRepsActingFor {
    client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. This list is the answer to three different questions, each one a filter: `?rep_code=` is what one rep has been doing, `?organization_id=` is what happened inside one customer — the question a buyer asks when an order appears that nobody there remembers placing — and `?contact_id=` is every occasion somebody acted as one person, which is what an erasure request is served by. Sort with `order=started_at.desc` for the most recent first. An entry with no `ended_at` is a session nobody closed, which is a fact rather than a missing value.
     *
     * @param {string} params.id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} params.repCode - Every occasion one rep acted for a buyer. The audit question "what has this rep been doing" is exactly this filter.
     * @param {string} params.organizationId - Every occasion a rep acted inside one customer — the question a buyer asks when an order appears that nobody there remembers placing.
     * @param {string} params.contactId - Every occasion a rep acted as one particular buyer. This is the filter an erasure request is served by.
     * @param {string} params.startedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the rep began acting for the buyer. Written when the entry is recorded, and it may be sent explicitly by whatever recorded it — a system that noticed afterwards must be able to say WHEN rather than when it got round to writing it down. Defaults to the moment of the write.
     * @param {string} params.endedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the rep stopped. Nullable, and a null is a FACT rather than a gap: it is a session nobody closed — the tab was shut, the token expired, the tablet went flat. There is no route that fills it in later, because this log is append-only; whoever records the entry records what they know.
     * @param {string} params.reason - Filter by the exact reason recorded. An equality over free text, so it is useful for a value a system writes and not for one a person typed.
     * @param {string} params.createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {number} params.limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} params.offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} params.order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    salesRepsImpersonationsList(params?: { id?: string, repCode?: string, organizationId?: string, contactId?: string, startedAt?: string, endedAt?: string, reason?: string, createdAt?: string, limit?: number, offset?: number, order?: string }): Promise<{}>;
    /**
     * An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. This list is the answer to three different questions, each one a filter: `?rep_code=` is what one rep has been doing, `?organization_id=` is what happened inside one customer — the question a buyer asks when an order appears that nobody there remembers placing — and `?contact_id=` is every occasion somebody acted as one person, which is what an erasure request is served by. Sort with `order=started_at.desc` for the most recent first. An entry with no `ended_at` is a session nobody closed, which is a fact rather than a missing value.
     *
     * @param {string} id - Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
     * @param {string} repCode - Every occasion one rep acted for a buyer. The audit question "what has this rep been doing" is exactly this filter.
     * @param {string} organizationId - Every occasion a rep acted inside one customer — the question a buyer asks when an order appears that nobody there remembers placing.
     * @param {string} contactId - Every occasion a rep acted as one particular buyer. This is the filter an erasure request is served by.
     * @param {string} startedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the rep began acting for the buyer. Written when the entry is recorded, and it may be sent explicitly by whatever recorded it — a system that noticed afterwards must be able to say WHEN rather than when it got round to writing it down. Defaults to the moment of the write.
     * @param {string} endedAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the rep stopped. Nullable, and a null is a FACT rather than a gap: it is a session nobody closed — the tab was shut, the token expired, the tablet went flat. There is no route that fills it in later, because this log is append-only; whoever records the entry records what they know.
     * @param {string} reason - Filter by the exact reason recorded. An equality over free text, so it is useful for a value a system writes and not for one a person typed.
     * @param {string} createdAt - Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
     * @param {number} limit - Page size (default 50, max 200). A larger value is clamped rather than refused.
     * @param {number} offset - Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
     * @param {string} order - Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsImpersonationsList(id?: string, repCode?: string, organizationId?: string, contactId?: string, startedAt?: string, endedAt?: string, reason?: string, createdAt?: string, limit?: number, offset?: number, order?: string): Promise<{}>;
    salesRepsImpersonationsList(
        paramsOrFirst?: { id?: string, repCode?: string, organizationId?: string, contactId?: string, startedAt?: string, endedAt?: string, reason?: string, createdAt?: string, limit?: number, offset?: number, order?: string } | string,
        ...rest: [(string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (string)?, (number)?, (number)?, (string)?]    
    ): Promise<{}> {
        let params: { id?: string, repCode?: string, organizationId?: string, contactId?: string, startedAt?: string, endedAt?: string, reason?: string, createdAt?: string, limit?: number, offset?: number, order?: string };
        
        if (!paramsOrFirst || (paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id?: string, repCode?: string, organizationId?: string, contactId?: string, startedAt?: string, endedAt?: string, reason?: string, createdAt?: string, limit?: number, offset?: number, order?: string };
        } else {
            params = {
                id: paramsOrFirst as string,
                repCode: rest[0] as string,
                organizationId: rest[1] as string,
                contactId: rest[2] as string,
                startedAt: rest[3] as string,
                endedAt: rest[4] as string,
                reason: rest[5] as string,
                createdAt: rest[6] as string,
                limit: rest[7] as number,
                offset: rest[8] as number,
                order: rest[9] as string            
            };
        }
        
        const id = params.id;
        const repCode = params.repCode;
        const organizationId = params.organizationId;
        const contactId = params.contactId;
        const startedAt = params.startedAt;
        const endedAt = params.endedAt;
        const reason = params.reason;
        const createdAt = params.createdAt;
        const limit = params.limit;
        const offset = params.offset;
        const order = params.order;


        const apiPath = '/v1/sales-reps/impersonations';
        const apiPayload: Payload = {};
        if (typeof id !== 'undefined') {
            apiPayload['id'] = id;
        }
        if (typeof repCode !== 'undefined') {
            apiPayload['rep_code'] = repCode;
        }
        if (typeof organizationId !== 'undefined') {
            apiPayload['organization_id'] = organizationId;
        }
        if (typeof contactId !== 'undefined') {
            apiPayload['contact_id'] = contactId;
        }
        if (typeof startedAt !== 'undefined') {
            apiPayload['started_at'] = startedAt;
        }
        if (typeof endedAt !== 'undefined') {
            apiPayload['ended_at'] = endedAt;
        }
        if (typeof reason !== 'undefined') {
            apiPayload['reason'] = reason;
        }
        if (typeof createdAt !== 'undefined') {
            apiPayload['created_at'] = createdAt;
        }
        if (typeof limit !== 'undefined') {
            apiPayload['limit'] = limit;
        }
        if (typeof offset !== 'undefined') {
            apiPayload['offset'] = offset;
        }
        if (typeof order !== 'undefined') {
            apiPayload['order'] = order;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. ⚠ Write this BEFORE the buyer session is minted, not after. The session such a handover creates is a BUYER session, so from the moment it exists every other app sees the contact and not the rep — and an entry written afterwards is an entry that a crash in between loses, leaving an order nobody can attribute. Three fields are owed. `started_at` defaults to the moment of the write and may be sent explicitly, because a system that noticed afterwards has to be able to say when it really began. `ended_at` and `reason` are optional and are written HERE or never: there is no route that fills them in later.
     *
     * @param {string} params.contactId - WHICH buyer the rep acted as — the contact in the organization, as the customers app knows them. It is the buyer and not the rep: the session that will be minted for this is a BUYER session, so on every other app the resulting order looks exactly as though this contact placed it. That is the reason this table exists at all.
     * @param {string} params.organizationId - WHICH customer, as the customers app knows the organization. Nothing here checks that the organization exists — it lives in another app, and a call on every write would fail a whole import for one organization somebody archived.
     * @param {string} params.repCode - WHICH rep this row is about, by their `code` rather than by their row id. The code is what an ERP already holds, so an import can write this row before it has ever read an id out of this app. There is no foreign key behind it: the check is a membership test against the rep table on every write, and a code that names no rep is refused with 400 `unknown_rep`. It is also why a rep's code cannot be renamed and why a rep carrying rows here cannot be deleted.
     * @param {string} params.endedAt - When the rep stopped. Nullable, and a null is a FACT rather than a gap: it is a session nobody closed — the tab was shut, the token expired, the tablet went flat. There is no route that fills it in later, because this log is append-only; whoever records the entry records what they know.
     * @param {string} params.reason - Why the rep acted for this buyer, in the words of whoever recorded it — "placed a telephone order", "checked a price the customer disputed". Optional and never validated: a log that refused an unfamiliar reason would be a log with a gap in it.
     * @param {string} params.startedAt - When the rep began acting for the buyer. Written when the entry is recorded, and it may be sent explicitly by whatever recorded it — a system that noticed afterwards must be able to say WHEN rather than when it got round to writing it down. Defaults to the moment of the write.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Impersonation>}
     */
    salesRepsImpersonationsCreate(params: { contactId: string, organizationId: string, repCode: string, endedAt?: string, reason?: string, startedAt?: string }): Promise<Models.Impersonation>;
    /**
     * An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. ⚠ Write this BEFORE the buyer session is minted, not after. The session such a handover creates is a BUYER session, so from the moment it exists every other app sees the contact and not the rep — and an entry written afterwards is an entry that a crash in between loses, leaving an order nobody can attribute. Three fields are owed. `started_at` defaults to the moment of the write and may be sent explicitly, because a system that noticed afterwards has to be able to say when it really began. `ended_at` and `reason` are optional and are written HERE or never: there is no route that fills them in later.
     *
     * @param {string} contactId - WHICH buyer the rep acted as — the contact in the organization, as the customers app knows them. It is the buyer and not the rep: the session that will be minted for this is a BUYER session, so on every other app the resulting order looks exactly as though this contact placed it. That is the reason this table exists at all.
     * @param {string} organizationId - WHICH customer, as the customers app knows the organization. Nothing here checks that the organization exists — it lives in another app, and a call on every write would fail a whole import for one organization somebody archived.
     * @param {string} repCode - WHICH rep this row is about, by their `code` rather than by their row id. The code is what an ERP already holds, so an import can write this row before it has ever read an id out of this app. There is no foreign key behind it: the check is a membership test against the rep table on every write, and a code that names no rep is refused with 400 `unknown_rep`. It is also why a rep's code cannot be renamed and why a rep carrying rows here cannot be deleted.
     * @param {string} endedAt - When the rep stopped. Nullable, and a null is a FACT rather than a gap: it is a session nobody closed — the tab was shut, the token expired, the tablet went flat. There is no route that fills it in later, because this log is append-only; whoever records the entry records what they know.
     * @param {string} reason - Why the rep acted for this buyer, in the words of whoever recorded it — "placed a telephone order", "checked a price the customer disputed". Optional and never validated: a log that refused an unfamiliar reason would be a log with a gap in it.
     * @param {string} startedAt - When the rep began acting for the buyer. Written when the entry is recorded, and it may be sent explicitly by whatever recorded it — a system that noticed afterwards must be able to say WHEN rather than when it got round to writing it down. Defaults to the moment of the write.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Impersonation>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsImpersonationsCreate(contactId: string, organizationId: string, repCode: string, endedAt?: string, reason?: string, startedAt?: string): Promise<Models.Impersonation>;
    salesRepsImpersonationsCreate(
        paramsOrFirst: { contactId: string, organizationId: string, repCode: string, endedAt?: string, reason?: string, startedAt?: string } | string,
        ...rest: [(string)?, (string)?, (string)?, (string)?, (string)?]    
    ): Promise<Models.Impersonation> {
        let params: { contactId: string, organizationId: string, repCode: string, endedAt?: string, reason?: string, startedAt?: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { contactId: string, organizationId: string, repCode: string, endedAt?: string, reason?: string, startedAt?: string };
        } else {
            params = {
                contactId: paramsOrFirst as string,
                organizationId: rest[0] as string,
                repCode: rest[1] as string,
                endedAt: rest[2] as string,
                reason: rest[3] as string,
                startedAt: rest[4] as string            
            };
        }
        
        const contactId = params.contactId;
        const organizationId = params.organizationId;
        const repCode = params.repCode;
        const endedAt = params.endedAt;
        const reason = params.reason;
        const startedAt = params.startedAt;

        if (typeof contactId === 'undefined') {
            throw new RevenexxException('Missing required parameter: "contactId"');
        }
        if (typeof organizationId === 'undefined') {
            throw new RevenexxException('Missing required parameter: "organizationId"');
        }
        if (typeof repCode === 'undefined') {
            throw new RevenexxException('Missing required parameter: "repCode"');
        }

        const apiPath = '/v1/sales-reps/impersonations';
        const apiPayload: Payload = {};
        if (typeof contactId !== 'undefined') {
            apiPayload['contact_id'] = contactId;
        }
        if (typeof endedAt !== 'undefined') {
            apiPayload['ended_at'] = endedAt;
        }
        if (typeof organizationId !== 'undefined') {
            apiPayload['organization_id'] = organizationId;
        }
        if (typeof reason !== 'undefined') {
            apiPayload['reason'] = reason;
        }
        if (typeof repCode !== 'undefined') {
            apiPayload['rep_code'] = repCode;
        }
        if (typeof startedAt !== 'undefined') {
            apiPayload['started_at'] = startedAt;
        }
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
            'content-type': 'application/json',
        }

        return this.client.call(
            'post',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. This route exists for ONE reason and it is not editing: `contact_id` names a person, so an erasure request has to be able to reach these rows. Everything else about the log is append-only — there is no update route, and this is a removal rather than a correction. Deleting an entry destroys the only record that the session happened at all, so an operator reaching for it to tidy a list is reaching for the wrong thing.
     *
     * @param {string} params.id - The entry to erase.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     */
    salesRepsImpersonationsDelete(params: { id: string }): Promise<{}>;
    /**
     * An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. This route exists for ONE reason and it is not editing: `contact_id` names a person, so an erasure request has to be able to reach these rows. Everything else about the log is append-only — there is no update route, and this is a removal rather than a correction. Deleting an entry destroys the only record that the session happened at all, so an operator reaching for it to tidy a list is reaching for the wrong thing.
     *
     * @param {string} id - The entry to erase.
     * @throws {RevenexxException}
     * @returns {Promise<{}>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsImpersonationsDelete(id: string): Promise<{}>;
    salesRepsImpersonationsDelete(
        paramsOrFirst: { id: string } | string    
    ): Promise<{}> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/impersonations/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'delete',
            uri,
            apiHeaders,
            apiPayload
        );
    }

    /**
     * An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. The route that turns an id back into an entry, which is what an audit trail on another record links to. What is NOT here is a route that edits it: the entry says what happened, and a log that could be corrected afterwards is an opinion.
     *
     * @param {string} params.id - The entry to read.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Impersonation>}
     */
    salesRepsImpersonationsGet(params: { id: string }): Promise<Models.Impersonation>;
    /**
     * An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. The route that turns an id back into an entry, which is what an audit trail on another record links to. What is NOT here is a route that edits it: the entry says what happened, and a log that could be corrected afterwards is an opinion.
     *
     * @param {string} id - The entry to read.
     * @throws {RevenexxException}
     * @returns {Promise<Models.Impersonation>}
     * @deprecated Use the object parameter style method for a better developer experience.
     */
    salesRepsImpersonationsGet(id: string): Promise<Models.Impersonation>;
    salesRepsImpersonationsGet(
        paramsOrFirst: { id: string } | string    
    ): Promise<Models.Impersonation> {
        let params: { id: string };
        
        if ((paramsOrFirst && typeof paramsOrFirst === 'object' && !Array.isArray(paramsOrFirst))) {
            params = (paramsOrFirst || {}) as { id: string };
        } else {
            params = {
                id: paramsOrFirst as string            
            };
        }
        
        const id = params.id;

        if (typeof id === 'undefined') {
            throw new RevenexxException('Missing required parameter: "id"');
        }

        const apiPath = '/v1/sales-reps/impersonations/{id}'.replace('{id}', id);
        const apiPayload: Payload = {};
        const uri = new URL(this.client.config.endpoint + apiPath);

        const apiHeaders: { [header: string]: string } = {
        }

        return this.client.call(
            'get',
            uri,
            apiHeaders,
            apiPayload
        );
    }
}
