export enum AvatarsGetCreditCardCode {
    Amex = 'amex',
    Argencard = 'argencard',
    Cabal = 'cabal',
    Cencosud = 'cencosud',
    Diners = 'diners',
    Discover = 'discover',
    Elo = 'elo',
    Hipercard = 'hipercard',
    Jcb = 'jcb',
    Mastercard = 'mastercard',
    Naranja = 'naranja',
    Targetashopping = 'targeta-shopping',
    Unionpay = 'unionpay',
    Visa = 'visa',
    Mir = 'mir',
    Maestro = 'maestro',
    Rupay = 'rupay',
}