export enum OrderVocabularySummaryName {
    Cancellationscopes = 'cancellation-scopes',
    Commentvisibilities = 'comment-visibilities',
    Discountappliesto = 'discount-applies-to',
    Discounteffectkinds = 'discount-effect-kinds',
    Discountplacements = 'discount-placements',
    Discountsources = 'discount-sources',
    Discountvaluetypes = 'discount-value-types',
    Fulfillmentstatuses = 'fulfillment-statuses',
    Itemtypes = 'item-types',
    Paymentstatuses = 'payment-statuses',
    Refundmodes = 'refund-modes',
    Returnreasontones = 'return-reason-tones',
    Returnresolutions = 'return-resolutions',
    Returnstatuses = 'return-statuses',
    Statuses = 'statuses',
}